export const ACCESSORIES = [
  {
    id: 'anker-prime-100w-gan-charger',
    name: 'Anker Prime 100W GaN Wall Charger (3-Port Multi-Device Fast Charger)',
    brand: 'Anker',
    category: 'Accessories',
    sku: 'ANK-PRM-100W-3P',
    price: 5999,
    originalPrice: 6999,
    stock: 36,
    rating: 4.8,
    reviewCount: 2450,
    tagline: 'GaNPrime technology. 100W max single-port output. 43% smaller than Apple 96W.',
    description: 'Compact 3-port fast wall charger with two USB-C and one USB-A ports, GaNPrime power architecture, ActiveShield 2.0 temperature monitoring, and foldable prongs.',
    fullDescription: 'Anker Prime 100W fast charger powers your MacBook Pro, iPhone, and AirPods simultaneously from one wall outlet. Dynamic Power Distribution dynamically shifts wattage based on device requirements.',
    featured: true,
    newArrival: true,
    tag: 'GaN Pioneer',
    specifications: {
      'Total Wattage': '100W Max',
      'Port Layout': '2x USB-C (100W Max each solo) + 1x USB-A (22.5W Max)',
      'Charging Protocol': 'Power Delivery 3.0, PPS (Programmable Power Supply), Quick Charge 4.0+',
      'Safety System': 'ActiveShield 2.0 monitors temperature over 3 million times per day',
    },
    features: [
      'Powers an M3 MacBook Pro and flagship smartphone simultaneously at high speeds',
      '43% more compact volume than original single-port 96W laptop chargers',
      'ActiveShield 2.0 real-time thermal throttling protects connected device batteries',
    ],
    dimensions: '60.5 x 44 x 39 mm',
    weight: '183 grams',
    warranty: '2-Year Anker Brand Warranty',
    shippingInfo: 'Fast dispatch within 24 hours of purchase.',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'anker-737-power-bank-24k',
    name: 'Anker 737 Power Bank (PowerCore 24K, 140W Two-Way Fast Charging)',
    brand: 'Anker',
    category: 'Accessories',
    sku: 'ANK-737-24K-140W',
    price: 9999,
    originalPrice: 12999,
    stock: 24,
    rating: 4.9,
    reviewCount: 3820,
    tagline: '24,000mAh capacity. 140W ultra-fast two-way charging. Smart digital display.',
    description: 'High-capacity battery bank capable of 140W output via Power Delivery 3.1. Features colorful smart digital display showing live wattage, battery health, and recharge countdown.',
    fullDescription: 'The Anker 737 is the undisputed king of portable power banks. Capable of charging a 16-inch MacBook Pro to 50% in just 40 minutes, while also recharging itself at 140W speeds.',
    featured: true,
    newArrival: false,
    tag: '140W Powerhouse',
    specifications: {
      'Capacity': '24,000 mAh (86.4 Wh airline carry-on compliant)',
      'Output Ports': '2x USB-C (140W Max PD 3.1) + 1x USB-A (18W Max)',
      'Recharge Speed': 'Recharges completely from 0 to 100% in 52 minutes at 140W input',
      'Smart Screen': 'TFT color display with real-time wattage, temperature, and cycle count',
    },
    features: [
      'Full 140W Power Delivery 3.1 output can charge high-end gaming laptops on the move',
      'Smart digital display reveals real-time charging status and internal battery temp',
      'Airline flight safe: compliant with international TSA and DGCA aviation guidelines',
    ],
    dimensions: '155.8 x 54.6 x 49.6 mm',
    weight: '635 grams',
    warranty: '2-Year Official Anker Warranty',
    shippingInfo: 'Standard 2-3 business day surface/air dispatch.',
    image: 'https://images.unsplash.com/photo-1609592426861-12501a3845ff?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1609592426861-12501a3845ff?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'belkin-boostcharge-pro-3in1-magsafe',
    name: 'Belkin BoostCharge Pro 3-in-1 Wireless Charging Stand with MagSafe 15W (White)',
    brand: 'Belkin',
    category: 'Accessories',
    sku: 'BLK-BCP-3IN1-WHT',
    price: 12999,
    originalPrice: 14999,
    stock: 19,
    rating: 4.8,
    reviewCount: 1680,
    tagline: 'Official Apple 15W MagSafe fast charging. Architectural stainless steel design.',
    description: 'Premier 3-in-1 wireless charging tree charging iPhone with 15W official MagSafe, fast charges Apple Watch Series 7/8/9/10/Ultra, and dedicated Qi charging pad for AirPods.',
    fullDescription: 'Elevate your nightstand or executive desk. Built with premium stainless steel branches and weighted silicone base, allowing you to charge iPhone horizontally in iOS StandBy mode.',
    featured: false,
    newArrival: false,
    tag: 'Apple Certified',
    specifications: {
      'Charging Surfaces': '1x Official 15W MagSafe + 1x Apple Watch Fast Charger + 1x 5W Qi Base',
      'Materials': 'Polished stainless steel arms with weighted soft-touch base',
      'StandBy Support': 'Holds iPhone in landscape orientation for iOS StandBy clock display',
      'Included Power Supply': '40W dedicated barrel power adapter with braided cable',
    },
    features: [
      'Official Apple Made for MagSafe certification guarantees full 15W wireless speed',
      'Apple Watch fast charging module charges Series 9 / Ultra up to 33% faster',
      'Charge in portrait for notifications or rotate into landscape to watch videos',
    ],
    dimensions: '165 x 135 x 135 mm',
    weight: '812 grams (solid anti-slip base)',
    warranty: '2-Year Belkin Manufacturer Warranty with Connected Equipment Warranty',
    shippingInfo: 'Fast dispatch within 24 hours.',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'apple-magsafe-battery-pack',
    name: 'Apple MagSafe Battery Pack with Reverse Wireless Charging',
    brand: 'Apple',
    category: 'Accessories',
    sku: 'APL-MAGSAFE-BAT',
    price: 9900,
    originalPrice: 9900,
    stock: 28,
    rating: 4.6,
    reviewCount: 2890,
    tagline: 'Snaps magnetically to iPhone. Smart iOS battery widget integration.',
    description: 'Magnetic wireless power bank engineered by Apple. Aligns automatically with iPhone 12/13/14/15/16 models, provides seamless iOS battery status integration, and reverse wireless charging.',
    fullDescription: 'The Apple MagSafe Battery Pack snaps onto the back of your iPhone securely. Charges on the go at up to 7.5W wireless speed, and doubles as a 15W MagSafe desk pad when plugged into a 20W USB-C charger.',
    featured: false,
    newArrival: false,
    tag: 'Original Apple',
    specifications: {
      'Attachment': 'Apple MagSafe neodymium magnetic array alignment',
      'Charging Speeds': 'Up to 7.5W on the go, up to 15W when connected to 20W+ power adapter',
      'Compatibility': 'iPhone 12 through iPhone 16 series',
      'Pass-Through': 'Pass-through bidirectional reverse wireless charging via iPhone',
    },
    features: [
      'Integrated with iOS: view battery level on lock screen and Battery Widget',
      'Intelligent thermal management pauses charging at 80% if battery becomes warm',
      'Silky smooth soft-touch matte polycarbonate exterior',
    ],
    dimensions: '95.8 x 64.2 x 11.3 mm',
    weight: '115 grams',
    warranty: '1-Year Apple Warranty',
    shippingInfo: 'Standard 2-3 business day courier delivery.',
    image: 'https://images.unsplash.com/photo-1609592426861-12501a3845ff?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1609592426861-12501a3845ff?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'apple-magic-mouse-black',
    name: 'Apple Magic Mouse (Black Multi-Touch Surface, USB-C)',
    brand: 'Apple',
    category: 'Accessories',
    sku: 'APL-MGC-MSE-BLK',
    price: 9500,
    originalPrice: 9500,
    stock: 25,
    rating: 4.5,
    reviewCount: 1840,
    tagline: 'Smooth Multi-Touch glass surface. Built-in USB-C rechargeable battery.',
    description: 'Wireless Bluetooth mouse featuring full Multi-Touch gesture support across its top glass surface. Swipe between web pages, scroll through documents, and recharge via modern USB-C.',
    fullDescription: 'Magic Mouse pairs automatically with your Mac. Its continuous smooth top surface detects gestures seamlessly, allowing fluid inertial scrolling in any direction with a single finger swipe.',
    featured: false,
    newArrival: true,
    tag: 'Mac Essential',
    specifications: {
      'Surface': 'Continuous Multi-Touch glass shell with gesture detection',
      'Tracking': 'Laser tracking engine with optimized foot glide rails',
      'Connectivity': 'Bluetooth Low Energy with automatic Mac pairing',
      'Port': 'USB-C charging port (includes woven USB-C to USB-C cable)',
      'Battery': 'Internal rechargeable lithium-ion (lasts approx 1 month per charge)',
    },
    features: [
      'Multi-Touch surface lets you swipe between desktops, scroll, and double-tap zoom',
      'Optimized acoustic foot rails glide smoothly across wood and desk mats',
      'Modern USB-C port charges device rapidly with standard Mac cables',
    ],
    dimensions: '113.5 x 57.1 x 21.6 mm',
    weight: '99 grams',
    warranty: '1-Year Apple India Warranty',
    shippingInfo: 'Fast dispatch within 24 hours of confirmation.',
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'apple-magic-trackpad-black',
    name: 'Apple Magic Trackpad (Black Multi-Touch Surface, USB-C)',
    brand: 'Apple',
    category: 'Accessories',
    sku: 'APL-MGC-TRK-BLK',
    price: 14500,
    originalPrice: 14500,
    stock: 18,
    rating: 4.8,
    reviewCount: 1920,
    tagline: 'Force Touch technology. Edge-to-edge glass. Complete macOS gesture set.',
    description: 'Wireless rechargeable trackpad with full suite of Multi-Touch gestures and Force Touch technology. Sensors detect subtle differences in pressure, enabling deeper interactions with macOS.',
    fullDescription: 'Magic Trackpad features a large edge-to-edge glass surface area that makes scrolling and swiping more comfortable than ever. Pairs automatically with your Mac and charges via USB-C.',
    featured: false,
    newArrival: true,
    tag: 'Studio Trackpad',
    specifications: {
      'Technology': 'Force Touch click sensors with haptic feedback engine',
      'Surface': 'Edge-to-edge frosted tactile glass',
      'Connectivity': 'Bluetooth Low Energy + USB-C wired mode',
      'Battery': 'Internal battery lasts over a month between charges',
    },
    features: [
      'Force Touch click enables pressure-sensitive Look Up, file previewing, and pressure drawing',
      'Large surface area provides ample room for 3-finger and 4-finger navigation gestures',
      'Includes woven black USB-C to USB-C charging cable in box',
    ],
    dimensions: '160 x 114.9 x 4.9 ~ 10.9 mm',
    weight: '230 grams',
    warranty: '1-Year Apple Warranty',
    shippingInfo: 'Fast courier delivery across India.',
    image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'sandisk-extreme-pro-1tb-ssd',
    name: 'SanDisk Extreme Pro 1TB Portable SSD USB 3.2 Gen 2x2 (2000MB/s)',
    brand: 'SanDisk',
    category: 'Accessories',
    sku: 'SND-EXTPRO-1TB',
    price: 13499,
    originalPrice: 18999,
    stock: 31,
    rating: 4.8,
    reviewCount: 3740,
    tagline: 'Blazing 2000 MB/s read and write speeds. Forged aluminum chassis with IP55.',
    description: 'Rugged professional NVMe portable SSD with USB 3.2 Gen 2x2 interface, forged aluminum chassis acting as a heatsink, carabiner loop, and IP55 water/dust resistance.',
    fullDescription: 'SanDisk Extreme Pro Portable SSD offers powerful NVMe solid-state performance with sequential read and write speeds up to 2,000 MB/s. Tough enough for outdoor field production with up to 3-meter drop protection.',
    featured: false,
    newArrival: false,
    tag: 'Field Production',
    specifications: {
      'Interface': 'USB 3.2 Gen 2x2 (20Gbps Type-C)',
      'Sequential Performance': 'Up to 2000 MB/s Read & 2000 MB/s Write',
      'Durability': 'IP55 water and dust resistance, 3-meter drop resistance',
      'Security': '256-bit AES hardware password encryption included',
    },
    features: [
      'Forged aluminum chassis pulls heat away from the NVMe core during sustained data dumps',
      'Handy carabiner loop secures drive to camera harness, backpack, or belt loop',
      'Directly compatible with iPhone 15/16 Pro 4K 60fps ProRes direct video recording',
    ],
    dimensions: '110.26 x 57.34 x 10.22 mm',
    weight: '77.5 grams',
    warranty: '5-Year SanDisk India Limited Warranty',
    shippingInfo: 'Fast dispatch within 24 hours.',
    image: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'spigen-arcfield-65w-gan-charger',
    name: 'Spigen ArcField 65W GaN Dual USB-C Fast Wall Charger',
    brand: 'Spigen',
    category: 'Accessories',
    sku: 'SPG-ARC65-GAN',
    price: 2999,
    originalPrice: 3599,
    stock: 42,
    rating: 4.7,
    reviewCount: 2680,
    tagline: 'GaN III technology. Dual 65W/30W power sharing. Compact pocket size.',
    description: 'Dual port USB-C GaN fast wall charger with Power Delivery 3.0 and PPS 45W Samsung Super Fast Charging 2.0 support. Compact form factor with intelligent power allocation.',
    fullDescription: 'Spigen ArcField 65W utilizes latest generation GaN III chips for cooler operation and maximum energy efficiency. Ideal for powering ultrabooks, tablets, and phones simultaneously.',
    featured: false,
    newArrival: false,
    tag: 'Compact Travel',
    specifications: {
      'Total Output': '65W Max',
      'Single Port Output': 'USB-C1 or USB-C2 up to 65W (Supports Samsung 45W PPS)',
      'Dual Port Sharing': '40W + 25W simultaneous output',
      'Technology': 'GaN III (Gallium Nitride) with AirBoost and IntelligentSafety',
    },
    features: [
      'Supports Samsung 45W Super Fast Charging 2.0 for Galaxy S24/S25 Ultra',
      'Intelligent power distribution auto-allocates optimal voltage to both connected devices',
      'Foldable plug pins prevent scratching inside travel laptop sleeves',
    ],
    dimensions: '48 x 48 x 28 mm',
    weight: '110 grams',
    warranty: '2-Year Spigen Domestic Warranty',
    shippingInfo: 'Standard 2-3 business day courier delivery.',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'satechi-dual-sided-eco-leather-pad',
    name: 'Satechi Dual-Sided Eco-Leather Deskmate Desk Pad (Midnight Blue)',
    brand: 'Satechi',
    category: 'Accessories',
    sku: 'SAT-DESKPAD-BLU',
    price: 3499,
    originalPrice: 4299,
    stock: 26,
    rating: 4.8,
    reviewCount: 1410,
    tagline: 'Premium reversible vegan eco-leather. Water-resistant desk protection.',
    description: 'Reversible desk mat crafted from quality Polyurethane (PU) eco-leather with Midnight Blue on one side and Warm Grey on the reverse. Protects wooden desks against scratches and spills.',
    fullDescription: 'Elevate your workspace aesthetics with the Satechi Eco-Leather Deskmate. Safe for delicate varnished surfaces, water-resistant for easy damp-cloth cleaning, and wide enough for laptop, keyboard, and mouse.',
    featured: false,
    newArrival: false,
    tag: 'Desk Aesthetics',
    specifications: {
      'Material': 'High-density Polyurethane (PU) vegan leather with perimeter stitching',
      'Dimensions': '58.4 x 31.0 cm (23 x 12.2 inches)',
      'Design': 'Reversible two-tone color scheme',
      'Maintenance': 'Water-resistant surface cleans easily with a damp microfiber cloth',
    },
    features: [
      'Dual-sided color allows switching workspace mood between vibrant blue and executive grey',
      'Protects your wooden desk surface from keyboard scratches, pen marks, and hot coffee mugs',
      'Provides a smooth, friction-free tracking surface for optical and laser mice',
    ],
    dimensions: '584 x 310 x 2 mm',
    weight: '340 grams',
    warranty: '1-Year Satechi Manufacturer Warranty',
    shippingInfo: 'Ships rolled in protective cylinder tube.',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'ugreen-revodok-pro-109-hub',
    name: 'UGREEN Revodok Pro 109 9-in-1 4K 60Hz Dual Display USB-C Hub',
    brand: 'UGREEN',
    category: 'Accessories',
    sku: 'UGR-REVODOK-109',
    price: 4999,
    originalPrice: 6999,
    stock: 33,
    rating: 4.7,
    reviewCount: 2190,
    tagline: 'Dual 4K 60Hz HDMI. 100W PD passthrough. Gigabit Ethernet & 5Gbps USB-A.',
    description: 'Comprehensive 9-in-1 aluminum USB-C hub featuring dual 4K 60Hz HDMI ports, 100W Power Delivery passthrough, RJ45 Gigabit Ethernet, SD/TF card reader, and three USB 3.0 ports.',
    fullDescription: 'UGREEN Revodok Pro 109 turns a single laptop USB-C port into a full workstation. Connect dual external 4K monitors, hardwired gigabit office internet, and camera SD cards in a premium aluminum case.',
    featured: false,
    newArrival: false,
    tag: '9-in-1 Dock',
    specifications: {
      'Video Output': '2x HDMI 2.0 (Dual 4K @ 60Hz with MST on Windows / Mirror on Mac)',
      'Power Input': 'USB-C 100W Power Delivery passthrough (85W to host laptop)',
      'Network': 'RJ45 Gigabit Ethernet port (10/100/1000 Mbps)',
      'Card Slots': 'SD and MicroSD card slots (supports simultaneous read/write up to 104MB/s)',
      'Data Ports': '2x USB-A 3.0 (5Gbps) + 1x USB-C 3.0 (5Gbps)',
    },
    features: [
      'Dual 4K 60Hz display support for fluid window positioning across multi-monitor desks',
      'Solid anodized aluminum alloy enclosure dissipates heat efficiently during high-speed data transfers',
      'Integrated braided nylon cable resists bending and fraying in laptop bags',
    ],
    dimensions: '128 x 45 x 16 mm',
    weight: '118 grams',
    warranty: '2-Year UGREEN Warranty',
    shippingInfo: 'Fast courier dispatch in sealed retail box.',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    ],
  },
];
