export const AUDIO = [
  {
    id: 'sony-wh-1000xm5',
    name: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones (Black)',
    brand: 'Sony',
    category: 'Headphones & Audio',
    sku: 'SON-WH1000XM5-BLK',
    price: 27990,
    originalPrice: 34990,
    stock: 23,
    rating: 4.8,
    reviewCount: 5240,
    tagline: 'Industry-leading noise cancellation with two processors and 8 microphones.',
    description: 'Flagship wireless over-ear headphones with Integrated Processor V1, HD Noise Cancelling Processor QN1, ultra-comfortable soft fit leather, and 30-hour battery life.',
    fullDescription: 'The Sony WH-1000XM5 rewrites the rules for distraction-free listening. Specially developed 30mm carbon fiber driver unit delivers natural sound quality with Hi-Res Audio Wireless and LDAC support. 4 beamforming microphones with AI noise reduction ensure crystal-clear telephone calls.',
    featured: true,
    newArrival: false,
    tag: 'Best ANC',
    specifications: {
      'Headphone Type': 'Closed-back dynamic over-ear',
      'Driver Unit': '30mm carbon fiber composite dome',
      'Frequency Response': '4 Hz - 40,000 Hz (JEITA)',
      'Active Noise Cancellation': 'Dual Processor (V1 + QN1) with 8 microphones & Auto NC Optimizer',
      'Battery Life': 'Up to 30 hours (NC ON), up to 40 hours (NC OFF)',
      'Charging Time': '3-minute quick charge yields 3 hours playback (USB-PD)',
      'Bluetooth Version': 'Bluetooth 5.2 with LDAC, AAC, SBC multipoint connection',
    },
    features: [
      'Speak-to-Chat automatically pauses playback when you start speaking',
      'Precise Voice Pickup technology uses four beamforming mics and AI reduction',
      'Multipoint connection pairs seamlessly with two Bluetooth devices at once',
    ],
    dimensions: '225 x 195 x 65 mm',
    weight: '250 grams',
    warranty: '1-Year Sony India Warranty',
    shippingInfo: 'Next-day delivery available across Tier-1 metro cities.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'sony-wf-1000xm5',
    name: 'Sony WF-1000XM5 True Wireless Noise Cancelling Earbuds (Silver)',
    brand: 'Sony',
    category: 'Headphones & Audio',
    sku: 'SON-WF1000XM5-SLV',
    price: 21990,
    originalPrice: 24990,
    stock: 29,
    rating: 4.7,
    reviewCount: 3120,
    tagline: 'Dynamic Driver X. Dual feedback microphones. Hi-Res LDAC.',
    description: 'Premium wireless earbuds with Integrated Processor V2, QN2e noise cancelling chip, deep rich bass, bone conduction sensors, and ergonomic miniature earbud fit.',
    fullDescription: 'Experience immersive silence anywhere with the Sony WF-1000XM5. Dynamic Driver X reproduces wide frequencies for detailed vocals and punchy sub-bass. Polyurethane foam tips block high-frequency ambient noise passively.',
    featured: false,
    newArrival: false,
    tag: 'Flagship TWS',
    specifications: {
      'Driver Unit': '8.4mm Dynamic Driver X',
      'Processors': 'Integrated Processor V2 + HD Noise Cancelling Processor QN2e',
      'Battery': '8 hours (earbuds) + 16 hours (case) with NC; Qi wireless charging',
      'Water Resistance': 'IPX4 splash and sweat resistance',
      'Codecs': 'LDAC, LC3, AAC, SBC',
      'Weight': '5.9 grams per earbud',
    },
    features: [
      'Bone conduction sensors and AI DNN noise reduction for call clarity',
      'Multipoint connection with seamless automatic device handoff',
      'Noise Isolation Earbud Tips crafted from exclusive polyurethane foam',
    ],
    dimensions: 'Case: 64.6 x 40.0 x 26.5 mm',
    weight: '39 grams (case) + 11.8 grams (buds)',
    warranty: '1-Year Sony India Manufacturer Warranty',
    shippingInfo: 'Express air dispatch with safe protective cushioning.',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'apple-airpods-max-usb-c',
    name: 'Apple AirPods Max (USB-C, Space Gray)',
    brand: 'Apple',
    category: 'Headphones & Audio',
    sku: 'APL-APM-USBC-SGRY',
    price: 59900,
    originalPrice: 59900,
    stock: 12,
    rating: 4.7,
    reviewCount: 2410,
    tagline: 'Computational audio. Custom acoustic driver. Personalized Spatial Audio.',
    description: 'Over-ear headphones with high-fidelity audio, Active Noise Cancellation with Transparency mode, knit-mesh canopy headband, and USB-C connectivity.',
    fullDescription: 'Apple AirPods Max combine acoustic engineering with bespoke Apple H1 headphone chips. From cushioning canopy to anodized aluminum ear cups, each part is crafted for an acoustical seal across varying head shapes.',
    featured: true,
    newArrival: true,
    tag: 'Audiophile Luxury',
    specifications: {
      'Acoustic Driver': 'Apple-designed 40mm dynamic driver',
      'Chips': 'Apple H1 headphone chip in each ear cup (10 audio cores each)',
      'Microphones': '9 microphones total (8 for ANC, 3 for voice pickup)',
      'Battery': 'Up to 20 hours listening time with ANC or Spatial Audio enabled',
      'Charging': 'USB-C (5-minute charge yields 1.5 hours playback)',
      'Sensors': 'Optical, position, case-detect, and accelerometer in each cup',
    },
    features: [
      'Personalized Spatial Audio with dynamic head tracking for theater sound',
      'Digital Crown for volume precision, track skipping, and Siri activation',
      'Smart Case puts headphones in ultra-low-power state to preserve charge',
    ],
    dimensions: '187.3 x 168.6 x 83.4 mm',
    weight: '384.8 grams',
    warranty: '1-Year Apple Warranty',
    shippingInfo: 'Insured premium shipping with tamper-evident seal.',
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'apple-airpods-pro-2-usbc',
    name: 'Apple AirPods Pro (2nd Generation, MagSafe Case USB-C)',
    brand: 'Apple',
    category: 'Headphones & Audio',
    sku: 'APL-APP2-USBC-WHT',
    price: 24900,
    originalPrice: 24900,
    stock: 35,
    rating: 4.9,
    reviewCount: 6890,
    tagline: 'Apple H2 silicon. 2x more Active Noise Cancellation. Adaptive Audio.',
    description: 'Pro-tier wireless earbuds featuring Adaptive Audio, Conversation Awareness, dust and water resistance, and MagSafe charging case with speaker and lanyard loop.',
    fullDescription: 'The 2nd generation AirPods Pro with USB-C feature the groundbreaking Apple H2 chip. Intelligently blends active noise cancellation with transparency mode based on real-time environmental noise.',
    featured: false,
    newArrival: false,
    tag: 'Bestseller',
    specifications: {
      'Audio Chip': 'Apple H2 headphone chip + Apple U1 in MagSafe charging case',
      'ANC': 'Up to 2x more active noise cancellation than previous generation',
      'Battery': 'Up to 6 hours listening time with ANC (up to 30 hours with case)',
      'Water Resistance': 'IP54 dust, sweat, and water resistant (earbuds and case)',
      'Case Charging': 'MagSafe, Apple Watch charger, Qi charger, or USB-C cable',
    },
    features: [
      'Adaptive Audio dynamically blends Transparency and ANC',
      'Touch control swipe up/down on stem for volume adjustment',
      'Precision Finding locates the charging case with built-in speaker chime',
    ],
    dimensions: 'Earbuds: 30.9 x 21.8 x 24.0 mm | Case: 45.2 x 60.6 x 21.7 mm',
    weight: '5.3 grams per bud, 50.8 grams case',
    warranty: '1-Year Apple Warranty',
    shippingInfo: 'Rapid dispatch within 24 hours across India.',
    image: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'bose-quietcomfort-ultra-headphones',
    name: 'Bose QuietComfort Ultra Wireless Noise Cancelling Headphones (Black)',
    brand: 'Bose',
    category: 'Headphones & Audio',
    sku: 'BOS-QCU-HP-BLK',
    price: 35900,
    originalPrice: 39900,
    stock: 15,
    rating: 4.8,
    reviewCount: 1980,
    tagline: 'World-class noise cancellation with Bose Immersive Audio spatialization.',
    description: 'Flagship Bose headphones with CustomTune sound calibration, breakthrough spatial audio, plush synthetic protein leather ear cushions, and 24-hour battery.',
    fullDescription: 'Bose QuietComfort Ultra headphones elevate listening to an art form. CustomTune technology automatically analyzes the unique acoustic properties of your ears and optimizes the frequency response.',
    featured: false,
    newArrival: true,
    tag: 'Spatial Master',
    specifications: {
      'Headphone Form': 'Around-ear circumaural',
      'Spatial Tech': 'Bose Immersive Audio (Still and Motion modes)',
      'Sound Calibration': 'CustomTune acoustic profiling',
      'Battery Life': 'Up to 24 hours (up to 18 hours with Immersive Audio)',
      'Bluetooth': 'Bluetooth 5.3 with Snapdragon Sound aptX Adaptive',
    },
    features: [
      'Quiet Mode for maximum ANC, Aware Mode for hearing surroundings',
      'CustomTune audio personalizes sound to the shape of your ear canal',
      'Luxury cast metal headband pivot arms with ultra-soft cushions',
    ],
    dimensions: '195 x 139 x 51 mm',
    weight: '252 grams',
    warranty: '1-Year Bose India Domestic Warranty',
    shippingInfo: 'Secure parcel dispatch with high-priority tracking.',
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'bose-quietcomfort-ultra-earbuds',
    name: 'Bose QuietComfort Ultra True Wireless Earbuds (White Smoke)',
    brand: 'Bose',
    category: 'Headphones & Audio',
    sku: 'BOS-QCU-EB-WSMK',
    price: 25900,
    originalPrice: 29900,
    stock: 18,
    rating: 4.7,
    reviewCount: 1420,
    tagline: 'Spatial audio earbuds with legendary Bose noise cancellation.',
    description: 'Next-gen wireless earbuds with Bose Immersive Audio, 9 ear tip and stability band combinations, crystal-clear noise-rejecting microphones, and IPX4 durability.',
    fullDescription: 'Bose QuietComfort Ultra Earbuds create realistic acoustic immersion that places the sound right in front of you. CustomTune technology personalizes the noise cancellation to match your ears.',
    featured: false,
    newArrival: false,
    tag: 'Ultra Comfort',
    specifications: {
      'Microphones': '4 microphones in each earbud',
      'Battery Life': 'Up to 6 hours (24 hours total with case)',
      'Water Resistance': 'IPX4 sweat and weather resistant',
      'Codecs': 'Qualcomm aptX Adaptive, AAC, SBC',
    },
    features: [
      'Umbrella-shaped soft silicone ear tips create a gentle acoustic seal',
      'Bose Fit Kit includes 3 sizes of ear tips and 3 sizes of stability bands',
      'Simple touch controls on earbuds for volume, skip, and ANC mode toggling',
    ],
    dimensions: 'Buds: 31.2 x 20.1 x 24.4 mm | Case: 66.3 x 59.4 x 26.7 mm',
    weight: '6.24 grams per earbud',
    warranty: '1-Year Bose India Warranty',
    shippingInfo: 'Fast dispatch within 24 hours of confirmation.',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'sennheiser-momentum-4-wireless',
    name: 'Sennheiser Momentum 4 Wireless ANC Headphones (Black/Copper)',
    brand: 'Sennheiser',
    category: 'Headphones & Audio',
    sku: 'SNN-M4-BLK-CPR',
    price: 24990,
    originalPrice: 34990,
    stock: 20,
    rating: 4.8,
    reviewCount: 2870,
    tagline: '60-hour marathon battery life. Audiophile-inspired 42mm transducer.',
    description: 'Premium wireless headphones with industry-leading 60-hour playback, Adaptive Noise Cancellation, customizable sound personalizer, and lightweight fold-flat design.',
    fullDescription: 'The Sennheiser Momentum 4 delivers signature audiophile acoustics with immense musicality. Equipped with a 42mm transducer system that provides brilliant dynamics, clarity, and musical impact.',
    featured: false,
    newArrival: false,
    tag: '60hr Battery',
    specifications: {
      'Transducer': '42mm dynamic driver',
      'Frequency Range': '6 Hz to 22,000 Hz',
      'Battery Life': 'Up to 60 hours playback via Bluetooth and ANC',
      'Charging Time': '10-minute fast charge gives 6 hours playtime',
      'Bluetooth': 'Bluetooth 5.2 compliant, class 1, 10 mW',
      'Codecs': 'aptX, aptX Adaptive, AAC, SBC',
    },
    features: [
      'Monumental 60 hours of continuous wireless playback on a single charge',
      'Smart Pause automatically halts music when you take headphones off',
      'Built-in 5-band EQ and Sound Personalization via Sennheiser Smart Control',
    ],
    dimensions: '180 x 195 x 46 mm',
    weight: '293 grams',
    warranty: '2-Year Sennheiser International Warranty',
    shippingInfo: 'Express courier delivery with insured shipment.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'sennheiser-hd-660s2',
    name: 'Sennheiser HD 660S2 Open-Back Audiophile Headphones',
    brand: 'Sennheiser',
    category: 'Headphones & Audio',
    sku: 'SNN-HD660S2-BLK',
    price: 44990,
    originalPrice: 54990,
    stock: 8,
    rating: 4.9,
    reviewCount: 610,
    tagline: 'Open-back circumaural reference monitor with sub-bass extension.',
    description: 'Reference-class dynamic open headphones engineered in Germany and manufactured in Ireland. Delivers deep sub-bass response, 300-ohm impedance, and crystalline midrange.',
    fullDescription: 'The HD 660S2 takes the legendary HD 600 series pedigree further. Features a revised aluminum voice coil with 300-ohm impedance matching high-end headphone amplifiers, delivering intimate vocal presence and refined soundstage.',
    featured: false,
    newArrival: false,
    tag: 'Audiophile Reference',
    specifications: {
      'Transducer Principle': 'Dynamic, open-back',
      'Transducer Size': '38mm with revised surround',
      'Impedance': '300 ohms',
      'Frequency Response': '8 Hz - 41,500 Hz',
      'Cables': 'Includes 6.3mm unbalanced cable and 4.4mm Pentaconn balanced cable',
      'Total Harmonic Distortion': '< 0.04% (1 kHz, 100 dB SPL)',
    },
    features: [
      'Acoustic open-mesh steel ear cup grilles for unrestricted airflow',
      'Detachable oxygen-free copper cables with gold-plated contact pins',
      'Plush velour ear cushions for hours of non-fatiguing reference listening',
    ],
    dimensions: '200 x 180 x 90 mm',
    weight: '260 grams (without cable)',
    warranty: '2-Year Official Sennheiser Warranty',
    shippingInfo: 'Dispatched in reinforced protective audiophile shipment.',
    image: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'jbl-tour-one-m2',
    name: 'JBL Tour One M2 Wireless Over-Ear ANC Headphones',
    brand: 'JBL',
    category: 'Headphones & Audio',
    sku: 'JBL-TOURN1-M2-BLK',
    price: 17999,
    originalPrice: 24999,
    stock: 24,
    rating: 4.6,
    reviewCount: 1560,
    tagline: 'True Adaptive Noise Cancelling with Smart Ambient and 50-hour playtime.',
    description: 'High-resolution certified wireless headphones with 40mm dynamic drivers, Personi-Fi 2.0 sound customization, 4-mic crystal call technology, and immersive spatial sound.',
    fullDescription: 'JBL Tour One M2 uses True Adaptive NC technology that listens to ambient surroundings 50,000 times per second to neutralize unwanted noise. Features Smart Talk voice recognition for seamless conversation.',
    featured: false,
    newArrival: false,
    tag: 'Value ANC',
    specifications: {
      'Driver Size': '40mm Dynamic Driver',
      'Battery Life': 'Up to 50 hours (NC off), up to 30 hours (NC on)',
      'Fast Charge': '10 minutes charging gives 5 hours playback',
      'Bluetooth': 'Bluetooth 5.3 LE Audio ready',
    },
    features: [
      'Smart Talk recognizes speech and auto-mutes audio and activates ambient mode',
      'Personi-Fi 2.0 creates a tailored listening profile using hearing test',
      'JBL Spatial Sound makes stereo movies feel like cinematic surround sound',
    ],
    dimensions: '205 x 175 x 80 mm',
    weight: '272 grams',
    warranty: '1-Year JBL India Warranty',
    shippingInfo: 'Fast courier dispatch within 24 hours.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'jbl-authentics-300',
    name: 'JBL Authentics 300 Smart Home Bluetooth & Wi-Fi Speaker',
    brand: 'JBL',
    category: 'Headphones & Audio',
    sku: 'JBL-AUTH300-BLK',
    price: 31999,
    originalPrice: 39999,
    stock: 14,
    rating: 4.7,
    reviewCount: 780,
    tagline: 'Retro Quadrex grille style. Simultaneous Google Assistant & Alexa.',
    description: 'Portable smart home speaker with iconic 1970s retro design, leather-wrapped aluminum enclosure, built-in battery with 8 hours playtime, and Dolby Atmos audio.',
    fullDescription: 'The JBL Authentics 300 combines vintage aesthetic styling with modern smart speaker power. It is the first speaker capable of running Google Assistant and Amazon Alexa simultaneously on a single unit.',
    featured: false,
    newArrival: true,
    tag: 'Smart Retro',
    specifications: {
      'Sound System': 'Stereo 2.1 (2x 25mm tweeters + 5.25-inch woofer + 6.5-inch passive radiator)',
      'Total Output Power': '100 Watts RMS',
      'Connectivity': 'Wi-Fi 6, Bluetooth 5.3, Ethernet, 3.5mm Aux-in',
      'Battery': 'Built-in rechargeable Li-ion battery (up to 8 hours playback)',
    },
    features: [
      'Simultaneous voice assistants: use Google Assistant or Alexa interchangeably',
      'Automatic self-tuning calibrates audio whenever speaker is moved to a new room',
      'Cast via AirPlay, Alexa Multi-Room Music, Spotify Connect, and Chromecast',
    ],
    dimensions: '342 x 195.6 x 180.3 mm',
    weight: '4.9 kg',
    warranty: '1-Year Harman India Warranty',
    shippingInfo: 'Secure heavy-duty packaging with express delivery.',
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'samsung-galaxy-buds3-pro',
    name: 'Samsung Galaxy Buds3 Pro (Silver)',
    brand: 'Samsung',
    category: 'Headphones & Audio',
    sku: 'SAM-BUDS3P-SLV',
    price: 19999,
    originalPrice: 22999,
    stock: 27,
    rating: 4.7,
    reviewCount: 1840,
    tagline: 'Blade lights design. 24-bit 96kHz Hi-Fi audio. Galaxy AI interpreter.',
    description: 'Next-gen blade stem design with ambient LED strip, dual amplifiers, 2-way planar speakers, adaptive noise cancellation with siren detection, and Galaxy AI live translate.',
    fullDescription: 'Samsung Galaxy Buds3 Pro delivers studio-grade 24-bit/96kHz audio with dual woofers and planar tweeters. Blade lights respond to pinch gestures and live calls while adaptive noise control tunes silence automatically.',
    featured: false,
    newArrival: true,
    tag: 'Hi-Fi Pro',
    specifications: {
      'Speaker Type': 'Enhanced 2-Way with Planar Tweeter & Dynamic Woofer',
      'Amplifier': 'Dual Amplifiers for independent woofer/tweeter control',
      'Sampling Rate': '24-bit / 96kHz SSC (Samsung Seamless Codec)',
      'Battery': 'Up to 7 hours playback (earbuds) and 30 hours total with case',
      'Water Resistance': 'IP57 water and dust resistance',
    },
    features: [
      'Real-time conversation Interpreter translation directly in ear',
      'Interactive Blade Lights with customizable illumination modes',
      'Adaptive Noise Control automatically lowers ANC when emergency siren is detected',
    ],
    dimensions: 'Earbuds: 18.1 x 20.4 x 19.8 mm',
    weight: '5.4 grams per earbud',
    warranty: '1-Year Samsung India Warranty',
    shippingInfo: 'Standard 2-3 business day courier delivery.',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'marshall-stanmore-iii',
    name: 'Marshall Stanmore III Bluetooth Home Speaker (Black)',
    brand: 'Marshall',
    category: 'Headphones & Audio',
    sku: 'MSH-STAN3-BLK',
    price: 36999,
    originalPrice: 41999,
    stock: 13,
    rating: 4.8,
    reviewCount: 1670,
    tagline: 'Legendary rock heritage. Re-engineered wider stereo soundstage.',
    description: 'Iconic home audio speaker with vintage brass control knobs, 80W total RMS output power, tweeters angled outwards with updated waveguides, and Bluetooth 5.2.',
    fullDescription: 'The Marshall Stanmore III takes center stage in any room. Built with an outward-angled tweeter architecture and updated waveguides to deliver a consistently solid, expansive soundstage that chases you around the room.',
    featured: false,
    newArrival: false,
    tag: 'Iconic Sound',
    specifications: {
      'Power Amplifiers': 'One 50 Watt Class D (woofer) + Two 15 Watt Class D (tweeters)',
      'Maximum Sound Pressure': '97 dB @ 1 m',
      'Frequency Range': '45 Hz - 20,000 Hz',
      'Inputs': 'Bluetooth 5.2, 3.5 mm Aux Input, RCA Input',
    },
    features: [
      'Analog brass control knobs for Volume, Bass, and Treble customization',
      'Dynamic Loudness balances tonal balance at all volume levels',
      '70% recycled plastic construction with vegan leather texture',
    ],
    dimensions: '350 x 203 x 188 mm',
    weight: '4.25 kg',
    warranty: '1-Year Official Marshall India Warranty',
    shippingInfo: 'Heavy-duty cushioned parcel shipment.',
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    ],
  },
];
