export const CAMERAS = [
  {
    id: 'sony-alpha-7-iv',
    name: 'Sony Alpha 7 IV Full-Frame Mirrorless Camera (Body Only)',
    brand: 'Sony',
    category: 'Cameras',
    sku: 'SON-A7M4-BODY',
    price: 209990,
    originalPrice: 224990,
    stock: 9,
    rating: 4.9,
    reviewCount: 1820,
    tagline: '33MP Exmor R sensor. BIONZ XR engine. Real-time Eye AF for photo & video.',
    description: 'The hybrid mirrorless benchmark. Features 33MP full-frame backside illuminated CMOS sensor, 4K 60p 10-bit 4:2:2 recording, 759-point phase-detection AF, and S-Cinetone color science.',
    fullDescription: 'The Sony Alpha 7 IV redefines basic full-frame standards. Featuring BIONZ XR processing power for up to 8x faster processing, Breathing Compensation, vari-angle LCD touchscreen, and live UVC/UAC 4K webcam streaming via single USB cable.',
    featured: true,
    newArrival: false,
    tag: 'Industry Benchmark',
    specifications: {
      'Image Sensor': '33.0 Megapixel 35mm full-frame Exmor R CMOS sensor',
      'Processor': 'BIONZ XR image processing engine',
      'Autofocus': '759 phase-detection points covering 94% of image area with Human, Animal, Bird Eye AF',
      'Video Recording': '4K 60p (Super 35mm crop), 4K 30p 7K oversampled, 10-bit 4:2:2 All-Intra',
      'Image Stabilization': '5.5-step 5-axis in-body optical image stabilization (IBIS)',
      'Viewfinder': '3.68M-dot Quad-VGA OLED electronic viewfinder',
    },
    features: [
      'Dual-layer mode dial allows switching Photo, Video, and S&Q with one hand',
      'Breathing Compensation maintains consistent angle of view when rack focusing',
      'Lossless Compressed RAW option preserves full dynamic range at smaller file sizes',
    ],
    dimensions: '131.3 x 96.4 x 79.8 mm',
    weight: '658 grams (including battery and memory card)',
    warranty: '2-Year Sony India Domestic Warranty',
    shippingInfo: 'High-value insured dispatch with security tamper seals.',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'sony-alpha-7c-ii',
    name: 'Sony Alpha 7C II Compact Full-Frame Mirrorless Camera (Silver Body)',
    brand: 'Sony',
    category: 'Cameras',
    sku: 'SON-A7C2-SLV',
    price: 189990,
    originalPrice: 204990,
    stock: 12,
    rating: 4.8,
    reviewCount: 940,
    tagline: '33MP full-frame in a rangefinder-style compact chassis. Dedicated AI Processing Unit.',
    description: 'Compact travel full-frame camera featuring 33MP sensor, dedicated AI deep learning AF unit, 7.0-stop 5-axis image stabilization, and 4K 60p 10-bit capture in a 514g body.',
    fullDescription: 'Sony Alpha 7C II packs the full-frame image quality of the A7 IV into an ultra-portable body. The dedicated AI Processing Unit recognizes pose estimation for humans, birds, insects, and vehicles.',
    featured: false,
    newArrival: true,
    tag: 'Compact Full Frame',
    specifications: {
      'Sensor': '33.0MP full-frame Exmor R BSI CMOS sensor',
      'AI Processing': 'Dedicated AI chip for advanced real-time subject recognition',
      'Stabilization': '7.0-step in-body optical image stabilization',
      'Video': '4K 60p (Super35) and 4K 30p 7K oversampled with S-Log3 and S-Cinetone',
      'Weight': '514 grams including battery',
    },
    features: [
      'Compact rangefinder-style top plate with front control dial and exposure comp',
      'LUT import feature enables previewing custom look profiles directly on screen',
      'Active Mode electronic stabilization delivers steady handheld walk-and-talk footage',
    ],
    dimensions: '124.0 x 71.1 x 63.4 mm',
    weight: '514 grams',
    warranty: '2-Year Official Sony Warranty',
    shippingInfo: 'Express courier dispatch with transit coverage.',
    image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'canon-eos-r6-mark-ii',
    name: 'Canon EOS R6 Mark II Mirrorless Camera (Body Only)',
    brand: 'Canon',
    category: 'Cameras',
    sku: 'CAN-R6M2-BODY',
    price: 215995,
    originalPrice: 235995,
    stock: 8,
    rating: 4.8,
    reviewCount: 1150,
    tagline: '40 fps electronic shutter. 6K oversampled 4K 60p uncropped. Dual Pixel CMOS AF II.',
    description: 'High-speed enthusiast and wedding photographer powerhouse. Features 24.2MP CMOS sensor, continuous shooting up to 40 fps, Dual Pixel CMOS AF II with vehicle and aircraft detection, and 8.0-stop IS.',
    fullDescription: 'Canon EOS R6 Mark II combines high burst speeds with low-light capability up to ISO 102,400. Records 6K oversampled full-width 4K 60p without crop, with up to 6 hours continuous recording limit.',
    featured: false,
    newArrival: false,
    tag: 'Speed King',
    specifications: {
      'Sensor': '24.2 Megapixel Full-Frame CMOS Sensor',
      'Continuous Shooting': 'Up to 40 fps with electronic shutter (12 fps mechanical)',
      'Video Quality': '4K 60p uncropped oversampled from 6K, Canon Log 3, HDR PQ',
      'Autofocus': 'Dual Pixel CMOS AF II with 1053 AF zones and deep learning subject tracking',
      'Image Stabilization': 'Up to 8.0 stops Coordinated IS with compatible RF lenses',
    },
    features: [
      'RAW Burst Mode with 0.5-second pre-shooting captures action before shutter fully pressed',
      'Dual UHS-II SD card slots for simultaneous redundant recording',
      'Dust and moisture resistant magnesium alloy body construction',
    ],
    dimensions: '138.4 x 98.4 x 88.4 mm',
    weight: '670 grams (with battery and memory card)',
    warranty: '2-Year Canon India Domestic Warranty',
    shippingInfo: 'Padded priority shipping with transit insurance.',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'canon-eos-r8-rf2450',
    name: 'Canon EOS R8 Full-Frame Mirrorless with RF 24-50mm IS STM Lens',
    brand: 'Canon',
    category: 'Cameras',
    sku: 'CAN-R8-2450-KIT',
    price: 132990,
    originalPrice: 149990,
    stock: 15,
    rating: 4.7,
    reviewCount: 820,
    tagline: 'Lightest full-frame EOS R camera. 24.2MP sensor. 40 fps electronic shutter.',
    description: 'Compact entry full-frame mirrorless camera paired with collapsible RF 24-50mm lens. Offers 24.2MP sensor, 6K oversampled 4K 60p video, Dual Pixel AF II, and Canon Log 3.',
    fullDescription: 'Canon EOS R8 brings pro-grade full-frame image quality to a featherlight 461g body. Perfect for hybrid creators and travel videographers wanting gorgeous shallow depth-of-field without heavy gear baggage.',
    featured: false,
    newArrival: false,
    tag: 'Best Entry Full Frame',
    specifications: {
      'Sensor': '24.2 Megapixel Full-Frame CMOS Sensor',
      'Lens Included': 'Canon RF 24-50mm f/4.5-6.3 IS STM Lens',
      'Video': '4K 60p uncropped 6K oversampled, Canon Log 3 10-bit 4:2:2',
      'Burst Speed': 'Up to 40 frames per second electronic shutter',
      'Weight': '461 grams (body with battery and card)',
    },
    features: [
      'Vari-angle 3.0-inch 1.62M-dot clear LCD touchscreen for vlogging',
      'Plug-and-play UVC/UAC video streaming over USB-C without capture card',
      'Subject detection for people, horses, dogs, cats, cars, and trains',
    ],
    dimensions: '132.5 x 86.1 x 70.0 mm',
    weight: '461 grams (body only)',
    warranty: '2-Year Canon Brand Warranty',
    shippingInfo: 'Fast dispatch within 2 business days.',
    image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'nikon-z6-iii',
    name: 'Nikon Z6 III Mirrorless Camera (Body Only)',
    brand: 'Nikon',
    category: 'Cameras',
    sku: 'NIK-Z6M3-BODY',
    price: 224990,
    originalPrice: 247990,
    stock: 7,
    rating: 4.9,
    reviewCount: 510,
    tagline: 'World first partially-stacked CMOS sensor. 6K 60p internal RAW. 5760k-dot EVF.',
    description: 'Groundbreaking hybrid full-frame camera with 24.5MP partially-stacked sensor, EXPEED 7 processor, internal 6K N-RAW recording, class-leading 4000 nits 5.76M-dot EVF, and 8.0 stops VR.',
    fullDescription: 'Nikon Z6 III introduces the world first partially-stacked CMOS architecture, unlocking 3.5x faster readout speeds. Features 120 fps continuous shooting, -10 EV autofocus in darkness, and professional N-RAW video.',
    featured: true,
    newArrival: true,
    tag: 'Next Gen Sensor',
    specifications: {
      'Sensor': '24.5MP Full-Frame Partially-Stacked CMOS Sensor',
      'Processor': 'EXPEED 7 flagship processing engine',
      'EVF': '5.76-million dot ultra-bright 4,000 nits DCI-P3 electronic viewfinder',
      'Video Modes': '6K 60p N-RAW internal, 5.4K 60p ProRes RAW, 4K 120p, Full HD 240p',
      'In-Body VR': '8.0-stop 5-axis vibration reduction with Focus Point VR',
    },
    features: [
      'Partially-stacked sensor provides fast electronic readout reducing rolling shutter',
      'Line-level audio input jack for professional external microphone mixers',
      'Dual slots: CFexpress Type B / XQD and UHS-II SD card compatibility',
    ],
    dimensions: '138.5 x 101.5 x 74 mm',
    weight: '760 grams (with battery and memory card)',
    warranty: '2-Year Nikon India Domestic Warranty',
    shippingInfo: 'High-value insured dispatch with secure handling.',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'fujifilm-x-t5',
    name: 'Fujifilm X-T5 Mirrorless Digital Camera (Black Body)',
    brand: 'Fujifilm',
    category: 'Cameras',
    sku: 'FUJ-XT5-BLK',
    price: 169999,
    originalPrice: 169999,
    stock: 10,
    rating: 4.8,
    reviewCount: 1390,
    tagline: '40.2MP X-Trans CMOS 5 HR sensor. 3-way tilting LCD. Classic analog dial control.',
    description: 'Photography-first mirrorless camera featuring 40.2MP high-resolution X-Trans sensor, X-Processor 5, 5-axis 7.0-stop in-body stabilization, 19 film simulation modes, and classic metal dials.',
    fullDescription: 'The Fujifilm X-T5 honors photographic tradition while packing high-tech punch. Classic analog dials for ISO, shutter speed, and exposure compensation combine with 160MP Pixel Shift Multi-Shot and tactile three-way tilting screen.',
    featured: false,
    newArrival: false,
    tag: 'Pure Photography',
    specifications: {
      'Sensor': '40.2 Megapixel X-Trans CMOS 5 HR APS-C sensor',
      'Processor': 'X-Processor 5 with AI deep-learning subject detection',
      'Film Simulations': '19 legendary Fujifilm Film Simulation modes including Nostalgic Neg',
      'LCD Screen': '3.0-inch 1.84M-dot three-way tilting touchscreen',
      'Stabilization': '7.0-stop 5-axis in-body image stabilization',
    },
    features: [
      'Dedicated analog tactile metal top dials for ISO, shutter speed, and EV compensation',
      '160MP Pixel Shift Multi-Shot mode for reproduction of ultra-fine textures',
      'Weather-resistant body sealed at 56 points against dust and moisture',
    ],
    dimensions: '129.5 x 91.0 x 63.8 mm',
    weight: '557 grams (with battery and card)',
    warranty: '2-Year Fujifilm India Warranty',
    shippingInfo: 'Express courier dispatch with padded protection.',
    image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'gopro-hero-13-black-creator',
    name: 'GoPro HERO13 Black Action Camera (Creator Edition)',
    brand: 'GoPro',
    category: 'Cameras',
    sku: 'GPR-H13B-CRTR',
    price: 44990,
    originalPrice: 49990,
    stock: 21,
    rating: 4.7,
    reviewCount: 2150,
    tagline: '5.3K 60fps video. HB-Series smart lens auto-detection. Enduro battery grip.',
    description: 'All-in-one content creation powerhouse featuring HERO13 Black camera, Volta battery grip, Media Mod with directional mic, Light Mod, and 5.3K 60fps video recording.',
    fullDescription: 'GoPro HERO13 Black Creator Edition includes magnetic latch mounting, HB-Series smart lenses that auto-configure camera aspect ratios and settings, 400fps slow motion bursts, and HLG HDR video.',
    featured: false,
    newArrival: true,
    tag: 'Creator Rig',
    specifications: {
      'Video Resolution': '5.3K 60fps, 4K 120fps, 2.7K 240fps, 720p 400fps Burst Slo-Mo',
      'Photo': '27MP with SuperPhoto, HDR, and RAW capture',
      'Lens Ecosystem': 'HB-Series interchangeable intelligent lenses with auto-sensor detection',
      'Audio': 'Directional mic mod with foam windscreen and 3.5mm mic port',
      'Battery': 'Volta grip adds 5+ hours of 4K recording time with integrated tripod legs',
    },
    features: [
      'HyperSmooth 6.0 video stabilization with 360-degree Horizon Lock',
      'Magnetic Latch mount system allows switching mounts in seconds',
      'Waterproof to 33 feet (10m) standalone without external housing',
    ],
    dimensions: '71.8 x 50.8 x 33.6 mm (camera only)',
    weight: '154 grams (camera) / 450 grams (full rig)',
    warranty: '1-Year GoPro India Domestic Warranty',
    shippingInfo: 'Fast dispatch within 24 hours of confirmation.',
    image: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'dji-osmo-pocket-3-creator',
    name: 'DJI Osmo Pocket 3 Creator Combo (1-inch CMOS Gimbal Camera)',
    brand: 'DJI',
    category: 'Cameras',
    sku: 'DJI-OP3-CRTR',
    price: 53990,
    originalPrice: 59990,
    stock: 14,
    rating: 4.9,
    reviewCount: 3420,
    tagline: '1-inch CMOS sensor. 2-inch rotatable OLED touchscreen. 3-axis mechanical gimbal.',
    description: 'Pocket-sized gimbal camera with 1-inch CMOS sensor, 4K 120fps capture, 10-bit D-Log M color, ActiveTrack 6.0 face tracking, DJI Mic 2 transmitter, and battery handle.',
    fullDescription: 'DJI Osmo Pocket 3 revolutionized mobile videography. The rotatable 2-inch OLED touchscreen lets you switch between horizontal 16:9 and vertical 9:16 social filming with a single flick of the finger.',
    featured: true,
    newArrival: false,
    tag: 'Vlog Phenomenon',
    specifications: {
      'Sensor': '1-inch CMOS sensor',
      'Display': '2.0-inch Rotatable OLED touchscreen (314 x 556, 700 nits)',
      'Gimbal': '3-axis motorized mechanical stabilization',
      'Video': '4K 120fps slow-motion, 4K 60fps HDR, 10-bit D-Log M and HLG',
      'Combo Includes': 'DJI Mic 2 transmitter, Battery handle, Mini tripod, Wide-angle lens',
    },
    features: [
      'Rotatable 2-inch OLED screen switches between landscape and portrait orientation',
      'ActiveTrack 6.0 with Face Auto-Detect keeps you centered during walk-and-talk',
      'Fast charging charges battery to 80% in just 16 minutes',
    ],
    dimensions: '139.7 x 42.2 x 33.5 mm',
    weight: '179 grams (camera body)',
    warranty: '1-Year DJI Warranty with replacement support',
    shippingInfo: 'Priority express shipping with insurance.',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    ],
  },
];
