export const DISPLAYS = [
  {
    id: 'lg-oled-c4-55-inch',
    name: 'LG OLED evo C4 55-inch 4K Smart TV (OLED55C4PSA)',
    brand: 'LG',
    category: 'TVs & Monitors',
    sku: 'LG-OLEDC4-55-4K',
    price: 134990,
    originalPrice: 179990,
    stock: 12,
    rating: 4.9,
    reviewCount: 2480,
    tagline: 'Self-lit OLED pixels. Alpha 9 AI Processor Gen7. 144Hz VRR with 0.1ms response.',
    description: 'The definitive gaming and home theater television. Features 55-inch 4K OLED evo panel with infinite contrast, Alpha 9 AI Processor Gen7, Brightness Booster, 4x HDMI 2.1 ports, and webOS 24.',
    fullDescription: 'LG OLED evo C4 brings cinema mastery to living rooms. Every pixel lights up individually for absolute true blacks and limitless contrast. Delivers 144Hz variable refresh rate certified for NVIDIA G-SYNC and AMD FreeSync Premium with Dolby Vision gaming.',
    featured: true,
    newArrival: true,
    tag: 'Home Cinema King',
    specifications: {
      'Screen Size': '55 inches (139 cm diagonal)',
      'Display Type': '4K OLED evo (3840 x 2160, self-lit pixels)',
      'Processor': 'Alpha 9 AI Processor 4K Gen7 with AI Picture Pro & AI Super Upscaling',
      'Gaming Features': '144Hz VRR, 0.1ms response time, 4x HDMI 2.1 (48Gbps), G-SYNC & FreeSync',
      'Audio': '40W 2.2 Channel sound with AI Sound Pro virtual 9.1.2 up-mixing',
      'Smart Platform': 'webOS 24 with 5 years guaranteed software upgrades',
    },
    features: [
      'Self-lit OLED evo pixels achieve pure black with zero haloing or light bleed',
      'Brightness Booster algorithm boosts individual pixel brightness for punchy highlights',
      'Comprehensive gaming dashboard with Game Optimizer and 0.1ms response time',
    ],
    dimensions: '1222 x 703 x 45.1 mm (without stand)',
    weight: '14.1 kg (without stand), 16.0 kg (with stand)',
    warranty: '3-Year Comprehensive LG India Warranty on OLED Panel',
    shippingInfo: 'Complimentary professional wall-mount installation included.',
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1526738549149-8e07eca6c147?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'lg-oled-g4-65-inch',
    name: 'LG OLED evo G4 65-inch 4K Gallery Edition (OLED65G4PSA)',
    brand: 'LG',
    category: 'TVs & Monitors',
    sku: 'LG-OLEDG4-65-GAL',
    price: 239990,
    originalPrice: 319990,
    stock: 6,
    rating: 4.9,
    reviewCount: 740,
    tagline: 'Micro Lens Array (MLA) Brightness Booster Max. Alpha 11 AI Processor. Zero-gap mount.',
    description: 'Ultra-bright reference flagship television featuring Micro Lens Array (MLA) optical technology, Alpha 11 AI processor, flush-fit Zero-Gap Gallery wall design, and 5-year panel warranty.',
    fullDescription: 'LG OLED G4 sets the absolute standard for consumer display brightness. Micro Lens Array technology places billions of microscopic convex lenses over the OLED pixels to redirect light forwards, producing up to 150% higher peak brightness.',
    featured: true,
    newArrival: false,
    tag: 'Flagship Gallery',
    specifications: {
      'Screen Size': '65 inches',
      'Panel': '4K OLED evo with Micro Lens Array (MLA+) Brightness Booster Max',
      'Processor': 'Alpha 11 AI Processor 4K (fastest LG processor with 4x AI performance)',
      'Audio': '60W 4.2 Channel with Dolby Atmos and WOW Orchestra pairing',
      'Mounting': 'Includes zero-gap flush wall mount bracket in packaging',
    },
    features: [
      'Micro Lens Array optics deliver reference HDR highlight peaks exceeding 3000 nits',
      'Flush wall mount sits totally flat against the wall like a fine art frame',
      '5-Year LG OLED panel warranty for total peace of mind',
    ],
    dimensions: '1441 x 826 x 24.3 mm',
    weight: '23.8 kg',
    warranty: '5-Year LG Official Panel Warranty',
    shippingInfo: 'Complimentary white-glove delivery, unboxing, and wall installation.',
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'samsung-neo-qled-65-qn90d',
    name: 'Samsung 65-inch Neo QLED 4K Smart TV (QN90D)',
    brand: 'Samsung',
    category: 'TVs & Monitors',
    sku: 'SAM-NQ65-QN90D',
    price: 174990,
    originalPrice: 229990,
    stock: 11,
    rating: 4.8,
    reviewCount: 1620,
    tagline: 'Quantum Matrix Technology with Mini LED. NQ4 AI Gen2 Processor. 144Hz.',
    description: 'Bright room champion featuring Quantum Mini LED backlighting, Neo Quantum HDR+, anti-glare wide viewing angle coating, and Dolby Atmos with Object Tracking Sound+.',
    fullDescription: 'Samsung Neo QLED QN90D delivers blazing highlights that pierce through sunlit Indian living rooms. Driven by NQ4 AI Gen2 processor utilizing 20 neural networks for 4K upscaling.',
    featured: false,
    newArrival: true,
    tag: 'Bright Room Master',
    specifications: {
      'Screen Size': '65 inches (163 cm diagonal)',
      'Display': 'Neo QLED Mini LED 4K (3840 x 2160, 144Hz refresh rate)',
      'Processor': 'NQ4 AI Gen2 Processor with 20 neural AI upscaling networks',
      'Anti-Reflection': 'Matte anti-glare coating reduces daytime window reflections',
      'Sound': '60W 4.2.2 Channel with Object Tracking Sound+ (OTS+)',
    },
    features: [
      'Quantum Mini LEDs 1/40th the size of conventional LEDs for ultra-fine dimming zones',
      'Anti-reflection screen coating eliminates window reflections during day matches',
      'Samsung Gaming Hub streams Xbox Cloud games directly without a console',
    ],
    dimensions: '1446.3 x 828.7 x 26.9 mm (without stand)',
    weight: '24.2 kg',
    warranty: '3-Year Samsung Comprehensive Warranty',
    shippingInfo: 'Free scheduled delivery with installation technician appointment.',
    image: 'https://images.unsplash.com/photo-1526738549149-8e07eca6c147?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1526738549149-8e07eca6c147?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'samsung-the-frame-55-ls03d',
    name: 'Samsung 55-inch The Frame QLED 4K Art TV (LS03D)',
    brand: 'Samsung',
    category: 'TVs & Monitors',
    sku: 'SAM-FR55-LS03D',
    price: 84990,
    originalPrice: 99990,
    stock: 18,
    rating: 4.7,
    reviewCount: 3150,
    tagline: 'Art Mode with anti-reflective Matte Display. Slim Fit wall-mount included.',
    description: 'Transform your room into a private gallery. Features anti-reflective Matte Display with zero glare, customizable magnetic bezels, Pantone ArtfulColor validation, and 100% Color Volume with Quantum Dot.',
    fullDescription: 'The Frame TV blends harmoniously into interior decor. When turned off, Art Mode displays museum-quality masterworks from the Louvre, Tate, and Van Gogh Museum with intelligent brightness and motion sensors.',
    featured: false,
    newArrival: false,
    tag: 'Design Icon',
    specifications: {
      'Screen Size': '55 inches',
      'Panel': 'QLED 4K with Matte Display texture and 100% Color Volume',
      'Art Store': 'Access over 2,500 artworks with motion detector and ambient light sensor',
      'Mount': 'Slim Fit Wall Mount hangs flush to the wall with single translucent One Connect cable',
    },
    features: [
      'Matte Display reduces reflections to near zero, resembling real paper texture',
      'Motion sensor turns Art Mode on when you enter the room and off when you leave',
      'Single near-invisible One Connect box moves power and HDMI cords into cabinet',
    ],
    dimensions: '1237.9 x 708.8 x 24.9 mm',
    weight: '16.9 kg',
    warranty: '1-Year Standard + 1-Year Additional Panel Warranty',
    shippingInfo: 'Free delivery and professional wall installation.',
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'sony-bravia-8-55-inch-oled',
    name: 'Sony BRAVIA 8 55-inch 4K OLED Google TV (K-55XR80)',
    brand: 'Sony',
    category: 'TVs & Monitors',
    sku: 'SON-BRV8-55-OLED',
    price: 184990,
    originalPrice: 219990,
    stock: 9,
    rating: 4.8,
    reviewCount: 910,
    tagline: 'XR Processor. Acoustic Surface Audio+ turns the screen itself into a speaker.',
    description: 'Cinema-grade OLED TV featuring XR Processor with XR Clear Image, Acoustic Surface Audio+ where actuators vibrate the glass panel to produce sound from on-screen action, and Google TV.',
    fullDescription: 'Sony BRAVIA 8 brings the creator vision directly to your home. Features Studio Calibrated modes for Netflix and Sony Pictures Core, Dolby Vision, IMAX Enhanced, and seamless PlayStation 5 auto HDR tone mapping.',
    featured: false,
    newArrival: true,
    tag: 'Acoustic Cinema',
    specifications: {
      'Screen Size': '55 inches (139 cm)',
      'Panel': '4K OLED with XR Contrast Booster 20 and XR Triluminos Pro',
      'Processor': 'XR Processor with cognitive intelligence cross-analysis',
      'Sound Tech': 'Acoustic Surface Audio+ with dual actuators and built-in subwoofers',
      'Gaming': 'Auto HDR Tone Mapping & Auto Genre Picture Mode for PS5, 4K 120Hz',
    },
    features: [
      'Acoustic Surface Audio+ vibrates the display screen so dialogue comes from actors mouths',
      'XR Clear Image dynamically reconstructs textures for spotless 4K upscaling',
      'Seamless multi-position stand adjusts to fit soundbars underneath without blocking view',
    ],
    dimensions: '1223 x 706 x 37 mm (without stand)',
    weight: '16.8 kg',
    warranty: '2-Year Comprehensive Sony India Warranty',
    shippingInfo: 'Dedicated transit with on-site technician installation.',
    image: 'https://images.unsplash.com/photo-1526738549149-8e07eca6c147?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1526738549149-8e07eca6c147?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'dell-ultrasharp-32-4k-u3223qe',
    name: 'Dell UltraSharp 32 4K USB-C Hub Monitor (U3223QE)',
    brand: 'Dell',
    category: 'TVs & Monitors',
    sku: 'DEL-U3223QE-4K',
    price: 68999,
    originalPrice: 84999,
    stock: 16,
    rating: 4.8,
    reviewCount: 1420,
    tagline: 'IPS Black technology with 2000:1 contrast ratio. 90W USB-C hub with RJ45.',
    description: 'Premier 31.5-inch 4K productivity display with IPS Black panel technology, 98% DCI-P3 color gamut, ComfortView Plus, and built-in KVM switch with single cable docking.',
    fullDescription: 'The Dell UltraSharp U3223QE is the definitive desk monitor for software developers and content editors. IPS Black doubles the contrast ratio of traditional IPS screens to 2000:1, rendering deep blacks and crisp text.',
    featured: false,
    newArrival: false,
    tag: 'Productivity Benchmark',
    specifications: {
      'Screen Size': '31.5-inch 16:9 anti-glare IPS Black',
      'Resolution': '4K UHD (3840 x 2160 @ 60Hz)',
      'Contrast Ratio': '2000:1 (typical IPS Black contrast)',
      'Color Gamut': '100% sRGB, 100% Rec.709, 98% DCI-P3 with Delta E < 2',
      'Docking Hub': 'USB-C with 90W Power Delivery, RJ45 Ethernet, 5x USB-A 10Gbps, DisplayPort out',
    },
    features: [
      'IPS Black delivers 35% deeper blacks than conventional IPS screens',
      'Built-in KVM switch and Auto KVM lets you control 2 connected PCs with one keyboard/mouse',
      'Daisy chain support lets you run dual 4K monitors over a single DisplayPort MST cable',
    ],
    dimensions: '712.6 x 469.3 ~ 619.3 x 233.2 mm (with stand)',
    weight: '10.36 kg (with stand)',
    warranty: '3-Year Dell Advanced Exchange Service and Premium Panel Guarantee',
    shippingInfo: 'Express courier delivery with heavy duty box packaging.',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'asus-rog-swift-oled-pg27aqdm',
    name: 'ASUS ROG Swift OLED PG27AQDM 27-inch 240Hz 0.03ms Gaming Monitor',
    brand: 'ASUS',
    category: 'TVs & Monitors',
    sku: 'ASU-PG27AQDM-OLED',
    price: 89990,
    originalPrice: 109990,
    stock: 8,
    rating: 4.9,
    reviewCount: 970,
    tagline: 'QHD 240Hz OLED. 0.03ms response time. Custom heatsink & intelligent voltage.',
    description: 'Esports tournament monitor featuring 26.5-inch QHD OLED panel, blistering 240Hz refresh, 0.03ms gray-to-gray response, custom internal heatsink, and anti-glare micro-texture coating.',
    fullDescription: 'The ROG Swift PG27AQDM eliminates ghosting completely. Features intelligent voltage optimization to reduce burn-in risk, 1000 nits peak brightness, and 99% DCI-P3 color gamut.',
    featured: true,
    newArrival: false,
    tag: 'Esports Legend',
    specifications: {
      'Screen Size': '26.5 inches (QHD 2560 x 1440)',
      'Panel Type': 'OLED with anti-glare micro-texture coating',
      'Refresh Rate & Response': '240Hz with near-instantaneous 0.03ms (GTG)',
      'Peak Brightness': '1000 nits (3% window HDR), 450 nits (100% APL)',
      'Thermal System': 'Custom heatsink with airflow channel design for passive cooling',
    },
    features: [
      '0.03ms response time virtually eliminates motion blur and inverse ghosting',
      'Uniform Brightness setting locks lumen levels for comfortable desktop spreadsheet work',
      '2-Year ASUS warranty including burn-in panel protection',
    ],
    dimensions: '605 x 438 ~ 548 x 274 mm',
    weight: '6.9 kg (with stand)',
    warranty: '2-Year ASUS Warranty with OLED Burn-in Coverage',
    shippingInfo: 'Padded courier dispatch with fragile handling label.',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'samsung-odyssey-oled-g9-49-inch',
    name: 'Samsung Odyssey OLED G9 49-inch Curved Gaming Monitor (G95SC)',
    brand: 'Samsung',
    category: 'TVs & Monitors',
    sku: 'SAM-ODYSG9-49-OLED',
    price: 139999,
    originalPrice: 179999,
    stock: 5,
    rating: 4.8,
    reviewCount: 630,
    tagline: '49-inch Dual QHD 32:9 curved OLED. 240Hz 0.03ms. Neo Quantum Processor Pro.',
    description: 'Immersive super ultra-wide 49-inch 1800R curved monitor. Equivalent to dual 27-inch 1440p displays side-by-side with 240Hz refresh, CoreSync rear lighting, and Neo Quantum Processor Pro.',
    fullDescription: 'Samsung Odyssey OLED G9 surrounds your peripheral vision. Built with an elegant 4.5mm slim metal frame, Smart TV platform with built-in streaming apps, and DisplayPort 1.4 + HDMI 2.1.',
    featured: true,
    newArrival: false,
    tag: 'Ultra-Wide Apex',
    specifications: {
      'Screen Size': '49 inches Dual QHD (5120 x 1440, 32:9 Super Ultra-Wide)',
      'Curvature': '1800R curved radius',
      'Panel': 'OLED with Quantum Dot layer',
      'Refresh Rate & Response': '240Hz refresh rate with 0.03ms (GTG) response',
      'Speakers': '5W x 2 stereo speakers with CoreSync RGB ambient lighting',
    },
    features: [
      'Massive 32:9 aspect ratio eliminates bezel seams between dual monitor setups',
      'CoreSync & Core Lighting+ projects on-screen game colors onto wall behind display',
      'Auto Source Switch+ detects when connected gaming consoles power on',
    ],
    dimensions: '1194.7 x 529.3 x 284.1 mm (with stand)',
    weight: '12.9 kg',
    warranty: '3-Year Samsung Comprehensive Warranty',
    shippingInfo: 'Palletized insured freight delivery with white glove assembly.',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'benq-designvue-pd3205u-4k',
    name: 'BenQ DesignVue PD3205U 31.5-inch 4K sRGB/Rec.709 Designer Monitor',
    brand: 'BenQ',
    category: 'TVs & Monitors',
    sku: 'BNQ-PD3205U-32-4K',
    price: 54990,
    originalPrice: 69990,
    stock: 14,
    rating: 4.7,
    reviewCount: 710,
    tagline: 'AQCOLOR technology with 99% sRGB. Calman & Pantone validated. Hotkey Puck G2.',
    description: 'Color-critical designer display featuring 31.5-inch 4K IPS panel, factory calibration report with Delta E <= 3, 90W USB-C connectivity, DualView mode, and Hotkey Puck controller.',
    fullDescription: 'BenQ PD3205U is designed specifically for graphic artists, UI/UX designers, and CAD draftsmen. Includes Darkroom and CAD/CAM modes, KVM switch, and uniform brightness across all screen zones.',
    featured: false,
    newArrival: false,
    tag: 'Designer Calibrated',
    specifications: {
      'Screen Size': '31.5 inches (3840 x 2160 4K UHD, 16:9)',
      'Color Standards': '99% sRGB and 99% Rec.709 with Calman and Pantone SkinTone Validation',
      'Factory Calibration': 'Delta E <= 3 individual factory report included',
      'Controller': 'Hotkey Puck G2 dial for rapid brightness and color space toggling',
      'USB-C Power': '90W Power Delivery with video and audio transfer',
    },
    features: [
      'DualView displays design artwork simultaneously in sRGB and CAD/CAM modes side-by-side',
      'BenQ Uniformity Technology balances brightness and chromaticity across hundreds of regions',
      'Hotkey Puck G2 physical dial lets you customize shortcuts and switch inputs instantly',
    ],
    dimensions: '714.7 x 487.4 ~ 597.4 x 256.8 mm',
    weight: '9.4 kg (with stand)',
    warranty: '3-Year BenQ India Onsite Warranty',
    shippingInfo: 'Insured parcel transit with factory packaging.',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'acer-nitro-vg270-s3-180hz',
    name: 'Acer Nitro VG270 S3 27-inch 180Hz 0.5ms IPS Gaming Monitor',
    brand: 'Acer',
    category: 'TVs & Monitors',
    sku: 'ACR-VG270S3-180',
    price: 12499,
    originalPrice: 14999,
    stock: 38,
    rating: 4.5,
    reviewCount: 4620,
    tagline: 'FHD IPS 180Hz refresh. 0.5ms response time. AMD FreeSync Premium.',
    description: 'High-speed budget esports gaming monitor featuring 27-inch Full HD Fast IPS panel, 180Hz refresh rate, 0.5ms response time, dual HDMI 2.0 ports, DisplayPort 1.2, and integrated stereo speakers.',
    fullDescription: 'The Acer Nitro VG270 S3 delivers fluid high-framerate competitive gaming at an accessible price point. Features ZeroFrame bezels for multi-monitor setups and AMD FreeSync Premium tear-free gaming.',
    featured: false,
    newArrival: false,
    tag: 'Budget Esports',
    specifications: {
      'Screen Size': '27.0-inch Full HD (1920 x 1080 @ 180Hz)',
      'Panel': 'Fast IPS with 99% sRGB wide color gamut',
      'Response Time': 'Up to 0.5ms (Min. GTG)',
      'Adaptive Sync': 'AMD FreeSync Premium certified',
      'Audio': 'Integrated 2W x 2 stereo speakers',
    },
    features: [
      '180Hz refresh rate delivers 3x smoother animation frames than standard 60Hz screens',
      'Acer VisionCare includes BlueLightShield and Flickerless technology for long gaming sessions',
      'ZeroFrame ultra-slim bezel design creates nearly seamless multi-monitor arrays',
    ],
    dimensions: '614 x 457 x 240 mm (with stand)',
    weight: '4.5 kg',
    warranty: '3-Year Acer Onsite Domestic Warranty',
    shippingInfo: 'Fast 1-2 business day dispatch across India.',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    ],
  },
];
