export const GAMING = [
  {
    id: 'sony-playstation-5-slim-disc',
    name: 'Sony PlayStation 5 Slim Console (1TB SSD, Disc Edition)',
    brand: 'PlayStation',
    category: 'Gaming',
    sku: 'SNY-PS5-SLM-DSC',
    price: 54990,
    originalPrice: 54990,
    stock: 16,
    rating: 4.9,
    reviewCount: 6410,
    tagline: 'Play Has No Limits. 1TB SSD. Ultra-HD Blu-ray disc drive. Ray tracing.',
    description: 'The world most sought-after gaming console. Features 30% smaller chassis, 1TB high-speed NVMe storage, custom AMD Zen 2 CPU / RDNA 2 GPU, Tempest 3D AudioTech, and DualSense haptic feedback controller.',
    fullDescription: 'PlayStation 5 Slim delivers cinematic 4K 120fps gaming with hardware-accelerated ray tracing. DualSense wireless controller immerses you with dynamic adaptive triggers, integrated microphone, and realistic surface haptics.',
    featured: true,
    newArrival: false,
    tag: 'Bestseller Console',
    specifications: {
      'Storage': '1TB Custom High-Speed NVMe SSD (5.5GB/s raw read bandwidth)',
      'Processor': 'Custom 8-core AMD Zen 2 CPU up to 3.5 GHz',
      'Graphics': 'Custom AMD RDNA 2 GPU engine with 36 CUs up to 2.23 GHz (10.3 TFLOPS)',
      'Optical Drive': 'Ultra HD Blu-ray Disc Drive (detachable drive cover mechanism)',
      'Video Output': 'HDMI 2.1 supporting 4K 120Hz, 8K TVs, and Variable Refresh Rate (VRR)',
      'Audio': 'Tempest 3D AudioTech custom sound DSP',
    },
    features: [
      'DualSense wireless controller with adaptive triggers and haptic feedback',
      'Ultra-high-speed SSD nearly eliminates loading screens in supported PS5 titles',
      'Backwards compatible with over 4,000 PlayStation 4 titles with Game Boost',
    ],
    dimensions: '358 x 96 x 216 mm',
    weight: '3.2 kg',
    warranty: '1-Year Sony India Official Warranty',
    shippingInfo: 'Express courier delivery with serial tamper protection.',
    image: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1592840496073-e53bb895e791?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'sony-playstation-portal',
    name: 'Sony PlayStation Portal Remote Player for PS5',
    brand: 'PlayStation',
    category: 'Gaming',
    sku: 'SNY-PS-PORTAL',
    price: 18990,
    originalPrice: 18990,
    stock: 21,
    rating: 4.6,
    reviewCount: 1480,
    tagline: '8-inch 1080p 60fps LCD screen with DualSense controller grips.',
    description: 'Dedicated PS5 remote play handheld with vibrant 8-inch Full HD screen, full DualSense adaptive trigger and haptic feedback integration, and Wi-Fi streaming.',
    fullDescription: 'Play your installed PS5 games without tying up the living room television. PlayStation Portal connects over your home broadband Wi-Fi directly to your PS5 console, delivering crisp 1080p 60fps gameplay.',
    featured: false,
    newArrival: true,
    tag: 'PS5 Handheld',
    specifications: {
      'Display': '8.0-inch Full HD LCD touchscreen (1920 x 1080 @ 60fps)',
      'Controls': 'Full DualSense wireless controller layout with haptic feedback & adaptive triggers',
      'Connectivity': 'Wi-Fi 5 (802.11ac), 3.5mm audio jack, PlayStation Link lossless audio',
      'Battery': 'Rechargeable lithium-ion (approx 4-6 hours active streaming runtime)',
    },
    features: [
      'DualSense haptic feedback and dynamic resistance triggers in handheld format',
      'PlayStation Link provides ultra-low latency lossless audio with Pulse Elite headsets',
      'Instantly jump into your PS5 library over Wi-Fi without needing a television',
    ],
    dimensions: '305 x 125 x 67 mm',
    weight: '529 grams',
    warranty: '1-Year Sony India Warranty',
    shippingInfo: 'Fast dispatch within 24 hours of order authorization.',
    image: 'https://images.unsplash.com/photo-1592840496073-e53bb895e791?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1592840496073-e53bb895e791?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'microsoft-xbox-series-x',
    name: 'Microsoft Xbox Series X 1TB Console (Black)',
    brand: 'Xbox',
    category: 'Gaming',
    sku: 'MSF-XBSX-1TB-BLK',
    price: 55990,
    originalPrice: 55990,
    stock: 12,
    rating: 4.8,
    reviewCount: 3190,
    tagline: '12 TFLOPS raw processing power. True 4K gaming. Quick Resume.',
    description: 'Microsoft most powerful gaming console. Powered by Xbox Velocity Architecture, 12 teraflops GPU, hardware ray tracing, 4K UHD Blu-ray drive, and Quick Resume across multiple titles.',
    fullDescription: 'Xbox Series X delivers 4K gaming at up to 120 frames per second. Features Quick Resume allowing you to suspend and jump between several active games in seconds without loading.',
    featured: false,
    newArrival: false,
    tag: '12 TFLOPS Power',
    specifications: {
      'Processor': 'Custom 8-core AMD Zen 2 CPU @ 3.8 GHz',
      'Graphics': 'Custom AMD RDNA 2 GPU with 52 CUs @ 1.825 GHz (12.15 TFLOPS)',
      'Memory': '16GB GDDR6 with 320-bit wide bus',
      'Storage': '1TB Custom NVMe SSD (expandable via Seagate Storage Expansion Card)',
      'Optical Drive': '4K UHD Blu-ray drive',
    },
    features: [
      'Quick Resume lets you switch between 4+ game titles seamlessly in under 5 seconds',
      'Xbox Velocity Architecture ensures blistering asset streaming and instantaneous world loading',
      'Dolby Vision and Dolby Atmos audio support for immersive gaming aesthetics',
    ],
    dimensions: '151 x 151 x 301 mm',
    weight: '4.45 kg',
    warranty: '1-Year Microsoft India Domestic Warranty',
    shippingInfo: 'Insured transit in reinforced courier packaging.',
    image: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'nintendo-switch-oled-model',
    name: 'Nintendo Switch OLED Model (Neon Blue & Neon Red)',
    brand: 'Nintendo',
    category: 'Gaming',
    sku: 'NTD-SW-OLED-NEO',
    price: 31999,
    originalPrice: 34999,
    stock: 24,
    rating: 4.8,
    reviewCount: 5210,
    tagline: '7-inch OLED screen with vivid colors and crisp contrast. Enhanced audio.',
    description: 'Hybrid gaming console featuring vibrant 7-inch OLED screen, wide adjustable tabletop stand, dock with wired LAN port, 64GB internal storage, and Joy-Con motion controllers.',
    fullDescription: 'Nintendo Switch OLED Model allows playing anywhere, anytime, with anyone. Enjoy iconic franchises like The Legend of Zelda, Super Mario, and Pokémon in handheld, tabletop, or docked TV modes.',
    featured: false,
    newArrival: false,
    tag: 'Family Favorite',
    specifications: {
      'Display': '7.0-inch OLED multi-touch screen (1280 x 720 handheld, 1080p docked)',
      'Storage': '64GB internal flash memory (expandable up to 2TB via MicroSD)',
      'Speakers': 'Enhanced onboard stereo speakers for tabletop audio',
      'Dock': 'Includes wired LAN Ethernet port + HDMI output',
      'Battery Life': 'Approximately 4.5 to 9 hours depending on title',
    },
    features: [
      'Vivid 7-inch OLED screen provides intense deep blacks and saturated color rendition',
      'Wide adjustable kickstand allows optimal viewing angle adjustments for tabletop gaming',
      'Detachable Joy-Con controllers enable instant 2-player local multiplayer anywhere',
    ],
    dimensions: '102 x 242 x 13.9 mm (with Joy-Con attached)',
    weight: '420 grams (with Joy-Con controllers)',
    warranty: '1-Year Importer Warranty with Service Support',
    shippingInfo: 'Standard 2-3 business day courier delivery.',
    image: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'asus-rog-ally-x-handheld',
    name: 'ASUS ROG Ally X Handheld Gaming PC (AMD Z1 Extreme / 24GB / 1TB / 80Wh)',
    brand: 'ASUS',
    category: 'Gaming',
    sku: 'ASU-ALLYX-Z1E-1TB',
    price: 89990,
    originalPrice: 89990,
    stock: 9,
    rating: 4.8,
    reviewCount: 840,
    tagline: 'Massive 80Wh battery. 24GB LPDDR5X-7500 RAM. 1TB M.2 2280 NVMe SSD.',
    description: 'Upgraded Windows 11 handheld gaming PC with double the battery capacity (80Wh), dual USB-C ports with USB4 40Gbps, ergonomic grips, redesigned Hall effect joysticks, and AMD Ryzen Z1 Extreme.',
    fullDescription: 'The ROG Ally X fixes every flaw of handheld gaming PCs. Packing an enormous 80Wh battery, 24GB high-speed RAM, standard M.2 2280 NVMe expansion slot, and fluid 1080p 120Hz FreeSync Premium touchscreen.',
    featured: true,
    newArrival: true,
    tag: 'Handheld Apex',
    specifications: {
      'Processor': 'AMD Ryzen Z1 Extreme (8 cores, 16 threads, 24MB cache, up to 5.10 GHz)',
      'Graphics': 'AMD Radeon Graphics (RDNA 3, 12 CUs, up to 2.7 GHz, 8.6 TFlops)',
      'RAM': '24GB LPDDR5X-7500 dual-channel onboard',
      'Storage': '1TB PCIe 4.0 NVMe M.2 2280 SSD',
      'Display': '7-inch FHD IPS (1920 x 1080, 120Hz, 7ms, 500 nits, FreeSync Premium)',
      'Battery': '80Wh 4-cell Li-ion with 65W fast charger',
    },
    features: [
      'Massive 80Wh battery doubles the runtime of competing handheld gaming PCs',
      'Standard M.2 2280 form factor allows easy aftermarket SSD capacity upgrades',
      'Dual USB-C ports include full Thunderbolt 4 / USB4 40Gbps external GPU support',
    ],
    dimensions: '280 x 111 x 24.7 ~ 36.9 mm',
    weight: '678 grams',
    warranty: '1-Year ASUS India Warranty',
    shippingInfo: 'High-value insured dispatch with secure courier transit.',
    image: 'https://images.unsplash.com/photo-1592840496073-e53bb895e791?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1592840496073-e53bb895e791?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'razer-huntsman-v3-pro',
    name: 'Razer Huntsman V3 Pro Analog Optical Gaming Keyboard',
    brand: 'Razer',
    category: 'Gaming',
    sku: 'RZR-HUNT3P-OPT',
    price: 24999,
    originalPrice: 27999,
    stock: 15,
    rating: 4.8,
    reviewCount: 920,
    tagline: 'Gen-2 Analog Optical Switches. Rapid Trigger mode. 0.1 to 4.0mm adjustable actuation.',
    description: 'Esports flagship mechanical keyboard with Gen-2 Analog Optical switches, Rapid Trigger for instantaneous key resets, onboard LED array indicator, multi-function digital dial, and magnetic wrist rest.',
    fullDescription: 'The Razer Huntsman V3 Pro gives competitive gamers pinpoint control. Rapid Trigger mode resets keys the fraction of a millimeter they move upwards, enabling blistering counter-strafing in games like Valorant and CS2.',
    featured: false,
    newArrival: false,
    tag: 'Esports Keyboard',
    specifications: {
      'Switch Type': 'Razer Gen-2 Analog Optical Switches with 100-million keystroke lifespan',
      'Actuation Range': '0.1 mm to 4.0 mm fully adjustable per-key actuation points',
      'Rapid Trigger': 'Adjustable sensitivity between 0.1mm and 2.0mm',
      'Keycaps': 'Textured double-shot PBT keycaps with side-printed secondary functions',
      'Chassis': 'Brushed 5052 aluminum top plate with acoustic dampening foam',
    },
    features: [
      'Rapid Trigger technology permits repeated keypresses at inhuman speeds',
      '10-LED onboard array display allows real-time actuation adjustment without software',
      'Firm leatherette magnetic wrist rest supports ergonomic marathon tournament play',
    ],
    dimensions: '445 x 139 x 39 mm',
    weight: '1.13 kg (with wrist rest)',
    warranty: '2-Year Razer India Warranty',
    shippingInfo: 'Fast dispatch within 24 hours of order receipt.',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'razer-deathadder-v3-pro',
    name: 'Razer DeathAdder V3 Pro Wireless Esports Gaming Mouse (Black)',
    brand: 'Razer',
    category: 'Gaming',
    sku: 'RZR-DAV3P-BLK',
    price: 13999,
    originalPrice: 16999,
    stock: 22,
    rating: 4.8,
    reviewCount: 3140,
    tagline: '63g ultra-lightweight ergonomic shape. Focus Pro 30K Optical Sensor.',
    description: 'Iconic ergonomic gaming mouse refined with world top esports pros. Weighs just 63 grams, Razer Focus Pro 30K optical sensor, Gen-3 optical switches, and 90-hour battery life.',
    fullDescription: 'The Razer DeathAdder V3 Pro represents an ergonomic evolution. With zero deadweight honeycomb holes, 90 hours of uninterrupted wireless gaming, and flawless tracking on transparent glass mousepads.',
    featured: false,
    newArrival: false,
    tag: 'Esports Mouse',
    specifications: {
      'Sensor': 'Focus Pro 30K Optical Sensor (30,000 DPI, 750 IPS, 70G acceleration)',
      'Switches': 'Optical Mouse Switches Gen-3 rated for 90 million clicks with zero debounce delay',
      'Weight': '63 grams ultra-lightweight solid unibody chassis',
      'Battery': 'Up to 90 hours continuous motion at 1000Hz polling rate',
      'Connectivity': 'Razer HyperSpeed Wireless 2.4GHz + USB Type-C wired',
    },
    features: [
      'Refined ergonomic silhouette developed alongside Tier-1 professional Counter-Strike athletes',
      'Asymmetric Cut-off allows independent lift-off and landing distance calibration',
      '100% PTFE mouse feet with rounded edges for smooth glides across cloth and cordura pads',
    ],
    dimensions: '128.0 x 68.0 x 44.0 mm',
    weight: '63 grams',
    warranty: '2-Year Razer Brand Warranty',
    shippingInfo: 'Fast courier dispatch in protective box packaging.',
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'logitech-g-pro-x-superlight-2',
    name: 'Logitech G PRO X Superlight 2 Wireless Gaming Mouse (Magenta)',
    brand: 'Logitech',
    category: 'Gaming',
    sku: 'LOG-GPXS2-MGN',
    price: 14995,
    originalPrice: 16995,
    stock: 19,
    rating: 4.9,
    reviewCount: 3890,
    tagline: '60g featherweight. LIGHTFORCE hybrid optical-mechanical switches. HERO 2 sensor.',
    description: 'The weapon of choice for world champion esports pros. Features LIGHTFORCE hybrid switches combining optical speed with mechanical click feel, 32,000 DPI HERO 2 sensor, and 95-hour battery life.',
    fullDescription: 'Logitech G PRO X Superlight 2 delivers sub-micron accuracy. 4000Hz wireless polling rate capability, zero-additive PTFE glide feet, USB-C recharging, and POWERPLAY wireless charging compatibility.',
    featured: false,
    newArrival: true,
    tag: 'Champion Weapon',
    specifications: {
      'Sensor': 'HERO 2 Sensor (100 - 32,000 DPI, >500 IPS, >40G)',
      'Switches': 'LIGHTFORCE hybrid optical-mechanical switches',
      'Polling Rate': 'Up to 4000Hz report rate via LIGHTSPEED wireless update',
      'Weight': '60 grams featherlight symmetrical design',
      'Battery': 'Up to 95 hours of continuous motion',
    },
    features: [
      'LIGHTFORCE optical actuation eliminates debounce delay while maintaining crisp tactile click',
      'HERO 2 sensor tracks true 1-to-1 movement across cloth and hard surfaces without smoothing',
      'POWERPLAY compatible for continuous wireless charging while playing',
    ],
    dimensions: '125.0 x 63.5 x 40.0 mm',
    weight: '60 grams',
    warranty: '2-Year Logitech India Limited Hardware Warranty',
    shippingInfo: 'Standard 2-3 business day delivery.',
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'logitech-g915-lightspeed-wireless',
    name: 'Logitech G915 LIGHTSPEED Wireless RGB Mechanical Keyboard (GL Tactile)',
    brand: 'Logitech',
    category: 'Gaming',
    sku: 'LOG-G915-TAC-BLK',
    price: 21995,
    originalPrice: 24995,
    stock: 11,
    rating: 4.7,
    reviewCount: 2140,
    tagline: 'Ultra-thin 22mm aircraft aluminum frame. Low-profile GL mechanical switches.',
    description: 'Premium wireless mechanical gaming keyboard with pro-grade 1ms LIGHTSPEED wireless, aircraft-grade 5052 aluminum alloy chassis, dedicated media keys, and 30-hour battery life.',
    fullDescription: 'The Logitech G915 is a breakthrough in mechanical keyboard engineering. Featuring half-height low profile GL Tactile switches for rapid actuation and reduced wrist fatigue during all-day gaming and typing.',
    featured: false,
    newArrival: false,
    tag: 'Low Profile Luxury',
    specifications: {
      'Switch Type': 'Logitech Low Profile GL Tactile (1.5mm actuation, 50g force)',
      'Wireless Tech': 'LIGHTSPEED 1ms wireless + Bluetooth 5.0 multi-host connection',
      'Chassis': 'Aircraft-grade 5052 aluminum-magnesium top plate',
      'Battery Life': '30 hours continuous play at 100% RGB brightness (up to 135 days without RGB)',
      'Controls': 'Dedicated cast volume roller wheel and rubberized media keys',
    },
    features: [
      'Incredibly slim 22mm height provides ergonomic comfort without requiring a wrist rest',
      'LIGHTSYNC RGB provides per-key illumination customizable across 16.8 million colors',
      'Dual connectivity switches instantly between LIGHTSPEED gaming PC and Bluetooth laptop',
    ],
    dimensions: '475 x 150 x 22 mm',
    weight: '1025 grams',
    warranty: '2-Year Logitech Warranty',
    shippingInfo: 'Fast dispatch with tamper-proof delivery box.',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'steelseries-arctis-nova-pro-wireless',
    name: 'SteelSeries Arctis Nova Pro Wireless Multi-System Gaming Headset',
    brand: 'SteelSeries',
    category: 'Gaming',
    sku: 'STL-ARCNV-PRO-WLS',
    price: 34999,
    originalPrice: 39999,
    stock: 10,
    rating: 4.8,
    reviewCount: 1680,
    tagline: 'Nova Pro Acoustic System. Active Noise Cancellation. Infinity Power hot-swap batteries.',
    description: 'Ultimate multi-system gaming headset with premium High Fidelity neodymium drivers, 4-mic hybrid active noise cancellation, dual hot-swappable batteries for infinite play, and wireless base station.',
    fullDescription: 'SteelSeries Arctis Nova Pro Wireless delivers legendary acoustic immersion. The desktop OLED Wireless Base Station lets you adjust EQ profiles and switch between PC, PlayStation, and Nintendo Switch with a single button press.',
    featured: false,
    newArrival: false,
    tag: 'Infinity Battery',
    specifications: {
      'Audio Drivers': 'Custom High Fidelity 40mm Neodymium drivers (10 - 40,000 Hz)',
      'Noise Cancellation': '4-mic hybrid Active Noise Cancellation with Transparency Mode',
      'Battery System': 'Infinity Power System includes 2 hot-swappable batteries (22 hours each)',
      'Base Station': 'Dual USB-C ports with multi-system switching and OLED control display',
      'Microphone': 'ClearCast Gen 2 fully retractable noise-cancelling bidirectional mic',
    },
    features: [
      'Infinity Power System: charge battery B in base station while playing on battery A',
      'Multi-System Connect lets you toggle between PC and console without swapping cables',
      'Simultaneous 2.4GHz gaming audio and Bluetooth mobile phone connectivity',
    ],
    dimensions: '190 x 185 x 85 mm',
    weight: '337 grams',
    warranty: '2-Year SteelSeries Manufacturer Warranty',
    shippingInfo: 'Secure courier dispatch with protective bubble wrap.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    ],
  },
];
