export const LAPTOPS = [
  {
    id: 'apple-macbook-pro-16-m3-max',
    name: 'Apple MacBook Pro 16-inch M3 Max 36GB / 1TB SSD (Space Black)',
    brand: 'Apple',
    category: 'Laptops',
    sku: 'APL-MBP16-M3M-1TB',
    price: 349900,
    originalPrice: 369900,
    stock: 8,
    rating: 4.9,
    reviewCount: 1120,
    tagline: 'Apple M3 Max 16-core CPU. 40-core GPU. Liquid Retina XDR display.',
    description: 'Pro workstation laptop featuring M3 Max silicon, 16.2-inch Liquid Retina XDR screen with 1600 nits peak brightness, hardware-accelerated ray tracing, and up to 22 hours battery life.',
    fullDescription: 'The 16-inch MacBook Pro with M3 Max is engineered for extreme workflows like 3D animation, code compilation, and multitrack 8K ProRes editing. Featuring Space Black anodization that dramatically reduces fingerprints, six-speaker sound system with force-cancelling woofers, and MagSafe 3 charging.',
    featured: true,
    newArrival: false,
    tag: 'Pro Workstation',
    specifications: {
      'Display': '16.2-inch Liquid Retina XDR (3456 x 2234, 120Hz ProMotion, 1600 nits peak)',
      'Processor': 'Apple M3 Max (16-core CPU, 40-core GPU, 16-core Neural Engine)',
      'Memory': '36GB Unified Memory (300GB/s bandwidth)',
      'Storage': '1TB NVMe PCIe 4.0 SSD',
      'Battery': '100Wh lithium-polymer with 140W USB-C MagSafe 3 Fast Charging',
      'Ports': '3x Thunderbolt 4 / USB4, HDMI 2.1, SDXC card slot, 3.5mm headphone jack',
      'OS': 'macOS Sonoma',
    },
    features: [
      'Space Black finish with breakthrough chemistry preventing finger smudges',
      'Hardware-accelerated mesh shading and ray tracing on Apple Silicon',
      'Six-speaker sound system with studio-quality wide stereo soundstage',
    ],
    dimensions: '355.7 x 248.1 x 16.8 mm',
    weight: '2.16 kg',
    warranty: '1-Year Apple India Warranty + 90 days complimentary tech support',
    shippingInfo: 'Complimentary courier delivery with high-value insurance.',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'apple-macbook-air-15-m3',
    name: 'Apple MacBook Air 15-inch M3 16GB / 512GB SSD (Midnight)',
    brand: 'Apple',
    category: 'Laptops',
    sku: 'APL-MBA15-M3-512',
    price: 154900,
    originalPrice: 164900,
    stock: 19,
    rating: 4.8,
    reviewCount: 2240,
    tagline: 'Impossibly thin 11.5mm unibody. 15.3-inch Liquid Retina. M3 speed.',
    description: 'Ultra-portable 15.3-inch laptop weighing just 1.51 kg. Powered by Apple M3 chip with support for up to two external displays, 18-hour battery, and silent fanless operation.',
    fullDescription: 'MacBook Air 15-inch gives you more room for what you love with its expansive Liquid Retina display. Features 1080p FaceTime HD camera, dual-mic array, spatial audio with Dolby Atmos, and MagSafe magnetic power delivery.',
    featured: false,
    newArrival: true,
    tag: 'Ultralight',
    specifications: {
      'Display': '15.3-inch Liquid Retina Display (2880 x 1864, 500 nits, P3 Wide Color)',
      'Processor': 'Apple M3 (8-core CPU, 10-core GPU, 16-core Neural Engine)',
      'Memory': '16GB Unified Memory',
      'Storage': '512GB SSD',
      'Battery': '66.5Wh with 35W Dual USB-C Port Compact Power Adapter',
      'Ports': '2x Thunderbolt / USB 4, MagSafe 3, 3.5mm headphone jack',
      'OS': 'macOS Sonoma',
    },
    features: [
      'Whisper-quiet fanless passive thermal architecture',
      'Supports dual external displays with laptop lid closed',
      'Four-speaker sound system with Spatial Audio support',
    ],
    dimensions: '340.4 x 237.6 x 11.5 mm',
    weight: '1.51 kg',
    warranty: '1-Year Official Apple Warranty',
    shippingInfo: 'Direct priority dispatch within 24 hours of order receipt.',
    image: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'apple-macbook-air-13-m3',
    name: 'Apple MacBook Air 13-inch M3 16GB / 256GB SSD (Starlight)',
    brand: 'Apple',
    category: 'Laptops',
    sku: 'APL-MBA13-M3-256',
    price: 114900,
    originalPrice: 124900,
    stock: 26,
    rating: 4.8,
    reviewCount: 3410,
    tagline: 'World most popular laptop. Now supercharged by M3 chip.',
    description: '13.6-inch Liquid Retina display, durable recycled aluminum body, all-day 18-hour battery, MagSafe charging, and seamless Apple ecosystem continuity.',
    fullDescription: 'The 13-inch MacBook Air is the benchmark everyday ultrabook. Whether writing code, editing 4K home video, or streaming lectures, M3 powers through demanding apps with ease while staying totally silent.',
    featured: false,
    newArrival: false,
    tag: 'Bestseller',
    specifications: {
      'Display': '13.6-inch Liquid Retina Display (2560 x 1664, 500 nits, True Tone)',
      'Processor': 'Apple M3 (8-core CPU, 8-core GPU)',
      'Memory': '16GB Unified Memory',
      'Storage': '256GB SSD',
      'Battery': '52.6Wh lithium-polymer with up to 18 hours Apple TV app movie playback',
      'Ports': '2x Thunderbolt / USB 4, MagSafe 3, 3.5mm jack',
      'OS': 'macOS Sonoma',
    },
    features: [
      '11.3 mm thin aluminum unibody weighing 1.24 kg',
      '1080p FaceTime HD camera with computational video enhancement',
      'Wi-Fi 6E with 2x faster throughput than prior generation',
    ],
    dimensions: '304.1 x 215.0 x 11.3 mm',
    weight: '1.24 kg',
    warranty: '1-Year Apple Warranty',
    shippingInfo: 'Express pan-India delivery within 2-3 business days.',
    image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'dell-xps-16-9640',
    name: 'Dell XPS 16 9640 (Intel Core Ultra 7 / 32GB / 1TB / RTX 4070)',
    brand: 'Dell',
    category: 'Laptops',
    sku: 'DEL-XPS16-U7-4070',
    price: 279990,
    originalPrice: 299990,
    stock: 7,
    rating: 4.7,
    reviewCount: 480,
    tagline: '4K OLED InfinityEdge touch. CNC aluminum. Dedicated AI NPU.',
    description: 'Flagship creator laptop featuring 16.3-inch 4K+ OLED touch screen, Intel Core Ultra 7 155H, NVIDIA GeForce RTX 4070 8GB GDDR6, and seamless glass touchpad.',
    fullDescription: 'The Dell XPS 16 combines CNC machined aluminum, Gorilla Glass 3, and a zero-lattice keyboard with capacitive touch function row. Built for studio creatives and engineers running local generative AI models and intense rendering.',
    featured: true,
    newArrival: true,
    tag: 'Flagship Creator',
    specifications: {
      'Display': '16.3-inch 4K+ OLED (3840 x 2400, 90Hz, 400 nits, 100% DCI-P3 touch)',
      'Processor': 'Intel Core Ultra 7 155H (16 cores, up to 4.8 GHz with Intel AI Boost)',
      'Graphics': 'NVIDIA GeForce RTX 4070 Laptop GPU (8GB GDDR6, 60W)',
      'RAM': '32GB LPDDR5x 7467 MHz dual-channel',
      'Storage': '1TB PCIe Gen4 NVMe SSD',
      'Battery': '99.5Wh with 130W Type-C AC Adapter',
      'OS': 'Windows 11 Home',
    },
    features: [
      'Seamless glass haptic trackpad integrated into wrist rest',
      'Quad-speaker design with 10W total studio sound output',
      'Integrated Intel AI Boost NPU for local Copilot accelerations',
    ],
    dimensions: '358.18 x 240.05 x 18.70 mm',
    weight: '2.13 kg',
    warranty: '1-Year Dell Premium Support with Onsite Service',
    shippingInfo: 'Insured courier shipping with direct serial authentication.',
    image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'dell-xps-14-9440',
    name: 'Dell XPS 14 9440 (Intel Core Ultra 7 / 16GB / 1TB / RTX 4050)',
    brand: 'Dell',
    category: 'Laptops',
    sku: 'DEL-XPS14-U7-4050',
    price: 219990,
    originalPrice: 239990,
    stock: 12,
    rating: 4.6,
    reviewCount: 390,
    tagline: '3.2K OLED 120Hz InfinityEdge. Compact 14.5-inch powerhouse.',
    description: 'Precision engineered 14.5-inch laptop with 3.2K OLED touch display, Intel Core Ultra 7, discrete NVIDIA GeForce RTX 4050, and 69.5Wh battery.',
    fullDescription: 'Crafted from tone-on-tone CNC aluminum and Gorilla Glass 3, the XPS 14 balances high-octane graphic power and sleek mobility for professionals on the move.',
    featured: false,
    newArrival: true,
    tag: 'Studio Ultra',
    specifications: {
      'Display': '14.5-inch 3.2K OLED (3200 x 2000, 120Hz, 100% DCI-P3, Touch)',
      'Processor': 'Intel Core Ultra 7 155H (16 Cores, 22 Threads)',
      'Graphics': 'NVIDIA GeForce RTX 4050 Laptop GPU (6GB GDDR6)',
      'RAM': '16GB LPDDR5x 7467 MHz',
      'Storage': '1TB M.2 PCIe NVMe SSD',
      'Battery': '69.5Wh with 100W Type-C adapter',
      'OS': 'Windows 11 Home',
    },
    features: [
      'Zero-lattice keyboard with larger keycaps and 1.0mm travel',
      'Wi-Fi 7 (802.11be) with Bluetooth 5.4 wireless card',
      'ExpressCharge charges up to 80% battery within 60 minutes',
    ],
    dimensions: '320.0 x 216.0 x 18.0 mm',
    weight: '1.68 kg',
    warranty: '1-Year Dell Onsite Hardware Service Warranty',
    shippingInfo: 'Dispatched via premium express logistics.',
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'hp-spectre-x360-14',
    name: 'HP Spectre x360 14 2-in-1 (Intel Core Ultra 7 / 16GB / 1TB OLED)',
    brand: 'HP',
    category: 'Laptops',
    sku: 'HP-SPEC14-U7-OLED',
    price: 169990,
    originalPrice: 184990,
    stock: 14,
    rating: 4.7,
    reviewCount: 890,
    tagline: '360° convertible hinge. 2.8K IMAX Enhanced OLED. 9MP AI camera.',
    description: 'Versatile 2-in-1 laptop with 14-inch 2.8K 120Hz OLED touchscreen, 360-degree geared hinge, bundled rechargeable tilt pen, and Intel Core Ultra 7 processor.',
    fullDescription: 'The HP Spectre x360 14 defines executive convertible laptops. Gem-cut aluminum design, Poly Studio quad speakers, auto-framing 9MP webcam with physical privacy shutter, and all-day 13-hour battery.',
    featured: false,
    newArrival: false,
    tag: 'Convertible',
    specifications: {
      'Display': '14-inch 2.8K OLED (2880 x 1800, 48-120Hz, 500 nits HDR, Touch)',
      'Processor': 'Intel Core Ultra 7 155H with Intel Arc Graphics',
      'RAM': '16GB LPDDR5x 7467 MHz onboard',
      'Storage': '1TB PCIe Gen4 NVMe M.2 SSD',
      'Battery': '68Wh with 65W USB Type-C power adapter',
      'OS': 'Windows 11 Home with Microsoft Office Home & Student 2021',
    },
    features: [
      '9MP IR AI webcam with walk-away lock and auto-wake sensors',
      'Includes HP Rechargeable MPP2.0 Tilt Pen in box',
      'IMAX Enhanced certified display and Audio by Poly Studio',
    ],
    dimensions: '313.7 x 220.4 x 16.9 mm',
    weight: '1.44 kg',
    warranty: '1-Year HP India Onsite Warranty',
    shippingInfo: 'Secure delivery with fragile item inspection assurance.',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'hp-envy-16-creator',
    name: 'HP Envy 16 Creator (Intel Core i7-13700H / 32GB / 1TB / RTX 4060)',
    brand: 'HP',
    category: 'Laptops',
    sku: 'HP-ENVY16-I7-4060',
    price: 159990,
    originalPrice: 174990,
    stock: 16,
    rating: 4.5,
    reviewCount: 630,
    tagline: '16-inch WQXGA 120Hz display with dedicated NVIDIA Studio drivers.',
    description: 'High-performance creative workstation featuring 13th Gen Intel Core i7, NVIDIA GeForce RTX 4060 8GB, 16-inch 16:10 120Hz anti-glare display, and vapor chamber cooling.',
    fullDescription: 'Engineered for colorists, video editors, and 3D artists. HP Envy 16 offers factory color-calibrated display with Delta E < 2, Bang & Olufsen tuned quad speakers, and versatile Thunderbolt 4 ports.',
    featured: false,
    newArrival: false,
    tag: 'Studio Pick',
    specifications: {
      'Display': '16-inch WQXGA (2560 x 1600, 120Hz, 100% sRGB, 400 nits)',
      'Processor': 'Intel Core i7-13700H (14 Cores, up to 5.0 GHz Turbo)',
      'Graphics': 'NVIDIA GeForce RTX 4060 Laptop GPU (8GB GDDR6)',
      'RAM': '32GB DDR5 5200 MHz (2 x 16GB)',
      'Storage': '1TB PCIe Gen4 NVMe TLC M.2 SSD',
      'Battery': '83Wh with 200W Smart AC power adapter',
      'OS': 'Windows 11 Home',
    },
    features: [
      'NVIDIA Studio verified for accelerated Adobe and Blender rendering',
      'HP Dual Speakers custom-tuned by Bang & Olufsen experts',
      'Full-size island-style backlit keyboard with numeric keys',
    ],
    dimensions: '357.4 x 252.4 x 19.9 mm',
    weight: '2.34 kg',
    warranty: '1-Year HP Manufacturer Warranty',
    shippingInfo: 'Fast dispatch within 2 business days.',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'lenovo-thinkpad-x1-carbon-gen12',
    name: 'Lenovo ThinkPad X1 Carbon Gen 12 (Core Ultra 7 / 32GB / 1TB)',
    brand: 'Lenovo',
    category: 'Laptops',
    sku: 'LNV-X1C12-U7-1TB',
    price: 249990,
    originalPrice: 269990,
    stock: 11,
    rating: 4.8,
    reviewCount: 760,
    tagline: 'Ultralight carbon fiber business standard. Legendary TrackPoint keyboard.',
    description: 'The executive enterprise benchmark weighing under 1.1 kg. Features Intel Core Ultra 7 processor, 14-inch 2.8K OLED 120Hz display, MIL-SPEC 810H durability, and biometric security.',
    fullDescription: 'ThinkPad X1 Carbon Gen 12 integrates tactile markings on the keyboard for accessibility, Communications Bar with 8MP computer vision webcam, dual fan thermal management, and rapid charging up to 80% in 60 minutes.',
    featured: false,
    newArrival: true,
    tag: 'Enterprise Elite',
    specifications: {
      'Display': '14-inch 2.8K OLED (2880 x 1800, 120Hz, 400 nits, Anti-glare, Dolby Vision)',
      'Processor': 'Intel Core Ultra 7 155H with Intel Arc Graphics & NPU',
      'RAM': '32GB LPDDR5x 6400 MHz soldered',
      'Storage': '1TB SSD M.2 2280 PCIe 4.0x4 Performance NVMe Opal 2.0',
      'Battery': '57Wh with 65W USB-C Slim AC adapter',
      'OS': 'Windows 11 Pro 64-bit',
    },
    features: [
      'Iconic red TrackPoint with programmable Quick Menu double-tap',
      'MIL-STD-810H military grade tested across 12 categories',
      'Discrete Trusted Platform Module (dTPM 2.0) hardware encryption',
    ],
    dimensions: '312.8 x 214.75 x 14.96 mm',
    weight: '1.09 kg',
    warranty: '3-Year Lenovo Premier Support with Next Business Day Onsite',
    shippingInfo: 'White glove enterprise courier shipping.',
    image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'lenovo-legion-pro-7i-gen9',
    name: 'Lenovo Legion Pro 7i Gen 9 (Core i9-14900HX / 32GB / 1TB / RTX 4080)',
    brand: 'Lenovo',
    category: 'Laptops',
    sku: 'LNV-LEG7I-I9-4080',
    price: 269990,
    originalPrice: 289990,
    stock: 9,
    rating: 4.8,
    reviewCount: 920,
    tagline: 'Intel Core i9-14900HX + RTX 4080 175W. 16-inch 240Hz PureSight Gaming.',
    description: 'Competitive esports powerhouse with ColdFront Vapor cooling, 16-inch WQXGA 240Hz 500 nits screen, per-key RGB Legion TrueStrike keyboard, and Lenovo LA-2 AI tuning chip.',
    fullDescription: 'Legion Pro 7i dominates high-framerate competitive gaming. Pushing full 175W TGP to NVIDIA GeForce RTX 4080, backed by AI-optimized framerate engine and Nahimic 3D spatial audio.',
    featured: true,
    newArrival: false,
    tag: 'Esports Monster',
    specifications: {
      'Display': '16-inch WQXGA (2560 x 1600, 240Hz, 500 nits, 100% sRGB, G-SYNC)',
      'Processor': 'Intel Core i9-14900HX (24 cores, 32 threads, up to 5.8 GHz)',
      'Graphics': 'NVIDIA GeForce RTX 4080 Laptop GPU (12GB GDDR6, 175W Max TGP)',
      'RAM': '32GB DDR5 5600 MHz (2 x 16GB dual channel)',
      'Storage': '1TB M.2 PCIe Gen4 NVMe SSD (dual slot expandable)',
      'Battery': '99.9Wh with 330W Slim Tip power supply',
      'OS': 'Windows 11 Home',
    },
    features: [
      'Legion ColdFront Vapor chamber with massive 0.1mm fan blades',
      'Lenovo LA-2 AI Chip dynamically balances CPU/GPU power distribution',
      'Legion TrueStrike keyboard with 100% anti-ghosting & per-key RGB',
    ],
    dimensions: '363.4 x 262.15 x 21.95 mm',
    weight: '2.62 kg',
    warranty: '1-Year Lenovo Legion Ultimate Support with Onsite Assistance',
    shippingInfo: 'Secure, padded transit packaging with signature verification.',
    image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'asus-rog-zephyrus-g16-2024',
    name: 'ASUS ROG Zephyrus G16 (Core Ultra 9 / 32GB / 1TB / RTX 4080 OLED)',
    brand: 'ASUS',
    category: 'Laptops',
    sku: 'ASU-ZG16-U9-4080',
    price: 289990,
    originalPrice: 309990,
    stock: 6,
    rating: 4.9,
    reviewCount: 680,
    tagline: 'CNC unibody. ROG Nebula 2.5K 240Hz OLED. Slash Lighting lid.',
    description: 'Ultra-thin gaming masterpiece at just 1.49 cm thickness. Powered by Intel Core Ultra 9 185H, NVIDIA GeForce RTX 4080, ROG Nebula 240Hz 0.2ms OLED panel, and tri-fan cooling.',
    fullDescription: 'The 2024 Zephyrus G16 redefines portable gaming luxury. Precision-milled single aluminum block, customizable Slash Lighting LED array across the lid, 6-speaker acoustic setup, and sub-2 kg weight.',
    featured: true,
    newArrival: true,
    tag: 'Design Award',
    specifications: {
      'Display': '16-inch 2.5K OLED (2560 x 1600, 240Hz, 0.2ms, 500 nits, G-SYNC, 100% DCI-P3)',
      'Processor': 'Intel Core Ultra 9 185H (16 cores, up to 5.1 GHz with Intel AI Boost)',
      'Graphics': 'NVIDIA GeForce RTX 4080 Laptop GPU (12GB GDDR6, 115W TGP with Dynamic Boost)',
      'RAM': '32GB LPDDR5X 7467 MHz onboard',
      'Storage': '1TB PCIe 4.0 NVMe M.2 Performance SSD',
      'Battery': '90Wh with 240W AC Adapter & 100W Type-C charging support',
      'OS': 'Windows 11 Home',
    },
    features: [
      'ROG Intelligent Cooling with 2nd Gen Arc Flow Fans and Liquid Metal',
      'Slash Lighting customizable diagonal matrix LED on top cover',
      'ROG Nebula OLED display with DisplayHDR True Black 500',
    ],
    dimensions: '354.0 x 246.0 x 14.9 mm',
    weight: '1.85 kg',
    warranty: '1-Year ASUS India International Warranty',
    shippingInfo: 'Fast courier dispatch in customized tamper-proof packaging.',
    image: 'https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'asus-zenbook-14-oled',
    name: 'ASUS Zenbook 14 OLED (Intel Core Ultra 7 / 16GB / 1TB / Ponder Blue)',
    brand: 'ASUS',
    category: 'Laptops',
    sku: 'ASU-ZB14-U7-PBLU',
    price: 99990,
    originalPrice: 114990,
    stock: 22,
    rating: 4.7,
    reviewCount: 1670,
    tagline: '3K 120Hz ASUS Lumina OLED. 75Wh battery. 1.2 kg all-metal chassis.',
    description: 'Thin and light premium ultrabook with 14-inch 3K 120Hz OLED display, Intel Core Ultra 7 processor, 75Wh battery providing up to 15 hours runtime, and Harman Kardon speakers.',
    fullDescription: 'ASUS Zenbook 14 OLED packs incredible visual fidelity and battery longevity into a 14.9mm slim metal profile. Includes FHD IR camera for facial login, military-grade durability, and linear haptic trackpad with illuminated NumberPad 2.0.',
    featured: false,
    newArrival: false,
    tag: 'Best OLED Value',
    specifications: {
      'Display': '14.0-inch 3K OLED (2880 x 1800, 120Hz, 0.2ms, 600 nits HDR, 100% DCI-P3)',
      'Processor': 'Intel Core Ultra 7 155H with Intel Arc Graphics',
      'RAM': '16GB LPDDR5X onboard',
      'Storage': '1TB M.2 NVMe PCIe 4.0 SSD',
      'Battery': '75Wh 4-cell Li-ion with 65W Type-C fast charging',
      'OS': 'Windows 11 Home with MS Office 2021',
    },
    features: [
      'ASUS NumberPad 2.0 LED numeric keypad integrated into touchpad',
      'Harman Kardon certified audio with Smart Amplifier technology',
      'US MIL-STD 810H military-grade standard durability testing',
    ],
    dimensions: '312.4 x 220.1 x 14.9 mm',
    weight: '1.20 kg',
    warranty: '1-Year ASUS Onsite Warranty',
    shippingInfo: 'Same-day dispatch for orders received before 2 PM.',
    image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'acer-predator-helios-16',
    name: 'Acer Predator Helios 16 (Core i9-14900HX / 16GB / 1TB / RTX 4070)',
    brand: 'Acer',
    category: 'Laptops',
    sku: 'ACR-PH16-I9-4070',
    price: 169990,
    originalPrice: 189990,
    stock: 13,
    rating: 4.6,
    reviewCount: 840,
    tagline: 'WQXGA 240Hz 500 nits display. 5th Gen AeroBlade 3D metal fans.',
    description: 'High-octane gaming rig with 14th Gen Intel Core i9, NVIDIA GeForce RTX 4070 8GB (140W MGP), liquid metal thermal paste, and 4-zone RGB backlit keyboard.',
    fullDescription: 'Predator Helios 16 delivers blistering esports frame rates. Includes NVIDIA Advanced Optimus with MUX switch, dual Killer Wi-Fi 6E connectivity, and predator Pulsar lighting bar.',
    featured: false,
    newArrival: false,
    tag: 'Gaming Pick',
    specifications: {
      'Display': '16.0-inch WQXGA IPS (2560 x 1600, 240Hz, 3ms, 500 nits, 100% DCI-P3, G-SYNC)',
      'Processor': 'Intel Core i9-14900HX (24 Cores, 32 Threads)',
      'Graphics': 'NVIDIA GeForce RTX 4070 (8GB GDDR6, 140W Max Graphics Power)',
      'RAM': '16GB DDR5 5600 MHz (expandable to 32GB)',
      'Storage': '1TB PCIe Gen4 NVMe SSD',
      'Battery': '90Wh with 330W Power Adapter',
      'OS': 'Windows 11 Home',
    },
    features: [
      'Dual 5th Gen AeroBlade 3D metal fans with liquid metal cooling',
      'NVIDIA Advanced Optimus for seamless GPU switching without reboot',
      'PredatorSense utility app for instantaneous fan and overclock control',
    ],
    dimensions: '357.78 x 278.74 x 26.90 mm',
    weight: '2.60 kg',
    warranty: '1-Year Acer International Travelers Warranty (ITW)',
    shippingInfo: 'Free express shipping across all major Indian pincodes.',
    image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80',
    ],
  },
];
