export const PC_COMPONENTS = [
  {
    id: 'asus-tuf-rtx-4080-super-16gb',
    name: 'ASUS TUF Gaming GeForce RTX 4080 Super 16GB GDDR6X',
    brand: 'NVIDIA',
    category: 'PC Components',
    sku: 'NV-TUF4080S-16G',
    price: 108990,
    originalPrice: 119990,
    stock: 8,
    rating: 4.9,
    reviewCount: 940,
    tagline: 'Ada Lovelace architecture. DLSS 3.5 Frame Generation. Military-grade TUF components.',
    description: 'Flagship 4K graphics card powered by NVIDIA Ada Lovelace architecture, 10,240 CUDA cores, 16GB high-speed GDDR6X memory, dual ball fan bearings, and metal exoskeleton.',
    fullDescription: 'ASUS TUF Gaming RTX 4080 Super delivers extreme 4K gaming performance with full ray tracing and neural DLSS 3.5 rendering. Built with military-grade capacitors rated for 20,000 hours at 105°C and rigid aluminum backplate.',
    featured: true,
    newArrival: true,
    tag: '4K GPU King',
    specifications: {
      'Graphics Engine': 'NVIDIA GeForce RTX 4080 SUPER (10,240 CUDA Cores)',
      'Video Memory': '16GB GDDR6X (256-bit bus, 23 Gbps)',
      'Engine Clock': 'OC mode: 2580 MHz | Default mode: 2550 MHz (Boost)',
      'Cooling': '3x Axial-tech fans scaled up for 23% more airflow with 0dB silent mode',
      'Power Connectors': '1x 16-pin (12VHPWR) power cable with 750W recommended PSU',
      'Display Outputs': '2x HDMI 2.1a, 3x DisplayPort 1.4a',
    },
    features: [
      'Axial-tech fans rotate on dual ball bearings for 2x the operational longevity',
      'Dual BIOS switch allows toggling between Performance and Quiet cooling profiles',
      'Auto-Extreme automated manufacturing process ensures flawless solder reliability',
    ],
    dimensions: '348 x 150 x 72.6 mm (3.65 slots)',
    weight: '1.97 kg',
    warranty: '3-Year ASUS India Warranty',
    shippingInfo: 'Heavy-duty cushioned parcel shipment with transit insurance.',
    image: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'msi-rtx-4070-ti-super-16gb',
    name: 'MSI Gaming X Slim GeForce RTX 4070 Ti Super 16GB GDDR6X',
    brand: 'NVIDIA',
    category: 'PC Components',
    sku: 'NV-MSI4070TIS-16G',
    price: 86990,
    originalPrice: 94990,
    stock: 12,
    rating: 4.8,
    reviewCount: 780,
    tagline: 'Slim form factor design. 16GB VRAM on 256-bit bus. TRI FROZR 3 cooling.',
    description: 'High-performance 1440p/4K GPU with 8,448 CUDA cores, 16GB GDDR6X video memory, TORX Fan 5.0 cooling system, and compact dual-slot thickness for versatile PC case clearance.',
    fullDescription: 'MSI GeForce RTX 4070 Ti SUPER Gaming X Slim brings 16GB VRAM buffer required for high-res AI generation and demanding ray-traced textures into a svelte chassis.',
    featured: false,
    newArrival: false,
    tag: 'Sweet Spot VRAM',
    specifications: {
      'Graphics Engine': 'NVIDIA GeForce RTX 4070 Ti SUPER (8,448 CUDA Cores)',
      'Memory': '16GB GDDR6X (256-bit memory bus)',
      'Boost Clock': '2670 MHz (MSI Center Extreme Performance)',
      'Cooling': 'TRI FROZR 3 thermal design with TORX Fan 5.0 and copper baseplate',
      'Form Factor': 'Slim design measuring 307 x 125 x 51 mm (2.5 slots)',
    },
    features: [
      'TORX Fan 5.0 ring arcs link three sets of fan blades for high-pressure airflow',
      'Solid nickel-plated copper baseplate captures heat from GPU and VRAM modules',
      'Included anti-bending support bracket prevents graphics card GPU sag',
    ],
    dimensions: '307 x 125 x 51 mm',
    weight: '1.09 kg',
    warranty: '3-Year MSI India Manufacturer Warranty',
    shippingInfo: 'Fast courier dispatch in sealed factory carton.',
    image: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'sapphire-nitro-plus-rx-7900-xtx',
    name: 'Sapphire Nitro+ AMD Radeon RX 7900 XTX 24GB GDDR6',
    brand: 'AMD',
    category: 'PC Components',
    sku: 'AMD-SAP7900XTX-24G',
    price: 104990,
    originalPrice: 115990,
    stock: 7,
    rating: 4.8,
    reviewCount: 650,
    tagline: '24GB GDDR6 memory. RDNA 3 architecture. Dual ARGB light bar.',
    description: 'AMD flagship graphics card featuring 24GB VRAM, RDNA 3 chiplet technology, Vapor-X cooling chamber, wave fin design, and full-length edge-to-edge ARGB light bar.',
    fullDescription: 'The Sapphire NITRO+ RX 7900 XTX is engineered for enthusiasts wanting maxed-out native rasterization and gigantic 24GB VRAM headroom for 4K gaming, LLM AI inference, and DaVinci Resolve rendering.',
    featured: false,
    newArrival: false,
    tag: '24GB Beast',
    specifications: {
      'GPU Engine': 'AMD Radeon RX 7900 XTX (6,144 Stream Processors, 96 Compute Units)',
      'Memory': '24GB GDDR6 (384-bit bus, 20 Gbps)',
      'Boost Clock': 'Up to 2680 MHz OC Clock',
      'Cooling': 'Vapor-X Chamber with composite heatpipes and Angular Velocity fan blades',
      'Power Connectors': '3x 8-pin power connectors (800W recommended PSU)',
    },
    features: [
      'Vapor-X chamber achieves direct contact with GPU surface for ultra-cool temperatures',
      'Full 24GB VRAM buffer handles large parameter AI models and 8K video timelines',
      'Dual ARGB light bar syncs dynamically with motherboard lighting systems',
    ],
    dimensions: '320 x 135.75 x 71.6 mm (3.5 slot)',
    weight: '1.92 kg',
    warranty: '3-Year Sapphire Warranty',
    shippingInfo: 'Insured transit in protective anti-static packaging.',
    image: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'amd-ryzen-7-7800x3d',
    name: 'AMD Ryzen 7 7800X3D Desktop Processor (8-Core, 16-Thread, 3D V-Cache)',
    brand: 'AMD',
    category: 'PC Components',
    sku: 'AMD-R7-7800X3D',
    price: 38990,
    originalPrice: 44990,
    stock: 22,
    rating: 4.9,
    reviewCount: 4890,
    tagline: 'World undisputed best gaming processor. 104MB cache on AM5 platform.',
    description: 'The definitive champion of PC gaming CPUs. Features 8 cores, 16 threads, AMD 3D V-Cache technology with 96MB L3 cache (104MB total), 120W TDP, and DDR5 support.',
    fullDescription: 'AMD Ryzen 7 7800X3D stacks L3 cache directly onto the compute die using TSMC 3D chiplet packaging. This massive cache radically lowers memory latency in CPU-bound games, achieving superior gaming framerates.',
    featured: true,
    newArrival: false,
    tag: 'Best Gaming CPU',
    specifications: {
      'Cores & Threads': '8 CPU Cores, 16 Threads',
      'Base & Boost Clock': '4.2 GHz Base Clock, up to 5.0 GHz Max Boost Clock',
      'Total Cache': '104MB (8MB L2 + 96MB 3D V-Cache L3)',
      'Socket': 'AM5 (supported through 2027+ on B650/X670/X870 boards)',
      'TDP': '120W power efficiency envelope',
      'Memory Support': 'DDR5 dual-channel with AMD EXPO memory profiles',
    },
    features: [
      'AMD 3D V-Cache delivers unparalleled 1% low framerate stability in esports titles',
      'Low 120W power draw means effortless cooling with standard air or AIO liquid coolers',
      'AMD EXPO one-click memory overclocking optimizes RAM sub-timings for AM5',
    ],
    dimensions: 'Socket AM5 LGA1718',
    weight: '120 grams (retail box without cooler)',
    warranty: '3-Year AMD Domestic Warranty',
    shippingInfo: 'Fast dispatch within 24 hours in sealed retail box.',
    image: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'intel-core-i9-14900k',
    name: 'Intel Core i9-14900K Desktop Processor (24-Core, up to 6.0 GHz Turbo)',
    brand: 'Intel',
    category: 'PC Components',
    sku: 'INT-I9-14900K',
    price: 52990,
    originalPrice: 58990,
    stock: 14,
    rating: 4.7,
    reviewCount: 2130,
    tagline: '24 cores (8 P-cores + 16 E-cores). Blistering 6.0 GHz out of the box.',
    description: 'Flagship desktop processor featuring 24 cores, 32 threads, 6.0 GHz Thermal Velocity Boost, Intel UHD Graphics 770, and compatibility with Intel 600 and 700 series motherboards.',
    fullDescription: 'Intel Core i9-14900K delivers blistering speed for video rendering, Unreal Engine 5 compiling, and workstation multitasking. Features Intel Application Optimization (APO) for targeted game thread scheduling.',
    featured: false,
    newArrival: false,
    tag: '6GHz Flagship',
    specifications: {
      'Cores & Threads': '24 Cores (8 Performance + 16 Efficient), 32 Threads',
      'Clock Speeds': '3.2 GHz P-core Base, up to 6.0 GHz Thermal Velocity Boost',
      'Cache': '36MB Intel Smart Cache (L3) + 32MB L2 Cache',
      'Socket': 'LGA 1700 (Intel Z790/Z690/B760)',
      'Memory': 'DDR5 up to 5600 MT/s and DDR4 up to 3200 MT/s',
    },
    features: [
      '6.0 GHz maximum clock speed without needing manual overclocking',
      'Intel Application Optimization (APO) optimizes thread dispatching for supported games',
      'Integrated Intel UHD 770 Graphics supports Quick Sync video hardware decoding',
    ],
    dimensions: 'Socket LGA 1700',
    weight: '110 grams',
    warranty: '3-Year Intel India Limited Warranty',
    shippingInfo: 'Express courier dispatch with tamper-evident seal.',
    image: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'corsair-vengeance-rgb-ddr5-32gb',
    name: 'Corsair Vengeance RGB DDR5 32GB (2x16GB) 6000MHz CL30 (Black)',
    brand: 'Corsair',
    category: 'PC Components',
    sku: 'COR-VENG-32G-6000',
    price: 11499,
    originalPrice: 13999,
    stock: 35,
    rating: 4.8,
    reviewCount: 3120,
    tagline: 'Optimized for AMD EXPO & Intel XMP. Tight CL30 timings. Ten-zone RGB.',
    description: 'High-speed DDR5 memory kit engineered for AMD Ryzen 7000/9000 and Intel 14th Gen processors. Features 6000MHz speed at ultra-low CL30-36-36-76 timings, aluminum heatspreader, and dynamic ten-zone RGB lighting.',
    fullDescription: 'Corsair Vengeance RGB DDR5 offers the sweet spot for modern desktop performance. Onboard voltage regulation ensures cleaner power delivery, while Corsair iCUE software enables per-LED ambient customization.',
    featured: false,
    newArrival: false,
    tag: 'Sweet Spot DDR5',
    specifications: {
      'Density': '32GB (2 x 16GB dual channel kit)',
      'Speed': 'DDR5-6000 MHz (PC5-48000)',
      'Tested Latency': '30-36-36-76 (Low Latency CL30)',
      'Tested Voltage': '1.35V with onboard Power Management IC (PMIC)',
      'Profiles': 'Dual AMD EXPO and Intel XMP 3.0 profile certification',
    },
    features: [
      'Tight CL30 latency provides the highest memory bandwidth and frame consistency',
      'Panoramic ten-zone RGB light bar enclosed in solid aluminum heatspreader',
      'Onboard PMIC voltage regulation facilitates stable system overclocking',
    ],
    dimensions: '138 x 45 x 7 mm',
    weight: '120 grams (kit)',
    warranty: 'Limited Lifetime Manufacturer Warranty',
    shippingInfo: 'Standard 2-3 business day courier delivery.',
    image: 'https://images.unsplash.com/photo-1562976540-1502c2145186?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1562976540-1502c2145186?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'samsung-990-pro-2tb-heatsink',
    name: 'Samsung 990 Pro 2TB PCIe 4.0 NVMe M.2 SSD with Heatsink',
    brand: 'Samsung',
    category: 'PC Components',
    sku: 'SAM-990PRO-2TB-HS',
    price: 18499,
    originalPrice: 22999,
    stock: 24,
    rating: 4.9,
    reviewCount: 4210,
    tagline: '7,450 MB/s read speed. Custom slim heatsink. PS5 console compatible.',
    description: 'The pinnacle of PCIe 4.0 storage speed. Reaches sequential reads up to 7,450 MB/s and writes up to 6,900 MB/s, custom Samsung Pascal controller, V-NAND TLC, and integrated slim heatsink.',
    fullDescription: 'Samsung 990 Pro maximizes the PCIe 4.0 interface bandwidth. The integrated slim heatsink dissipates heat silently and complies with the PlayStation 5 internal expansion slot dimensions.',
    featured: true,
    newArrival: false,
    tag: 'Storage Leader',
    specifications: {
      'Interface': 'PCIe Gen 4.0 x4, NVMe 2.0 (M.2 2280)',
      'Sequential Read': 'Up to 7,450 MB/s',
      'Sequential Write': 'Up to 6,900 MB/s',
      'Random Read / Write': 'Up to 1,600,000 IOPS / 1,550,000 IOPS',
      'Endurance': '1200 TBW (Terabytes Written)',
      'Heatsink': 'Pre-installed aluminum heatsink with RGB LED indicator',
    },
    features: [
      '50% improved power efficiency per watt compared to previous generation 980 Pro',
      'Fits seamlessly into PlayStation 5 console storage expansion slot',
      'Samsung Magician software suite optimizes drive health, firmware, and encryption',
    ],
    dimensions: '80.15 x 25.0 x 8.88 mm (with heatsink)',
    weight: '30.5 grams',
    warranty: '5-Year Samsung Limited Warranty or 1200 TBW',
    shippingInfo: 'Fast dispatch within 24 hours in anti-static blister packaging.',
    image: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'wd-black-sn850x-2tb',
    name: 'WD_BLACK SN850X 2TB PCIe Gen4 NVMe Internal Gaming SSD',
    brand: 'WD',
    category: 'PC Components',
    sku: 'WD-SN850X-2TB',
    price: 16999,
    originalPrice: 21999,
    stock: 28,
    rating: 4.8,
    reviewCount: 3670,
    tagline: '7,300 MB/s speeds. Game Mode 2.0 predictive loading.',
    description: 'Blazing-fast PCIe Gen4 NVMe M.2 2280 gaming SSD with read speeds up to 7,300 MB/s, custom Western Digital in-house controller, BiCS5 112-layer 3D TLC NAND, and Game Mode 2.0.',
    fullDescription: 'Built from the ground up for hardcore gaming and heavy creative workloads. Game Mode 2.0 serves up PC features that prep game assets in advance for lightning-fast level loading.',
    featured: false,
    newArrival: false,
    tag: 'Gaming Storage',
    specifications: {
      'Form Factor': 'M.2 2280 single-sided',
      'Interface': 'PCIe Gen4 16GT/s, up to 4 lanes',
      'Sequential Read': 'Up to 7,300 MB/s',
      'Sequential Write': 'Up to 6,600 MB/s',
      'Endurance': '1200 Terabytes Written (TBW)',
    },
    features: [
      'Game Mode 2.0 brings PC gaming performance tools to the WD_BLACK Dashboard',
      'Ultra-low latency delivers smooth texture rendering without stuttering in open-world games',
      'Single-sided M.2 form factor fits easily into thin laptops and compact motherboards',
    ],
    dimensions: '80 x 22 x 2.38 mm',
    weight: '7.5 grams',
    warranty: '5-Year Western Digital Limited Warranty',
    shippingInfo: 'Fast courier dispatch in protective box packaging.',
    image: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'corsair-rm850x-shift-850w',
    name: 'Corsair RM850x Shift 850W Fully Modular 80 Plus Gold Power Supply',
    brand: 'Corsair',
    category: 'PC Components',
    sku: 'COR-RM850X-SFT',
    price: 14299,
    originalPrice: 16999,
    stock: 17,
    rating: 4.8,
    reviewCount: 1280,
    tagline: 'Side-mounted modular cable interface. ATX 3.0 & PCIe 5.0 certified.',
    description: 'Revolutionary modular power supply featuring side-facing modular cable connections for effortless cable management. 80 PLUS Gold efficiency, 105°C Japanese capacitors, and native PCIe 5.0 12VHPWR.',
    fullDescription: 'The Corsair RMx SHIFT series transforms PC building. By placing the modular cable panel on the side of the unit rather than the back, all cables are immediately accessible from the side panel.',
    featured: false,
    newArrival: false,
    tag: 'ATX 3.0 Standard',
    specifications: {
      'Wattage': '850 Watts continuous power output',
      'Efficiency Certification': '80 PLUS Gold certified (up to 90% efficiency)',
      'Standards': 'ATX 3.0 & PCIe 5.0 compliant with native 12VHPWR 300W cable',
      'Fan': '140mm fluid dynamic bearing fan with Zero RPM fan mode at low loads',
      'Capacitors': '100% industrial-grade 105°C Japanese electrolytic capacitors',
    },
    features: [
      'Patent-pending side-mounted modular connector panel makes cable routing simple',
      'Zero RPM fan mode ensures virtually silent operation at light and medium loads',
      'Native 16-pin 12VHPWR PCIe 5.0 cable powers RTX 40-series cards without ugly adapters',
    ],
    dimensions: '160 x 150 x 86 mm',
    weight: '1.7 kg',
    warranty: '10-Year Corsair Comprehensive Warranty',
    shippingInfo: 'Insured delivery in heavy-duty packaging.',
    image: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'nzxt-kraken-elite-360-rgb',
    name: 'NZXT Kraken Elite 360 RGB AIO Liquid CPU Cooler with LCD Display',
    brand: 'NZXT',
    category: 'PC Components',
    sku: 'NZX-KRAK-E360-RGB',
    price: 24999,
    originalPrice: 29999,
    stock: 11,
    rating: 4.8,
    reviewCount: 1450,
    tagline: '2.36-inch wide-angle 60Hz LCD screen. Asetek 7th Gen pump. F120 RGB Core fans.',
    description: 'High-performance 360mm all-in-one liquid CPU cooler with customizable 2.36-inch wide-angle 640x640 LCD display, Asetek turbine pump, three F120 RGB Core fans, and reinforced braided tubing.',
    fullDescription: 'NZXT Kraken Elite 360 RGB cools CPUs under heavy thermal loads while displaying personalized GIFs, images, or real-time system temperatures on its brilliant 60Hz IPS LCD screen via NZXT CAM.',
    featured: false,
    newArrival: true,
    tag: 'Custom LCD',
    specifications: {
      'Radiator Size': '360mm aluminum radiator (394 x 120 x 27 mm)',
      'Display': '2.36-inch diameter IPS LCD (640 x 640 resolution, 60Hz refresh rate, 690 cd/m²)',
      'Pump': 'Asetek 7th generation pump motor (800 - 2,800 RPM)',
      'Fans': '3x F120 RGB Core fluid dynamic bearing fans (500 - 1,800 RPM, 78.86 CFM)',
      'Compatibility': 'Intel LGA 1700/1200/115X & AMD AM5/AM4',
    },
    features: [
      'Brilliant 60Hz LCD screen plays custom animated GIFs and live system telemetry',
      'Single breakout cable simplifies pump installation and reduces front motherboard clutter',
      'Reinforced extended rubber tubing with durable braided nylon sleeves',
    ],
    dimensions: 'Radiator: 394 x 120 x 27 mm | Cap: 81.9 x 81.9 x 59.5 mm',
    weight: '1.58 kg',
    warranty: '6-Year NZXT Manufacturer Warranty',
    shippingInfo: 'Dispatched in factory protective box.',
    image: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80',
    ],
  },
];
