export const SMART_HOME = [
  {
    id: 'tp-link-deco-be85-mesh',
    name: 'TP-Link Deco BE85 BE22000 Tri-Band Whole Home Mesh Wi-Fi 7 System (2-Pack)',
    brand: 'TP-Link',
    category: 'Networking & Smart Home',
    sku: 'TPL-DEC-BE85-2PK',
    price: 79999,
    originalPrice: 99999,
    stock: 9,
    rating: 4.9,
    reviewCount: 410,
    tagline: 'Wi-Fi 7 tri-band up to 22 Gbps. Dual 10Gbps ports. Coverage up to 7,600 sq ft.',
    description: 'Next-generation whole-home mesh Wi-Fi 7 system featuring 320MHz channels, 4K-QAM, dual 10Gbps Ethernet/SFP+ combo ports, and multi-link operation (MLO) for zero-lag 8K streaming.',
    fullDescription: 'TP-Link Deco BE85 eliminates dead zones across multi-story homes. With 12 high-gain internal antennas and AI-driven roaming algorithms, devices seamlessly switch nodes without dropping video calls or gaming sessions.',
    featured: true,
    newArrival: true,
    tag: 'Wi-Fi 7 Flagship',
    specifications: {
      'Wi-Fi Standard': 'Wi-Fi 7 (802.11be) Tri-Band (6 GHz: 11520 Mbps + 5 GHz: 8640 Mbps + 2.4 GHz: 1376 Mbps)',
      'Ethernet Ports': '2x 10 Gbps (1x SFP+/RJ45 combo + 1x RJ45) + 2x 2.5 Gbps ports per unit',
      'Coverage': 'Up to 7,600 sq ft (2-pack)',
      'Capacity': 'Connects up to 200+ simultaneous smart home and computing devices',
    },
    features: [
      'Multi-Link Operation (MLO) allows devices to transmit data across multiple bands simultaneously',
      'Dual 10Gbps multi-gigabit ports future-proof high-speed fiber broadband connections',
      'TP-Link HomeShield provides real-time IoT network protection and parental controls',
    ],
    dimensions: '128 x 128 x 236 mm (each tower unit)',
    weight: '1.28 kg per unit',
    warranty: '3-Year TP-Link India Warranty',
    shippingInfo: 'Insured parcel delivery with fragile shipment verification.',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'asus-rog-rapture-gt-axe16000',
    name: 'ASUS ROG Rapture GT-AXE16000 Quad-Band Wi-Fi 6E Gaming Router',
    brand: 'ASUS',
    category: 'Networking & Smart Home',
    sku: 'ASU-GT-AXE16000',
    price: 58990,
    originalPrice: 69990,
    stock: 7,
    rating: 4.8,
    reviewCount: 380,
    tagline: 'World first quad-band Wi-Fi 6E gaming router. Dual 10G ports. Triple-level game acceleration.',
    description: 'Ultimate enthusiast gaming router powered by 2.0 GHz quad-core CPU, quad-band speeds up to 16,000 Mbps, dual 10G ports, four 1G LAN ports, 2.5G WAN, and customizable RGB infinity mirror.',
    fullDescription: 'The ROG Rapture GT-AXE16000 unlocks pristine 6 GHz wireless channels free from older device interference. Triple-level game acceleration prioritizes competitive game packets from PC to game server.',
    featured: false,
    newArrival: false,
    tag: 'Quad-Band Beast',
    specifications: {
      'Wi-Fi Speed': 'Quad-band (6 GHz, 5 GHz-1, 5 GHz-2, 2.4 GHz) up to 16,000 Mbps',
      'Processor': '2.0 GHz 64-bit quad-core flagship processor with 2GB DDR4 RAM',
      'Ports': '2x 10G ports, 1x 2.5G WAN port, 4x 1G LAN ports, USB 3.2 Gen 1',
      'Antennas': '8 external antennas with optimized copper circuitry',
    },
    features: [
      'Dedicated 6 GHz band provides maximum throughput without legacy device interference',
      'Dual 10G ports provide ultra-fast throughput to NAS servers or workstation PCs',
      'Mobile Game Mode prioritizes mobile gaming packet traffic with a single tap in ASUS Router app',
    ],
    dimensions: '354 x 354 x 193 mm',
    weight: '2.42 kg',
    warranty: '3-Year ASUS India Warranty',
    shippingInfo: 'Express courier delivery with reinforced transit protection.',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'netgear-nighthawk-rs700s',
    name: 'Netgear Nighthawk RS700S Tri-Band Wi-Fi 7 Router 19Gbps',
    brand: 'Netgear',
    category: 'Networking & Smart Home',
    sku: 'NTG-RS700S-W7',
    price: 54999,
    originalPrice: 64999,
    stock: 11,
    rating: 4.8,
    reviewCount: 460,
    tagline: '19 Gbps speeds. 10 Gig internet port. 3D antenna design with 3,500 sq ft coverage.',
    description: 'Sleek cylindrical Wi-Fi 7 router with 19Gbps aggregate speed, 10Gbps internet port, four 1Gbps LAN ports, and integrated Netgear Armor cybersecurity protection.',
    fullDescription: 'Netgear Nighthawk RS700S reimagines home networking with an elegant upright enclosure housing eight internal antennas with high-power amplifiers providing 360-degree coverage across up to 3,500 sq ft.',
    featured: false,
    newArrival: true,
    tag: 'Next Gen Speed',
    specifications: {
      'Wi-Fi Technology': 'Wi-Fi 7 (802.11be) Tri-Band up to 19 Gbps',
      'Coverage': 'Up to 3,500 sq. ft. and up to 200 devices connected',
      'Processor': '2.6 GHz quad-core processor',
      'Ethernet Ports': '1x 10Gbps Internet WAN, 1x 10Gbps LAN, 4x 1Gbps LAN',
    },
    features: [
      '3D omnidirectional antenna array delivers uniform signal penetration through thick walls',
      'Pristine 320MHz high-capacity channels double the bandwidth to compatible Wi-Fi 7 laptops',
      'Includes 1-year of Netgear Armor cybersecurity powered by Bitdefender',
    ],
    dimensions: '281.7 x 142 x 124 mm',
    weight: '1.63 kg',
    warranty: '3-Year Netgear Brand Warranty',
    shippingInfo: 'Fast dispatch within 24 hours of confirmation.',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'google-nest-hub-2nd-gen',
    name: 'Google Nest Hub (2nd Generation) Smart Display with Sleep Sensing (Chalk)',
    brand: 'Google',
    category: 'Networking & Smart Home',
    sku: 'GGL-NEST-HUB2-CHK',
    price: 7999,
    originalPrice: 9999,
    stock: 27,
    rating: 4.6,
    reviewCount: 3820,
    tagline: '7-inch smart touch display. Soli radar Sleep Sensing. 50% more bass.',
    description: 'Smart bedside and kitchen display featuring Google Assistant, 7-inch touchscreen, enhanced speaker with 50% more bass, Soli radar Sleep Sensing without cameras, and smart home hub control.',
    fullDescription: 'The Google Nest Hub 2nd Gen is the command center for your helpful home. Motion Sense Soli radar tracks sleep stages and coughing without requiring a wearable or intrusive bedside camera.',
    featured: false,
    newArrival: false,
    tag: 'Bedside Assistant',
    specifications: {
      'Display': '7.0-inch touchscreen LCD (1024 x 600)',
      'Audio': 'Full-range speaker with 43.5mm driver (50% more bass than 1st Gen)',
      'Sensors': 'Soli sensor for Motion Sense, Ambient EQ light sensor, Temperature sensor',
      'Microphones': '3 far-field microphones with hardware mic mute switch',
      'Privacy': 'No camera for guaranteed bedroom privacy',
    },
    features: [
      'Sleep Sensing uses Soli radar to analyze sleep quality without a wearable device',
      'Quick Gestures lets you wave your hand in the air to pause timers or snooze alarms',
      'Central dashboard controls lights, thermostats, and cameras with a single swipe',
    ],
    dimensions: '177.4 x 120.4 x 69.5 mm',
    weight: '558 grams',
    warranty: '1-Year Google India Official Warranty',
    shippingInfo: 'Fast 2-3 business day courier delivery.',
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'amazon-echo-show-10-3rd-gen',
    name: 'Amazon Echo Show 10 (3rd Gen) HD Smart Display with Motion & Alexa (Charcoal)',
    brand: 'Amazon',
    category: 'Networking & Smart Home',
    sku: 'AMZ-ESHOW10-CHR',
    price: 24999,
    originalPrice: 24999,
    stock: 14,
    rating: 4.7,
    reviewCount: 1650,
    tagline: '10.1-inch HD screen moves automatically with you. 13MP auto-framing camera.',
    description: 'Revolutionary smart display with motorized silent rotation that keeps the 10.1-inch HD screen and 13MP camera in view as you move around the room. Built-in Zigbee and Matter smart home hub.',
    fullDescription: 'Amazon Echo Show 10 tracks your movements silently during video calls or while cooking along to recipe videos. Features directional dual front-firing tweeters and powerful woofer that face you as the screen rotates.',
    featured: true,
    newArrival: false,
    tag: 'Motion Smart Display',
    specifications: {
      'Display': '10.1-inch HD touch screen (1280 x 800) with motorized brushless silent swivel',
      'Camera': '13MP camera with auto-framing and physical privacy shutter',
      'Audio': '2.1 system (2x 1.0-inch tweeters + 3.0-inch woofer)',
      'Smart Hub': 'Integrated Zigbee, Matter, and Thread smart home radio',
    },
    features: [
      'Silent motorized base rotates 350 degrees to keep screen in your sightline automatically',
      '13MP camera auto-pans and zooms during video calls to keep you centered in frame',
      'Securely check in on your home remotely with 360-degree panning camera view in Alexa app',
    ],
    dimensions: '251 x 230 x 172 mm',
    weight: '2.56 kg',
    warranty: '1-Year Amazon India Domestic Warranty',
    shippingInfo: 'Secure courier dispatch with cushioned packaging.',
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'amazon-echo-dot-5th-gen',
    name: 'Amazon Echo Dot (5th Gen) Deep Bass Smart Speaker with Alexa (Black)',
    brand: 'Amazon',
    category: 'Networking & Smart Home',
    sku: 'AMZ-EDOT5-BLK',
    price: 4499,
    originalPrice: 5499,
    stock: 45,
    rating: 4.6,
    reviewCount: 7890,
    tagline: 'Best sounding Echo Dot yet. Vibrant audio. Motion sensor & temperature sensing.',
    description: 'Compact smart speaker with improved audio for clearer vocals and deeper bass, built-in ultrasound motion detection, indoor temperature sensor, and hands-free Alexa voice assistance.',
    fullDescription: 'The 5th generation Echo Dot delivers 2x the bass depth of earlier generations. Set up smart routines that turn on your air conditioner if room temperature rises above your set threshold.',
    featured: false,
    newArrival: false,
    tag: 'Bestseller Smart Speaker',
    specifications: {
      'Speaker': '1.73-inch front-firing speaker for high-res lossless audio',
      'Sensors': 'Ultrasound motion detection + Indoor ambient temperature sensor',
      'Voice Assistant': 'Amazon Alexa built-in (English and Hindi multilingual support)',
      'Connectivity': 'Dual-band Wi-Fi 5, Bluetooth Low Energy, Matter support',
    },
    features: [
      'Tap gesture controls on top of speaker to pause songs or snooze wake-up alarms',
      'Temperature sensor triggers smart AC or fan routines when room gets warm',
      'Privacy controls include physical microphone off disconnect button',
    ],
    dimensions: '100 x 100 x 89 mm',
    weight: '304 grams',
    warranty: '1-Year Amazon India Manufacturer Warranty',
    shippingInfo: 'Fast dispatch within 24 hours across India.',
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'philips-hue-starter-kit-e27',
    name: 'Philips Hue White & Color Ambiance Starter Kit (3 Bulbs + Hue Bridge)',
    brand: 'Philips Hue',
    category: 'Networking & Smart Home',
    sku: 'PHL-HUE-STR3-E27',
    price: 14999,
    originalPrice: 17999,
    stock: 19,
    rating: 4.8,
    reviewCount: 2340,
    tagline: '16 million colors. Hue Bridge included. Sync with music, movies & games.',
    description: 'Premier smart lighting ecosystem starter kit including three 800-lumen 9W E27 smart LED bulbs, Hue Bridge, and power adapter. Supports Apple HomeKit, Alexa, and Google Assistant.',
    fullDescription: 'Philips Hue White & Color Ambiance transforms home ambience with 16 million colors and 50,000 shades of warm-to-cool white light. Sync your lights with on-screen TV entertainment with Spotify or PC gaming.',
    featured: false,
    newArrival: false,
    tag: 'Smart Ambience',
    specifications: {
      'Bulbs Included': '3x E27 Base White & Color Ambiance LED bulbs (9W each, 800 lumens)',
      'Color Capabilities': '16 million colors + 2000K to 6500K tunable white spectrum',
      'Hub Included': 'Hue Bridge connects up to 50 lights and 12 accessories throughout home',
      'Ecosystem Support': 'Matter, Apple HomeKit, Google Assistant, Amazon Alexa, SmartThings',
    },
    features: [
      'Hue Bridge enables out-of-home remote control and zero-lag Zigbee mesh communication',
      'Sync with Spotify music to pulse and shift hue dynamically to the rhythm of audio',
      'Wake up gently with sunrise simulation routines that gradually brighten the room',
    ],
    dimensions: 'Bulb: 110 x 60 mm | Bridge: 90.9 x 90.6 x 26 mm',
    weight: 'Bulb: 72 grams each',
    warranty: '2-Year Philips India Warranty',
    shippingInfo: 'Fast courier dispatch in sealed retail box.',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'tp-link-tapo-c225-ai-camera',
    name: 'TP-Link Tapo C225 2K QHD Pan/Tilt AI Smart Home Security Camera',
    brand: 'TP-Link',
    category: 'Networking & Smart Home',
    sku: 'TPL-TAPO-C225-2K',
    price: 4499,
    originalPrice: 5499,
    stock: 32,
    rating: 4.7,
    reviewCount: 3120,
    tagline: '2K QHD 4MP resolution. Smart AI detection for people, pets & abnormal sounds.',
    description: 'High-definition 360-degree pan/tilt indoor security camera with 2K QHD sensor, Starlight night vision, physical lens privacy button, smart motion tracking, and MicroSD card slot up to 512GB.',
    fullDescription: 'The Tapo C225 protects privacy with a physical privacy shutter button that mechanically rotates the camera lens inside its housing. Advanced AI algorithms detect person, pet, and baby crying sounds without cloud subscriptions.',
    featured: false,
    newArrival: false,
    tag: 'Smart Security',
    specifications: {
      'Image Sensor': '1/3-inch Progressive Scan CMOS 2K QHD (2560 x 1440 @ 30fps)',
      'Field of View': '360° Horizontal Pan, 149° Vertical Tilt',
      'Night Vision': '850 nm / 940 nm invisible IR LED + Starlight Color Night Vision',
      'Storage': 'Local MicroSD slot up to 512GB (no mandatory subscription fee)',
    },
    features: [
      'Physical privacy mode rolls the camera lens inside the case with one press',
      'Smart Motion Tracking tracks moving subjects smoothly at up to 120° per second',
      'Two-way audio allows clear communication through built-in microphone and speaker',
    ],
    dimensions: '80 x 80 x 112 mm',
    weight: '240 grams',
    warranty: '2-Year TP-Link India Warranty',
    shippingInfo: 'Standard 2-3 business day courier delivery.',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    ],
  },
];
