export const SMARTPHONES = [
  {
    id: 'apple-iphone-16-pro-max',
    name: 'Apple iPhone 16 Pro Max 256GB (Natural Titanium)',
    brand: 'Apple',
    category: 'Smartphones',
    sku: 'APL-IP16PM-256-NTIT',
    price: 144900,
    originalPrice: 154900,
    stock: 18,
    rating: 4.8,
    reviewCount: 3840,
    tagline: 'Titanium unibody. A18 Pro silicon. Camera Control.',
    description: 'Engineered with Grade 5 titanium, the iPhone 16 Pro Max features a 6.9-inch Super Retina XDR OLED display, A18 Pro chip, and pro-grade 48MP Fusion camera with 5x telephoto optical zoom.',
    fullDescription: 'The iPhone 16 Pro Max delivers unprecedented smartphone power with Apple Intelligence integration, hardware-accelerated ray tracing, 4K 120fps Dolby Vision video recording, and studio-quality 4-mic array. Includes tactile Camera Control button for instant framing and zoom manipulation.',
    featured: true,
    newArrival: true,
    tag: 'Flagship',
    specifications: {
      'Display': '6.9-inch Super Retina XDR OLED (2868 x 1320, 120Hz ProMotion)',
      'Processor': 'Apple A18 Pro (6-core CPU, 6-core GPU, 16-core Neural Engine)',
      'Storage': '256GB NVMe',
      'Rear Camera': '48MP Main + 48MP Ultra-Wide + 12MP 5x Telephoto',
      'Front Camera': '12MP TrueDepth with Autofocus',
      'Battery': 'Up to 33 hours video playback, Qi2 & MagSafe 25W',
      'Build': 'Grade 5 Titanium frame with Ceramic Shield front',
      'OS': 'iOS 18',
    },
    features: [
      'Dedicated tactile capacitive Camera Control button',
      'Apple Intelligence with private cloud compute capabilities',
      '4K 120 fps Dolby Vision HDR studio recording',
      'Next-generation Ceramic Shield with 2x toughest glass formulation',
    ],
    dimensions: '163.0 x 77.6 x 8.25 mm',
    weight: '227 grams',
    warranty: '1-Year Apple India Warranty with AppleCare+ option',
    shippingInfo: 'Free express air delivery across India within 2 business days.',
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'apple-iphone-16-128gb',
    name: 'Apple iPhone 16 128GB (Teal)',
    brand: 'Apple',
    category: 'Smartphones',
    sku: 'APL-IP16-128-TEA',
    price: 79900,
    originalPrice: 84900,
    stock: 24,
    rating: 4.7,
    reviewCount: 2190,
    tagline: 'Vibrant color-infused glass. A18 Bionic. Dual 48MP Fusion.',
    description: 'Dynamic Island, innovative Action button, 6.1-inch Super Retina XDR OLED, and 48MP 2-in-1 Fusion camera system delivering optical-quality 2x telephoto.',
    fullDescription: 'Equipped with the new A18 processor built on second-generation 3-nanometer technology, the iPhone 16 jumps two generations forward. Enjoy tactile Camera Control, Spatial Audio recording, and enhanced thermal dissipation for sustained gaming performance.',
    featured: false,
    newArrival: true,
    tag: 'Trending',
    specifications: {
      'Display': '6.1-inch Super Retina XDR OLED (2556 x 1179, 2000 nits peak)',
      'Processor': 'Apple A18 Chip (6-core CPU, 5-core GPU)',
      'Storage': '128GB NVMe',
      'Rear Camera': '48MP Fusion + 12MP Ultra-Wide with Macro',
      'Front Camera': '12MP TrueDepth Camera',
      'Battery': 'Up to 22 hours video playback, 25W MagSafe',
      'Build': 'Aerospace-grade aluminum with color-infused glass back',
      'OS': 'iOS 18',
    },
    features: [
      'Dynamic Island for glanceable live activities',
      'Action Button customizable for flashlight, voice memo, or camera',
      'Spatial photo and video capture for Apple Vision Pro',
    ],
    dimensions: '147.6 x 71.6 x 7.80 mm',
    weight: '170 grams',
    warranty: '1-Year Official Apple India Warranty',
    shippingInfo: 'Standard 2-3 day insured courier dispatch across major metros.',
    image: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'samsung-galaxy-s25-ultra',
    name: 'Samsung Galaxy S25 Ultra 5G 256GB (Titanium Gray)',
    brand: 'Samsung',
    category: 'Smartphones',
    sku: 'SAM-S25U-256-TGRY',
    price: 129999,
    originalPrice: 139999,
    stock: 14,
    rating: 4.8,
    reviewCount: 4120,
    tagline: 'Snapdragon 8 Elite. Galaxy AI. 200MP Quad Telephoto & S-Pen.',
    description: 'Samsung flagship with built-in S-Pen stylus, flat 6.8-inch Dynamic AMOLED 2X panel with Corning Gorilla Armor anti-reflective glass, and quad camera system with 100x Space Zoom.',
    fullDescription: 'Galaxy S25 Ultra sets the gold standard for Android power. Features Snapdragon 8 Elite for Galaxy, comprehensive Galaxy AI suite with Circle to Search, Live Call Translation, Generative Edit, and 45W super-fast wired charging.',
    featured: true,
    newArrival: true,
    tag: 'Bestseller',
    specifications: {
      'Display': '6.8-inch Dynamic AMOLED 2X (3120 x 1440, 1-120Hz LTPO, 2600 nits)',
      'Processor': 'Snapdragon 8 Elite Mobile Platform for Galaxy',
      'RAM & Storage': '12GB LPDDR5X + 256GB UFS 4.0',
      'Rear Camera': '200MP Main OIS + 50MP Periscope 5x + 50MP Ultra-Wide + 10MP 3x',
      'Battery': '5000 mAh with 45W Wired & Fast Wireless Charging 2.0',
      'Stylus': 'Embedded Bluetooth LE S-Pen stylus',
      'OS': 'One UI 7 on Android 15',
    },
    features: [
      'Anti-reflective Gorilla Armor glass reduces glare by 75%',
      'Integrated low-latency S-Pen for note-taking and remote shutter',
      '7 years of guaranteed OS upgrades and security updates',
    ],
    dimensions: '162.8 x 77.6 x 8.2 mm',
    weight: '219 grams',
    warranty: '1-Year Samsung India Domestic Warranty',
    shippingInfo: 'Express same-day dispatch from regional warehouse.',
    image: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'samsung-galaxy-s25-256gb',
    name: 'Samsung Galaxy S25 5G 256GB (Onyx Black)',
    brand: 'Samsung',
    category: 'Smartphones',
    sku: 'SAM-S25-256-BLK',
    price: 74999,
    originalPrice: 82999,
    stock: 22,
    rating: 4.6,
    reviewCount: 1890,
    tagline: 'Compact ergonomic flagship with Galaxy AI and Dynamic AMOLED 2X.',
    description: 'Compact 6.2-inch FHD+ 120Hz Dynamic AMOLED display, Armor Aluminum chassis, 50MP triple camera system, and all-day intelligent battery.',
    fullDescription: 'The perfect one-handed flagship. Galaxy S25 delivers cutting-edge performance with Snapdragon 8 Elite, ProVisual AI camera engine, IP68 water resistance, and vibrant HDR10+ visuals in a featherlight form factor.',
    featured: false,
    newArrival: true,
    tag: 'Compact Flagship',
    specifications: {
      'Display': '6.2-inch Dynamic AMOLED 2X (2340 x 1080, 1-120Hz, 2600 nits)',
      'Processor': 'Snapdragon 8 Elite for Galaxy',
      'RAM & Storage': '12GB RAM + 256GB UFS 4.0',
      'Camera': '50MP Dual Pixel OIS + 12MP Ultra-Wide + 10MP 3x Telephoto',
      'Battery': '4000 mAh with 25W Fast Charging',
      'OS': 'One UI 7 on Android 15',
    },
    features: [
      'Slim symmetrical bezel design weighing just 167 grams',
      'Circle to Search with Google and real-time live interpreter',
      'Armor Aluminum 2.0 unibody frame for drop resilience',
    ],
    dimensions: '147.0 x 70.6 x 7.6 mm',
    weight: '167 grams',
    warranty: '1-Year Samsung Brand Warranty',
    shippingInfo: 'Fast dispatch within 24 hours across tier-1 and tier-2 Indian cities.',
    image: 'https://images.unsplash.com/photo-1575695342320-d2d2d2f9b73f?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1575695342320-d2d2d2f9b73f?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'samsung-galaxy-z-fold6',
    name: 'Samsung Galaxy Z Fold6 5G 256GB (Silver Shadow)',
    brand: 'Samsung',
    category: 'Smartphones',
    sku: 'SAM-ZF6-256-SLV',
    price: 164999,
    originalPrice: 179999,
    stock: 9,
    rating: 4.7,
    reviewCount: 940,
    tagline: 'Next-gen dual screen foldable with AI-powered multi-window productivity.',
    description: 'Ultra-thin foldable smartphone featuring a 7.6-inch QXGA+ foldable Dynamic AMOLED 2X inner display and 6.3-inch cover screen with enhanced dual-rail hinge.',
    fullDescription: 'The Galaxy Z Fold6 offers unparalleled multitasking with flex mode, S-Pen fold edition compatibility, IP48 water resistance, and Snapdragon 8 Gen 3 for Galaxy.',
    featured: false,
    newArrival: false,
    tag: 'Foldable Pro',
    specifications: {
      'Main Display': '7.6-inch Foldable Dynamic AMOLED 2X (2160 x 1856, 120Hz, 2600 nits)',
      'Cover Display': '6.3-inch Dynamic AMOLED 2X (2376 x 968, 120Hz)',
      'Processor': 'Snapdragon 8 Gen 3 for Galaxy (4nm)',
      'RAM & Storage': '12GB RAM + 256GB UFS 4.0',
      'Camera': '50MP OIS + 12MP Ultra-Wide + 10MP 3x Optical Telephoto',
      'Battery': '4400 mAh dual-cell battery with 25W charging',
      'OS': 'One UI 6.1.1 on Android 14',
    },
    features: [
      'Dual-rail FlexHinge with zero-gap closure mechanism',
      'Galaxy AI Composer and Note Assist with handwriting auto-cleanup',
      'IP48 water and particle intrusion certified resistance',
    ],
    dimensions: 'Folded: 153.5 x 68.1 x 12.1 mm | Unfolded: 153.5 x 132.6 x 5.6 mm',
    weight: '239 grams',
    warranty: '1-Year Samsung India Warranty with 1-time screen replacement offer',
    shippingInfo: 'High-value insured dispatch with OTP verification on delivery.',
    image: 'https://images.unsplash.com/photo-1585060544812-6b45742d762f?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1585060544812-6b45742d762f?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'google-pixel-9-pro-xl',
    name: 'Google Pixel 9 Pro XL 256GB (Obsidian)',
    brand: 'Google',
    category: 'Smartphones',
    sku: 'GGL-PX9PXL-256-OBS',
    price: 124999,
    originalPrice: 134999,
    stock: 15,
    rating: 4.7,
    reviewCount: 2310,
    tagline: 'Google Tensor G4. Gemini Nano with Multimodality. Pro Triple Camera.',
    description: 'Google apex flagship with 6.8-inch Super Actua LTPO OLED (3000 nits), 50MP main sensor, 48MP 5x telephoto, and built-in Gemini Live conversational AI.',
    fullDescription: 'Pixel 9 Pro XL combines polished aerospace metal with matte rear glass. Features 16GB RAM for on-device AI models, temperature sensor, satellite SOS capability, and 7 years of Pixel Feature Drops.',
    featured: true,
    newArrival: true,
    tag: 'Pure Android',
    specifications: {
      'Display': '6.8-inch Super Actua OLED (2992 x 1344, 1-120Hz LTPO, 3000 nits)',
      'Processor': 'Google Tensor G4 with Titan M2 security coprocessor',
      'RAM & Storage': '16GB LPDDR5X + 256GB UFS 3.1',
      'Rear Camera': '50MP Octa PD Main + 48MP Quad PD Ultrawide + 48MP 5x Telephoto',
      'Front Camera': '42MP Dual PD Selfie Camera with Autofocus',
      'Battery': '5060 mAh with 37W Fast Charging & 23W Pixel Stand Wireless',
      'OS': 'Android 15 with 7 Years OS and Security Updates',
    },
    features: [
      'Gemini Live natural voice conversational assistant on-device',
      'Pixel Camera Add Me feature for taking group photos including the photographer',
      'Super Res Zoom up to 30x with AI zoom enhancement algorithm',
    ],
    dimensions: '162.8 x 76.6 x 8.5 mm',
    weight: '221 grams',
    warranty: '1-Year Official Google India Warranty',
    shippingInfo: 'Direct priority dispatch via express courier.',
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'google-pixel-9-128gb',
    name: 'Google Pixel 9 128GB (Peony)',
    brand: 'Google',
    category: 'Smartphones',
    sku: 'GGL-PX9-128-PEO',
    price: 79999,
    originalPrice: 84999,
    stock: 21,
    rating: 4.6,
    reviewCount: 1650,
    tagline: 'Engineered by Google. Tensor G4. Class-leading computational photography.',
    description: '6.3-inch Actua OLED display with 120Hz refresh, all-new sculpted camera bar, dual 50MP + 48MP rear cameras, and 12GB RAM for everyday AI.',
    fullDescription: 'Pixel 9 delivers award-winning computational imaging with Magic Editor, Best Take, and Clear Calling. The satin metal frame and polished glass back offer refined balance and durability.',
    featured: false,
    newArrival: true,
    tag: 'AI Camera',
    specifications: {
      'Display': '6.3-inch Actua OLED (2424 x 1080, 60-120Hz, 2700 nits)',
      'Processor': 'Google Tensor G4',
      'RAM & Storage': '12GB RAM + 128GB Storage',
      'Camera': '50MP Octa PD Main + 48MP Quad PD Ultrawide with Macro Focus',
      'Battery': '4700 mAh with 27W Fast Charging',
      'OS': 'Android 15 with 7 Years Updates',
    },
    features: [
      'Magic Eraser and Audio Magic Eraser for studio audio filtering',
      'Car Crash Detection and Emergency Satellite Connectivity',
      'IP68 dust and water resistance rating',
    ],
    dimensions: '152.8 x 72.0 x 8.5 mm',
    weight: '198 grams',
    warranty: '1-Year Official Google Brand Warranty',
    shippingInfo: 'Fast dispatch within 1-2 business days across India.',
    image: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'oneplus-13-5g-256gb',
    name: 'OnePlus 13 5G 256GB (Midnight Ocean)',
    brand: 'OnePlus',
    category: 'Smartphones',
    sku: '1PL-OP13-256-BLU',
    price: 69999,
    originalPrice: 75999,
    stock: 28,
    rating: 4.7,
    reviewCount: 2950,
    tagline: 'Snapdragon 8 Elite. Hasselblad Master Camera. 6000mAh Glacier Battery.',
    description: 'Flagship powerhouse featuring Qualcomm Snapdragon 8 Elite, 2K 120Hz Oriental Screen with Glove Mode, 100W SUPERVOOC charging, and 50W wireless AIRVOOC.',
    fullDescription: 'OnePlus 13 introduces a massive 6000mAh silicon-carbon Glacier battery with IP69 water and dust ingress protection. The Hasselblad Master Camera system brings natural color calibration and portrait focal length simulations.',
    featured: false,
    newArrival: true,
    tag: 'Powerhouse',
    specifications: {
      'Display': '6.82-inch 2K Oriental LTPO AMOLED (3168 x 1440, 1-120Hz, 4500 nits peak)',
      'Processor': 'Qualcomm Snapdragon 8 Elite (3nm, Oryon CPU)',
      'RAM & Storage': '16GB LPDDR5X + 256GB UFS 4.0',
      'Camera': '50MP Sony LYT-808 OIS + 50MP Periscope 3x + 50MP Ultrawide',
      'Battery': '6000 mAh Glacier Battery with 100W Wired & 50W Wireless',
      'OS': 'OxygenOS 15 based on Android 15',
    },
    features: [
      'IP68 & IP69 dual water resistance rating with Aqua Touch 2.0',
      'Bionic Vibration Motor Turbo for console-grade haptics',
      '100W SUPERVOOC wall charger included in packaging',
    ],
    dimensions: '162.9 x 76.5 x 8.5 mm',
    weight: '213 grams',
    warranty: '1-Year OnePlus India Domestic Warranty',
    shippingInfo: 'Express delivery with real-time transit telemetry.',
    image: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'oneplus-12r-256gb',
    name: 'OnePlus 12R 5G 256GB (Cool Blue)',
    brand: 'OnePlus',
    category: 'Smartphones',
    sku: '1PL-OP12R-256-BLU',
    price: 42999,
    originalPrice: 45999,
    stock: 33,
    rating: 4.6,
    reviewCount: 4180,
    tagline: 'Snapdragon 8 Gen 2. 4th Gen LTPO 120Hz. 5500mAh battery with 100W.',
    description: 'Performance-driven smartphone with 1.5K ProXDR 120Hz display, dual cryo-velocity VC cooling system, and 50MP Sony IMX890 camera with OIS.',
    fullDescription: 'The OnePlus 12R sets the standard in the premium midrange segment. Delivers ultra-responsive 120fps gaming, massive 5500mAh cell with 100W charger included in the box, and OxygenOS fluidity.',
    featured: false,
    newArrival: false,
    tag: 'Value Champion',
    specifications: {
      'Display': '6.78-inch 1.5K LTPO4 AMOLED (2780 x 1264, 1-120Hz, 4500 nits peak)',
      'Processor': 'Qualcomm Snapdragon 8 Gen 2',
      'RAM & Storage': '16GB LPDDR5X + 256GB UFS 3.1',
      'Camera': '50MP Sony IMX890 OIS + 8MP Ultra-Wide + 2MP Macro',
      'Battery': '5500 mAh with 100W SUPERVOOC (0-100% in 26 mins)',
      'OS': 'OxygenOS 14 on Android 14',
    },
    features: [
      'Dual Cryo-Velocity VC vapor chamber heat dissipation',
      'DisplayMate A+ certified panel with 2160Hz high frequency PWM',
      'Alert Slider hardware toggle for ring, vibrate, and silent modes',
    ],
    dimensions: '163.3 x 75.3 x 8.8 mm',
    weight: '207 grams',
    warranty: '1-Year OnePlus India Brand Warranty',
    shippingInfo: 'Fast dispatch within 24 hours of payment authorization.',
    image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'xiaomi-14-ultra-512gb',
    name: 'Xiaomi 14 Ultra 512GB (Titanium Black)',
    brand: 'Xiaomi',
    category: 'Smartphones',
    sku: 'XMI-14U-512-BLK',
    price: 99999,
    originalPrice: 119999,
    stock: 11,
    rating: 4.8,
    reviewCount: 1540,
    tagline: 'Leica Quad 50MP Cameras with 1-inch LYT-900 Variable Aperture sensor.',
    description: 'Professional optical imaging flagship co-developed with Leica. Features four 50MP sensors spanning 12mm to 120mm focal lengths, Snapdragon 8 Gen 3, and 90W fast charging.',
    fullDescription: 'Xiaomi 14 Ultra bridges the boundary between dedicated mirrorless camera and mobile smartphone. Features a stepless variable aperture (f/1.63-f/4.0), Leica color profiles, and ultra-durable Xiaomi Guardian Structure.',
    featured: false,
    newArrival: false,
    tag: 'Leica Optics',
    specifications: {
      'Display': '6.73-inch WQHD+ AMOLED (3200 x 1440, 1-120Hz, 3000 nits)',
      'Processor': 'Qualcomm Snapdragon 8 Gen 3',
      'RAM & Storage': '16GB LPDDR5X + 512GB UFS 4.0',
      'Camera': '50MP 1-inch LYT-900 Variable Aperture + 50MP 3.2x OIS + 50MP 5x Periscope + 50MP Ultra-Wide',
      'Battery': '5000 mAh with 90W HyperCharge & 80W Wireless HyperCharge',
      'OS': 'Xiaomi HyperOS based on Android 14',
    },
    features: [
      'Stepless variable aperture f/1.63 to f/4.0 for hardware bokeh depth',
      'Leica Authentic and Leica Vibrant bespoke optical color science',
      'Xiaomi Shield Glass with 10x drop resistance improvement',
    ],
    dimensions: '161.4 x 75.3 x 9.2 mm',
    weight: '220 grams',
    warranty: '1-Year Comprehensive Manufacturer Warranty',
    shippingInfo: 'Complimentary white-glove express courier with real-time tracking.',
    image: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'nothing-phone-2-256gb',
    name: 'Nothing Phone (2) 256GB (Dark Grey)',
    brand: 'Nothing',
    category: 'Smartphones',
    sku: 'NOTH-PH2-256-DGRY',
    price: 36999,
    originalPrice: 49999,
    stock: 25,
    rating: 4.5,
    reviewCount: 3820,
    tagline: 'Glyph Interface illuminated rear glass with Snapdragon 8+ Gen 1.',
    description: 'Distinctive transparent industrial design with 33 addressable Glyph LED zones, 6.7-inch flexible LTPO OLED, dual 50MP cameras, and bloatware-free Nothing OS 2.5.',
    fullDescription: 'Nothing Phone (2) encourages mindful screen time. The Glyph Interface displays volume levels, countdown timers, delivery progress, and priority contact notifications without turning on the screen. Pillowed curved glass back provides comfortable hand ergonomics.',
    featured: false,
    newArrival: false,
    tag: 'Iconic Design',
    specifications: {
      'Display': '6.7-inch Flexible LTPO OLED (1080 x 2412, 1-120Hz, 1600 nits)',
      'Processor': 'Qualcomm Snapdragon 8+ Gen 1 (4nm)',
      'RAM & Storage': '12GB RAM + 256GB Storage',
      'Camera': '50MP Sony IMX890 OIS + 50MP Samsung JN1 Ultrawide',
      'Battery': '4700 mAh with 45W PPS fast charging & 15W Qi wireless',
      'OS': 'Nothing OS 2.6 on Android 14',
    },
    features: [
      'Essential Glyph notifications for selected contacts and apps',
      'Glyph Composer enables creating custom ringtones and light patterns',
      '100% recycled aluminum mid-frame and zero pre-installed bloatware',
    ],
    dimensions: '162.1 x 76.4 x 8.6 mm',
    weight: '201 grams',
    warranty: '1-Year Brand Warranty',
    shippingInfo: 'Fast dispatch from Mumbai fulfillment center within 24 hours.',
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'motorola-edge-50-ultra',
    name: 'Motorola Edge 50 Ultra 512GB (Peach Fuzz)',
    brand: 'Motorola',
    category: 'Smartphones',
    sku: 'MOT-E50U-512-PCH',
    price: 54999,
    originalPrice: 64999,
    stock: 19,
    rating: 4.6,
    reviewCount: 1480,
    tagline: 'Pantone-validated color with real wood/vegan leather back.',
    description: '6.7-inch 144Hz Super HD pOLED curved screen, Snapdragon 8s Gen 3 processor, triple 50MP AI camera system with periscope telephoto, and 125W TurboPower charging.',
    fullDescription: 'Motorola Edge 50 Ultra pairs genuine handcrafted wood or soft vegan leather finishes with sandblasted aluminum chassis. Features Pantone-validated display and camera tuning, IP68 water resistance, and 50W wireless charging.',
    featured: false,
    newArrival: false,
    tag: 'Artisan Finish',
    specifications: {
      'Display': '6.7-inch 1.5K pOLED (2712 x 1220, 144Hz curved, 2500 nits)',
      'Processor': 'Qualcomm Snapdragon 8s Gen 3',
      'RAM & Storage': '16GB LPDDR5X + 512GB UFS 4.0',
      'Camera': '50MP OIS + 50MP Ultrawide Macro + 64MP 3x Periscope Telephoto',
      'Battery': '4500 mAh with 125W TurboPower (0-100% in 18 minutes)',
      'Build': 'IP68 water resistant with authentic wood/leather backing',
      'OS': 'Hello UI on Android 14',
    },
    features: [
      'Moto AI Photo Enhancement Engine with Auto Focus Tracking',
      'World first Pantone Validated camera and display certification',
      '125W TurboPower charger and protective cover included in box',
    ],
    dimensions: '161.09 x 72.38 x 8.59 mm',
    weight: '197 grams',
    warranty: '1-Year Motorola India Warranty',
    shippingInfo: 'Dispatched securely via insured express courier.',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
    ],
  },
];
