export const TABLETS = [
  {
    id: 'apple-ipad-pro-13-m4',
    name: 'Apple iPad Pro 13-inch M4 256GB Wi-Fi (Space Black)',
    brand: 'Apple',
    category: 'Tablets',
    sku: 'APL-IPP13-M4-256',
    price: 129900,
    originalPrice: 129900,
    stock: 14,
    rating: 4.9,
    reviewCount: 1450,
    tagline: 'Ultra Retina XDR Tandem OLED. Apple M4 chip. Impossibly thin 5.1mm.',
    description: 'Thinnest Apple product ever made at just 5.1mm. Features groundbreaking Tandem OLED Ultra Retina XDR display, breakthrough M4 chip with hardware ray tracing, and Apple Pencil Pro support.',
    fullDescription: 'The 13-inch iPad Pro with M4 delivers 1000 nits full-screen brightness and 1600 nits peak HDR. Features 12MP landscape front camera with Center Stage, Thunderbolt / USB 4 connectivity, and quad studio-grade speakers.',
    featured: true,
    newArrival: true,
    tag: 'Flagship Slate',
    specifications: {
      'Display': '13-inch Ultra Retina XDR Tandem OLED (2752 x 2064, 10-120Hz ProMotion, 1600 nits peak)',
      'Processor': 'Apple M4 chip (9-core CPU, 10-core GPU, 16-core Neural Engine)',
      'Storage': '256GB NVMe',
      'Cameras': '12MP Wide rear camera with LiDAR Scanner + 12MP Landscape Center Stage front',
      'Connectivity': 'Thunderbolt / USB 4, Wi-Fi 6E (802.11ax), Bluetooth 5.3',
      'Battery': '38.99Wh rechargeable lithium-polymer (up to 10 hours web browsing)',
    },
    features: [
      'Breakthrough Tandem OLED technology combines light from two OLED panels',
      'Supports Apple Pencil Pro with barrel roll, squeeze haptics, and Find My',
      'Only 5.1mm thin with rigid aluminum enclosure for maximum portability',
    ],
    dimensions: '281.6 x 215.5 x 5.1 mm',
    weight: '579 grams',
    warranty: '1-Year Apple India Warranty',
    shippingInfo: 'Complimentary insured courier delivery with live transit tracking.',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'apple-ipad-air-13-m2',
    name: 'Apple iPad Air 13-inch M2 128GB Wi-Fi (Starlight)',
    brand: 'Apple',
    category: 'Tablets',
    sku: 'APL-IPA13-M2-128',
    price: 79900,
    originalPrice: 84900,
    stock: 20,
    rating: 4.8,
    reviewCount: 1890,
    tagline: 'Expansive 13-inch Liquid Retina display powered by Apple M2 silicon.',
    description: 'Redesigned 13-inch iPad Air featuring Liquid Retina anti-reflective screen, blazing M2 chip, landscape 12MP front camera with Center Stage, and Touch ID power button.',
    fullDescription: 'The new 13-inch iPad Air gives you 30% more screen real estate than previous models. Perfect for Split View multitasking, digital sketching with Apple Pencil Pro, and 4K video editing in Final Cut Pro.',
    featured: false,
    newArrival: true,
    tag: 'Creator Choice',
    specifications: {
      'Display': '13-inch Liquid Retina Display (2732 x 2048, 600 nits, P3 Wide Color, True Tone)',
      'Processor': 'Apple M2 chip (8-core CPU, 9-core GPU, 16-core Neural Engine)',
      'Storage': '128GB',
      'Audio': 'Landscape stereo speakers with 2x more bass',
      'Security': 'Touch ID fingerprint sensor integrated into top power button',
    },
    features: [
      'Apple M2 chip delivers nearly 50% faster performance than prior iPad Air',
      'Landscape 12MP Ultra Wide front camera ideal for video conference calls',
      'Compatible with Magic Keyboard and Apple Pencil Pro',
    ],
    dimensions: '280.6 x 214.9 x 6.1 mm',
    weight: '617 grams',
    warranty: '1-Year Apple Warranty',
    shippingInfo: 'Fast dispatch within 24 hours of purchase.',
    image: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'apple-ipad-10th-gen',
    name: 'Apple iPad 10th Gen 10.9-inch Wi-Fi 64GB (Blue)',
    brand: 'Apple',
    category: 'Tablets',
    sku: 'APL-IP10-64-BLU',
    price: 34900,
    originalPrice: 39900,
    stock: 31,
    rating: 4.7,
    reviewCount: 4520,
    tagline: 'All-screen design. 10.9-inch Liquid Retina display. A14 Bionic.',
    description: 'Colorful everyday tablet with 10.9-inch Liquid Retina display, A14 Bionic chip, landscape 12MP Ultra Wide front camera, USB-C connector, and Wi-Fi 6.',
    fullDescription: 'The 10th-generation iPad brings modern edge-to-edge design at an accessible price. Draw, take notes, and collaborate effortlessly using Apple Pencil and Magic Keyboard Folio.',
    featured: false,
    newArrival: false,
    tag: 'Bestseller',
    specifications: {
      'Display': '10.9-inch Liquid Retina Display (2360 x 1640, 500 nits, True Tone)',
      'Processor': 'A14 Bionic chip with 6-core CPU and 4-core GPU',
      'Storage': '64GB',
      'Camera': '12MP Wide back camera + Landscape 12MP Ultra Wide front camera',
      'Connector': 'USB-C port for charging and accessories',
    },
    features: [
      'Touch ID in top button for fast, secure authentication',
      'Center Stage automatically keeps you centered in frame during video calls',
      'Stereo landscape speakers for rich movie watching',
    ],
    dimensions: '248.6 x 179.5 x 7.0 mm',
    weight: '477 grams',
    warranty: '1-Year Apple India Domestic Warranty',
    shippingInfo: 'Express courier delivery across India.',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'samsung-galaxy-tab-s10-ultra',
    name: 'Samsung Galaxy Tab S10 Ultra 5G 256GB (Moonstone Gray)',
    brand: 'Samsung',
    category: 'Tablets',
    sku: 'SAM-TS10U-256-GRY',
    price: 122999,
    originalPrice: 134999,
    stock: 9,
    rating: 4.8,
    reviewCount: 890,
    tagline: '14.6-inch Dynamic AMOLED 2X. Anti-Reflection Armor. Bundled S-Pen.',
    description: 'Monumental 14.6-inch flagship Android tablet with MediaTek Dimensity 9300+ processor, Galaxy AI features, anti-reflective coating, IP68 water resistance, and low-latency S-Pen.',
    fullDescription: 'Galaxy Tab S10 Ultra is a true PC-replacement tablet. Boasting Samsung DeX mode, quad AKG speakers with Dolby Atmos, Armor Aluminum frame, and seamless clip-on book cover keyboard support.',
    featured: true,
    newArrival: true,
    tag: 'Giant Slate',
    specifications: {
      'Display': '14.6-inch Dynamic AMOLED 2X (2960 x 1848, 120Hz, Anti-Reflective, HDR10+)',
      'Processor': 'MediaTek Dimensity 9300+ (4nm flagship octa-core)',
      'RAM & Storage': '12GB RAM + 256GB Storage (MicroSD expandable up to 1.5TB)',
      'Stylus': 'S-Pen included in box with IP68 rating and magnetic charging',
      'Battery': '11,200 mAh with 45W Super Fast Charging 2.0',
    },
    features: [
      'Anti-reflective coating reduces glare even under bright studio lighting',
      'Galaxy AI Circle to Search and Note Assist with PDF voice transcriptions',
      'IP68 water and dust resistance for both tablet and S-Pen',
    ],
    dimensions: '326.4 x 208.6 x 5.4 mm',
    weight: '718 grams',
    warranty: '1-Year Samsung India Warranty',
    shippingInfo: 'High-value insured delivery with signature receipt.',
    image: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'samsung-galaxy-tab-s9-fe-plus',
    name: 'Samsung Galaxy Tab S9 FE+ Wi-Fi 128GB (Mint)',
    brand: 'Samsung',
    category: 'Tablets',
    sku: 'SAM-TS9FE-128-MNT',
    price: 46999,
    originalPrice: 54999,
    stock: 22,
    rating: 4.6,
    reviewCount: 2130,
    tagline: '12.4-inch 90Hz display. IP68 water resistance with included S-Pen.',
    description: 'Expansive 12.4-inch productivity tablet featuring Vision Booster outdoor adaptive brightness, Exynos 1380 processor, 10,090mAh long-lasting battery, and bundled stylus.',
    fullDescription: 'The Galaxy Tab S9 FE+ delivers pro-level productivity at an accessible price. Enjoy smooth note-taking with the inbox S-Pen, dual AKG speakers, and expandable microSD card storage up to 1TB.',
    featured: false,
    newArrival: false,
    tag: 'Value Big Screen',
    specifications: {
      'Display': '12.4-inch WQXGA LCD (2560 x 1600, 90Hz refresh rate, DCI-P3)',
      'Processor': 'Samsung Exynos 1380 Octa-core',
      'RAM & Storage': '8GB RAM + 128GB Storage (MicroSD up to 1TB)',
      'Battery': '10,090 mAh with 45W Fast Charging support',
      'Stylus': 'IP68 S-Pen included in retail box',
    },
    features: [
      'IP68 water and dust resistance ensures peace of mind outdoors',
      'Vision Booster algorithm maintains screen clarity under direct sunlight',
      'Samsung DeX desktop interface for multi-window windowed workflow',
    ],
    dimensions: '285.4 x 185.4 x 6.5 mm',
    weight: '627 grams',
    warranty: '1-Year Samsung Brand Warranty',
    shippingInfo: 'Fast courier dispatch within 24 hours.',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'oneplus-pad-2-256gb',
    name: 'OnePlus Pad 2 256GB (Nimbus Gray)',
    brand: 'OnePlus',
    category: 'Tablets',
    sku: '1PL-PAD2-256-GRY',
    price: 42999,
    originalPrice: 47999,
    stock: 25,
    rating: 4.7,
    reviewCount: 1680,
    tagline: 'Snapdragon 8 Gen 3. 3K 144Hz 7:5 ReadFit display. 67W SUPERVOOC.',
    description: 'Flagship tier performance tablet with 12.1-inch 3K 144Hz display, Snapdragon 8 Gen 3 flagship silicon, 6-speaker spatial audio system, and 9510mAh battery.',
    fullDescription: 'OnePlus Pad 2 features a unique 7:5 aspect ratio optimized for reading documents and books. Seamlessly syncs clipboard, notifications, and screen mirroring with OnePlus and Android devices.',
    featured: false,
    newArrival: true,
    tag: 'Flagship Performer',
    specifications: {
      'Display': '12.1-inch 3K LCD (3000 x 2120, 144Hz, 900 nits peak, 7:5 aspect ratio)',
      'Processor': 'Qualcomm Snapdragon 8 Gen 3 (4nm)',
      'RAM & Storage': '12GB LPDDR5X + 256GB UFS 3.1',
      'Audio': '6 Omnibearing speakers with Sound Field Expansion',
      'Battery': '9510 mAh with 67W SUPERVOOC Fast Charging',
    },
    features: [
      'Unique 7:5 ReadFit screen mimics textbook pages for natural reading',
      'Open Canvas multitasking displays up to 3 split apps simultaneously',
      '67W SUPERVOOC charges battery from 0 to 64% in only 30 minutes',
    ],
    dimensions: '268.66 x 195.06 x 6.49 mm',
    weight: '584 grams',
    warranty: '1-Year OnePlus India Warranty',
    shippingInfo: 'Standard 2-3 business day courier delivery.',
    image: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'xiaomi-pad-6-256gb',
    name: 'Xiaomi Pad 6 256GB (Graphite Grey)',
    brand: 'Xiaomi',
    category: 'Tablets',
    sku: 'XMI-PAD6-256-GRY',
    price: 28999,
    originalPrice: 39999,
    stock: 28,
    rating: 4.6,
    reviewCount: 3920,
    tagline: '11-inch 2.8K 144Hz screen. Snapdragon 870. Quad Dolby Atmos speakers.',
    description: 'Unibody metal design tablet with 11-inch 2.8K 144Hz 7-stage variable refresh display, Snapdragon 870 processor, 8840mAh battery, and 33W fast charge.',
    fullDescription: 'The Xiaomi Pad 6 delivers unbeatable performance per rupee. Aluminum unibody construction, Dolby Vision and Atmos certification, and Xiaomi Smart Pen 2nd Gen compatibility.',
    featured: false,
    newArrival: false,
    tag: 'Best Budget Tablet',
    specifications: {
      'Display': '11.0-inch 2.8K (2880 x 1800, 144Hz 7-stage refresh, Dolby Vision, 550 nits)',
      'Processor': 'Qualcomm Snapdragon 870 5G Mobile Platform',
      'RAM & Storage': '8GB LPDDR5 + 256GB UFS 3.1',
      'Audio': 'Quad stereo speakers with Dolby Atmos support',
      'Battery': '8840 mAh with 33W fast charging adapter in box',
    },
    features: [
      '7-stage variable refresh rate optimizes smoothness and battery lifespan',
      'Sleek metal unibody enclosure measuring just 6.51mm thin',
      'FocusFrame front camera auto-adjusts orientation during video meetings',
    ],
    dimensions: '253.95 x 165.18 x 6.51 mm',
    weight: '490 grams',
    warranty: '1-Year Xiaomi India Warranty',
    shippingInfo: 'Fast dispatch within 24 hours of payment.',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'lenovo-tab-p12-3k',
    name: 'Lenovo Tab P12 12.7-inch 3K (Storm Grey with Tab Pen Plus)',
    brand: 'Lenovo',
    category: 'Tablets',
    sku: 'LNV-TABP12-3K-GRY',
    price: 26999,
    originalPrice: 34999,
    stock: 19,
    rating: 4.5,
    reviewCount: 1470,
    tagline: '12.7-inch 3K LTPS display with JBL quad speakers and bundled stylus.',
    description: 'Large-screen multimedia tablet featuring 12.7-inch 3K LCD display, MediaTek Dimensity 7050 octa-core processor, JBL quad speakers, and bundled Lenovo Tab Pen Plus.',
    fullDescription: 'Designed for students and streaming enthusiasts. The Tab P12 offers split-screen quad multitasking, reading mode with chromatic filter, and expansive 10,200mAh battery for up to 10 hours video playback.',
    featured: false,
    newArrival: false,
    tag: 'Large Screen Value',
    specifications: {
      'Display': '12.7-inch 3K LTPS LCD (2944 x 1840, 60Hz, 400 nits, 96% DCI-P3)',
      'Processor': 'MediaTek Dimensity 7050 (8 cores, up to 2.6 GHz)',
      'RAM & Storage': '8GB LPDDR4x + 128GB UFS 2.2 (MicroSD expandable)',
      'Audio': 'Quad JBL speakers customized with Dolby Atmos',
      'Battery': '10,200 mAh with 30W Quick Charge support',
    },
    features: [
      'Includes Lenovo Tab Pen Plus stylus with tilt and pressure sensitivity',
      'Four-split screen multitasking for note-taking alongside PDF reading',
      'Chromatics and mono reading modes that alleviate eye strain',
    ],
    dimensions: '293.3 x 190.7 x 6.9 mm',
    weight: '615 grams',
    warranty: '1-Year Lenovo Domestic Warranty',
    shippingInfo: 'Standard insured courier dispatch.',
    image: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=800&q=80',
    ],
  },
];
