export const WEARABLES = [
  {
    id: 'apple-watch-ultra-2',
    name: 'Apple Watch Ultra 2 (GPS + Cellular, 49mm Titanium Case with Blue Ocean Band)',
    brand: 'Apple',
    category: 'Smartwatches & Wearables',
    sku: 'APL-AWU2-49-OCN',
    price: 89900,
    originalPrice: 89900,
    stock: 11,
    rating: 4.9,
    reviewCount: 1640,
    tagline: '49mm aerospace-grade titanium. 3000 nits display. Precision dual-frequency GPS.',
    description: 'Rugged smartwatch built for endurance athletes, outdoor adventurers, and water sports. Features S9 SiP chip, up to 36 hours normal battery (72 hours in low power), and 100m water resistance.',
    fullDescription: 'The Apple Watch Ultra 2 is the most capable smartwatch in Apple history. Features precision dual-frequency L1 and L5 GPS, depth gauge and water temperature sensor with EN13319 scuba certification, and customizable tactile Action button.',
    featured: true,
    newArrival: true,
    tag: 'Extreme Rugged',
    specifications: {
      'Case': '49mm Aerospace-grade Titanium with sapphire crystal front',
      'Display': 'Always-On Retina display (up to 3000 nits brightness, down to 1 nit in dark)',
      'Chip': 'S9 SiP with 64-bit dual-core processor and 4-core Neural Engine',
      'Sensors': 'Depth gauge with water temperature sensor, ECG, Blood Oxygen, Temperature sensing',
      'Battery': 'Up to 36 hours regular use (up to 72 hours in Low Power Mode)',
      'Water Resistance': '100m water resistant, certified EN13319 dive computer standard to 40m',
    },
    features: [
      'Customizable Action Button in international orange for instant workout start',
      'Dual-frequency GPS combines L1 and L5 signals with advanced satellite maps',
      '86-decibel Siren audible up to 180 meters for emergency rescue alerting',
    ],
    dimensions: '49 x 44 x 14.4 mm',
    weight: '61.4 grams (case only)',
    warranty: '1-Year Apple Warranty',
    shippingInfo: 'High-value priority courier dispatch with OTP confirmation.',
    image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'apple-watch-series-10',
    name: 'Apple Watch Series 10 (GPS, 46mm Jet Black Aluminum with Black Sport Band)',
    brand: 'Apple',
    category: 'Smartwatches & Wearables',
    sku: 'APL-AWS10-46-JBLK',
    price: 49900,
    originalPrice: 49900,
    stock: 22,
    rating: 4.8,
    reviewCount: 2890,
    tagline: 'Thinnest Apple Watch ever. Wide-angle OLED display. Sleep apnea notifications.',
    description: 'Thinnest Apple Watch at 9.7mm with 30% more active screen area. Wide-angle OLED provides up to 40% brighter viewing off-axis, fast charging to 80% in 30 minutes, and sleep apnea notifications.',
    fullDescription: 'Apple Watch Series 10 features a breakthrough wide-angle OLED display that refreshes once per second in always-on mode. Built with the S10 SiP, depth gauge to 6 meters, and built-in speaker playback for music and podcasts.',
    featured: false,
    newArrival: true,
    tag: 'Next Gen',
    specifications: {
      'Case': '46mm polished Jet Black aluminum case',
      'Display': 'Wide-angle OLED Always-On Retina display (up to 2000 nits)',
      'Processor': 'S10 SiP with 64-bit dual-core processor and 4-core Neural Engine',
      'Health Sensors': 'Electrical heart sensor (ECG), Third-generation optical heart sensor, Sleep apnea detection',
      'Battery': 'Up to 18 hours (fast charge to 80% in approximately 30 minutes)',
      'Water Resistance': '50m swimproof with depth gauge and water temperature sensor',
    },
    features: [
      'Wide-angle OLED emits more light at wider angles for easy glanceability',
      'Sleep Apnea notification alerts users to breathing disturbances overnight',
      'Integrated speaker allows playing podcasts and songs directly from watch',
    ],
    dimensions: '46 x 39 x 9.7 mm',
    weight: '36.4 grams',
    warranty: '1-Year Apple India Domestic Warranty',
    shippingInfo: 'Fast courier dispatch within 24 hours of order receipt.',
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'samsung-galaxy-watch-ultra',
    name: 'Samsung Galaxy Watch Ultra (LTE, 47mm Titanium Gray with Marine Band)',
    brand: 'Samsung',
    category: 'Smartwatches & Wearables',
    sku: 'SAM-GWU-47-TGRY',
    price: 59999,
    originalPrice: 64999,
    stock: 14,
    rating: 4.8,
    reviewCount: 980,
    tagline: 'Titanium cushion design. 10ATM & IP68. Galaxy AI Energy Score.',
    description: 'Rugged outdoor smartwatch engineered with Grade 4 Titanium, 3000 nits sapphire display, dual-frequency GPS, Quick Button for sports transitions, and 100-hour battery mode.',
    fullDescription: 'Samsung Galaxy Watch Ultra endures extreme temperatures from -20°C to 55°C and 9,000m altitudes. Powered by 3nm Exynos W1000 processor, Galaxy AI wellness coaching, and siren alarm.',
    featured: true,
    newArrival: true,
    tag: 'Pro Endurance',
    specifications: {
      'Case': '47mm Grade 4 Titanium cushion frame with Sapphire Crystal glass',
      'Display': '1.5-inch Super AMOLED (480 x 480, 3000 nits peak, Always-on)',
      'Processor': 'Exynos W1000 (3nm Penta-core processor)',
      'Connectivity': '4G LTE, Dual-frequency GPS (L1 + L5), Bluetooth 5.3, NFC',
      'Battery': '590 mAh (up to 100 hours in Power Saving mode, 48 hours Exercise mode)',
      'Durability': '10ATM + IP68 water resistance, MIL-STD-810H compliant',
    },
    features: [
      'Galaxy AI Energy Score calculates physical readiness from sleep and heart stats',
      'Physical Quick Button lets you instantly trigger multisport triathlons',
      'Emergency Siren sounds an 86dB beacon audible up to 180 meters',
    ],
    dimensions: '47.4 x 47.1 x 12.1 mm',
    weight: '60.5 grams',
    warranty: '1-Year Samsung India Warranty',
    shippingInfo: 'Insured transit dispatch via air courier.',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'samsung-galaxy-watch-7',
    name: 'Samsung Galaxy Watch7 (Bluetooth, 44mm Green)',
    brand: 'Samsung',
    category: 'Smartwatches & Wearables',
    sku: 'SAM-GW7-44-GRN',
    price: 32999,
    originalPrice: 36999,
    stock: 24,
    rating: 4.6,
    reviewCount: 1720,
    tagline: '3nm Exynos W1000. Enhanced BioActive sensor. Galaxy AI coaching.',
    description: 'Everyday lifestyle and fitness tracker with 44mm aluminum chassis, upgraded 13-LED BioActive sensor, personalized heart rate zones, and seamless One UI Watch 6.',
    fullDescription: 'Galaxy Watch7 offers 3x faster CPU execution with the 3nm Exynos processor. Features Sleep Coaching, AGEs index measurement for metabolic tracking, and dual-frequency GPS for precision city routing.',
    featured: false,
    newArrival: false,
    tag: 'Daily Smart',
    specifications: {
      'Case': '44mm Armor Aluminum 2.0 with Sapphire Crystal glass',
      'Display': '1.5-inch Super AMOLED (480 x 480, 2000 nits, Always On)',
      'Processor': 'Exynos W1000 (3nm)',
      'Sensors': 'Samsung BioActive Sensor (Optical Heart Rate + Electrical Heart + Bioelectrical Impedance)',
      'Battery': '425 mAh with WPC wireless charging',
    },
    features: [
      'AGEs index tracks biological metabolic aging from advanced glycation end-products',
      'Dual-frequency GPS accurately tracks running pace between high-rise buildings',
      'Suggested Replies powered by Galaxy AI contextually drafts text responses',
    ],
    dimensions: '44.4 x 44.4 x 9.7 mm',
    weight: '33.8 grams',
    warranty: '1-Year Samsung Brand Warranty',
    shippingInfo: 'Standard 2-3 business day delivery.',
    image: 'https://images.unsplash.com/photo-1510017803434-a899398421b3?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1510017803434-a899398421b3?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'garmin-fenix-8-solar-51mm',
    name: 'Garmin Fenix 8 Solar 51mm (Titanium with DLC Coating & Sapphire Glass)',
    brand: 'Garmin',
    category: 'Smartwatches & Wearables',
    sku: 'GAR-FEN8-SOL-51',
    price: 104990,
    originalPrice: 114990,
    stock: 7,
    rating: 4.9,
    reviewCount: 420,
    tagline: 'Solar charging with up to 48 days battery. Built-in mic, speaker & dive rating.',
    description: 'Premier multisport GPS smartwatch with solar charging lens, titanium bezel, built-in flashlight, speaker and microphone for phone calls, TopoActive mapping, and 40m scuba dive rating.',
    fullDescription: 'The Garmin Fenix 8 Solar 51mm is designed for uncompromising athletes and adventurers. The Power Sapphire lens delivers 50% more solar power than its predecessor, providing up to 48 days in smartwatch mode. Includes leak-proof inductive buttons and targeted strength training plans.',
    featured: true,
    newArrival: true,
    tag: 'Elite Expedition',
    specifications: {
      'Lens Material': 'Power Sapphire with Solar charging ring',
      'Bezel Material': 'Titanium with Diamond-Like Carbon (DLC) coating',
      'Display': '1.4-inch Sunlight-visible, transflective memory-in-pixel (MIP) (280 x 280)',
      'Battery Life': 'Up to 30 days / 48 days with solar in smartwatch mode; up to 149 hours GPS with solar',
      'Water Rating': '10 ATM with 40-meter scuba diving certification (EN13319)',
      'Memory': '32GB onboard for offline worldwide TopoActive maps and Spotify music',
    },
    features: [
      'Integrated LED flashlight with variable intensities, red light, and strobe cadence',
      'Leak-proof inductive buttons engineered for deep water diving pressure',
      'Offline TopoActive topographic maps with dynamic round-trip routing',
    ],
    dimensions: '51 x 51 x 15.4 mm',
    weight: '95 grams (titanium case with silicone band)',
    warranty: '2-Year Garmin International Warranty',
    shippingInfo: 'High-value white glove courier transit with insurance.',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'garmin-forerunner-965',
    name: 'Garmin Forerunner 965 GPS Running Smartwatch (Amp Yellow / Black Titanium)',
    brand: 'Garmin',
    category: 'Smartwatches & Wearables',
    sku: 'GAR-FR965-YEL-TIT',
    price: 67490,
    originalPrice: 67490,
    stock: 12,
    rating: 4.8,
    reviewCount: 840,
    tagline: 'Brilliant 1.4-inch AMOLED. Titanium bezel. Full-color built-in mapping.',
    description: 'Premium dedicated running and triathlon smartwatch with crisp 1.4-inch AMOLED touchscreen, lightweight titanium bezel, wrist-based running dynamics, and 23 days battery.',
    fullDescription: 'The Forerunner 965 gives runners actionable training metrics including Training Readiness, HRV Status, and acute-to-chronic training load ratios. Preloaded with full-color topographic mapping for trail navigating.',
    featured: false,
    newArrival: false,
    tag: 'Runner Benchmark',
    specifications: {
      'Display': '1.4-inch AMOLED touchscreen (454 x 454 resolution)',
      'Bezel': 'Lightweight Titanium bezel with Corning Gorilla Glass DX',
      'Battery Life': 'Smartwatch mode: up to 23 days; GPS mode: up to 31 hours',
      'Sensors': 'Multi-band GNSS with SatIQ, Pulse Ox, Barometric Altimeter, Compass, Gyroscope',
      'Weight': '53 grams featherlight athletic construction',
    },
    features: [
      'SatIQ technology dynamically selects multi-band GPS to optimize battery life',
      'Training Readiness score tells you whether today is a good day to go hard',
      'Real-time Stamina insights prevent you from burning out early in the race',
    ],
    dimensions: '47.2 x 47.2 x 13.2 mm',
    weight: '53 grams',
    warranty: '2-Year Garmin India Domestic Warranty',
    shippingInfo: 'Fast dispatch with tamper-proof packaging.',
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'google-pixel-watch-3',
    name: 'Google Pixel Watch 3 (45mm, Matte Black Aluminum with Obsidian Active Band)',
    brand: 'Google',
    category: 'Smartwatches & Wearables',
    sku: 'GGL-PW3-45-BLK',
    price: 39900,
    originalPrice: 39900,
    stock: 18,
    rating: 4.6,
    reviewCount: 1120,
    tagline: 'Actua AMOLED display 2000 nits. Deep Fitbit integration. Loss of Pulse detection.',
    description: 'Larger 45mm circular smartwatch with 2x brighter Actua AMOLED display, Qualcomm SW5100 processor, advanced running form analytics, and deep Google suite integration.',
    fullDescription: 'Google Pixel Watch 3 introduces a larger 45mm size with 40% more screen area and 1-2000 nits dynamic refresh. Includes industry-first Loss of Pulse Detection that can automatically dial emergency services if the heart stops.',
    featured: false,
    newArrival: true,
    tag: 'Fitbit Powered',
    specifications: {
      'Display': '1.4-inch Actua AMOLED (456 x 456, 1-60Hz Ddr, 2000 nits peak)',
      'Processor': 'Qualcomm SW5100 with Cortex M33 co-processor',
      'Sensors': 'Loss of pulse sensor, cEDA for stress, ECG, SpO2, Skin temperature',
      'Battery': '420 mAh (up to 36 hours with Battery Saver mode)',
      'Water Resistance': '5 ATM / IP68 water resistance',
    },
    features: [
      'Loss of Pulse detection initiates automated emergency call if heartbeat ceases',
      'Advanced Running Form tracks cadence, stride length, and vertical ratio',
      'Real-time Google Maps offline navigation and Google Assistant on wrist',
    ],
    dimensions: '45 x 45 x 12.3 mm',
    weight: '37 grams (without band)',
    warranty: '1-Year Google Official Warranty',
    shippingInfo: 'Dispatched within 24 hours via express logistics.',
    image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'oneplus-watch-2',
    name: 'OnePlus Watch 2 (Radiant Steel, 100-Hour Battery Wear OS 4)',
    brand: 'OnePlus',
    category: 'Smartwatches & Wearables',
    sku: '1PL-WAT2-STL-BLK',
    price: 24999,
    originalPrice: 27999,
    stock: 26,
    rating: 4.7,
    reviewCount: 1940,
    tagline: 'Dual-Engine Architecture. 100-hour battery life. Stainless steel unibody.',
    description: 'Flagship Wear OS smartwatch pairing Snapdragon W5 Gen 1 with BES2700 efficiency chipset. Delivers up to 100 hours of full smartwatch use, sapphire crystal face, and dual-frequency GPS.',
    fullDescription: 'The OnePlus Watch 2 solves the smartwatch battery dilemma. Two distinct processors run two separate operating systems simultaneously: Wear OS 4 for apps and an RTOS for background health tracking.',
    featured: false,
    newArrival: false,
    tag: '100-Hour WearOS',
    specifications: {
      'Case': 'Stainless steel chassis with 2.5D Sapphire Crystal glass',
      'Dual Chipset': 'Qualcomm Snapdragon W5 Gen 1 + BES2700 efficiency MCU',
      'Display': '1.43-inch AMOLED (466 x 466, 60Hz, 1000 nits High Brightness Mode)',
      'Battery': '500 mAh with 7.5W VOOC Fast Charging (charges to 100% in 60 minutes)',
      'Water Resistance': '5 ATM + IP68 + MIL-STD-810H durability standard',
    },
    features: [
      'Dual-Engine Architecture achieves genuine 100-hour Wear OS battery lifespan',
      'Independent L1 + L5 dual frequency antenna handles urban signal reflection',
      'Over 100 sports modes including specialized professional tennis analysis',
    ],
    dimensions: '47.0 x 46.6 x 12.1 mm',
    weight: '49 grams (without band), 80 grams (with strap)',
    warranty: '1-Year OnePlus India Warranty',
    shippingInfo: 'Fast dispatch with real-time transit telemetry.',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    ],
  },
];
